name: Publish APP preview OTA

on:
  push:
    branches: ['main']
    paths:
      - 'apps/mobile/app/**'
      - 'apps/mobile/src/**'
      - 'apps/mobile/assets/**'

jobs:
  publish_preview_update:
    name: Publish preview update
    environment: preview
    type: update
    params:
      platform: all
      channel: preview
