name: Publish APP preview OTA

on:
  push:
    branches: ['main']
    paths:
      - 'apps/mobile/app/**'
      - 'apps/mobile/src/**'
      - 'apps/mobile/assets/**'
      - '!apps/mobile/src/**/*.test.js'
      - '!apps/mobile/src/**/*.test.mjs'
      - '!apps/mobile/src/**/*.test.ts'
      - '!apps/mobile/src/**/*.test.tsx'
      - '!apps/mobile/assets/app-icon-1024.png'

concurrency:
  cancel_in_progress: true

jobs:
  publish_preview_update:
    name: Publish preview update
    environment: preview
    type: update
    params:
      platform: all
      channel: preview
