const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function load(file,deps){const module={exports:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/'+file,'utf8'),{module,exports:module.exports,require:n=>deps[n]||require(n),console:{error(){}},Buffer,crypto:require('node:crypto').webcrypto,fetch:async()=>{throw Error('unexpected network')},URL,Date},{filename:file});return module.exports}
const U='11111111-1111-4111-8111-111111111111',V='22222222-2222-4222-8222-222222222222',L='33333333-3333-4333-8333-333333333333',A='44444444-4444-4444-8444-444444444444',B='55555555-5555-4555-8555-555555555555';
function setup({user=U,rows={}}={}){const writes=[];const shared={safeText:(v,max=20000)=>String(v??'').trim().slice(0,max),SUPABASE_URL:'https://test.invalid',SERVICE_KEY:'not-a-secret',authenticateUser:async()=>{if(!user)throw Object.assign(Error('请先登录'),{statusCode:401});return{user:{id:user,email:'test@example.invalid'},token:'test'}},rest:async(table,{method='GET',query={},body}={})=>{let items=rows[table]||[];const match=x=>Object.entries(query).every(([k,v])=>{if(String(v).startsWith('eq.'))return String(x[k])===v.slice(3);if(String(v).startsWith('in.('))return v.slice(4,-1).split(',').includes(String(x[k]));return true});if(method==='GET')return items.filter(match);writes.push({table,method,query,body});if(method==='POST'){const row={id:L,...body};(rows[table]??=[]).push(row);return[row]}if(method==='PATCH')return items.filter(match).map(x=>Object.assign(x,body));return[]}};const core=load('_shared/property-core.js',{'./supabase-admin':shared});const account=load('property-account.js',{'./_shared/supabase-admin':shared,'./_shared/property-core':core});const publicApi=load('property-listings-public.js',{'./_shared/supabase-admin':shared,'./_shared/property-core':core});return{core,account,publicApi,writes,rows}}
const input={title:'测试房源标题',address:'123 Test Avenue',neighborhood:'Flushing',property_type:'Condo',listing_type:'sale',price:100,bedrooms:0,authorization_confirmed:true};
const post=(handler,body)=>handler({httpMethod:'POST',headers:{},body:JSON.stringify(body)});
test('all account mutations reject unauthenticated callers',async()=>{const x=setup({user:null});for(const action of ['save_listing','create_claim','create_lead','favorite','upload_file','lead_status'])assert.equal((await post(x.account.handler,{action})).statusCode,401);assert.equal(x.writes.length,0)});
test('strict authorization and numeric validation retain studio zero',()=>{const {account}=setup();assert.equal(account._test.listingInput(input).bedrooms,0);for(const value of [false,'true',1,undefined])assert.throws(()=>account._test.listingInput({...input,authorization_confirmed:value}));assert.throws(()=>account._test.listingInput({...input,price:'NaN'}));assert.throws(()=>account._test.listingInput({...input,bathrooms:-1}))});
test('draft cannot submit without photos and proof',async()=>{const x=setup({rows:{property_listings:[{id:L,source_user_id:U,status:'draft',authorization_confirmed:true}]}});assert.equal((await post(x.account.handler,{action:'submit_listing',id:L})).statusCode,409);assert.equal(x.writes.length,0)});
test('other account cannot edit, upload, or submit an owned listing',async()=>{const x=setup({rows:{property_listings:[{id:L,source_user_id:V,status:'draft'}]}});for(const body of [{action:'save_listing',id:L,...input},{action:'submit_listing',id:L},{action:'upload_file',entity_type:'listing',entity_id:L}])assert.equal((await post(x.account.handler,body)).statusCode,404);assert.equal(x.writes.length,0)});
test('only complete materials progress a draft to pending, not published',async()=>{const x=setup({rows:{property_listings:[{id:L,source_user_id:U,status:'draft',authorization_confirmed:true}],property_files:[{id:U,entity_type:'listing',entity_id:L,category:'photo',mime_type:'image/png'},{id:V,entity_type:'listing',entity_id:L,category:'authorization',mime_type:'application/pdf'}]}});const r=await post(x.account.handler,{action:'submit_listing',id:L});assert.equal(r.statusCode,200);assert.equal(JSON.parse(r.body).record.status,'pending');assert.ok(x.writes.some(w=>w.table==='property_admin_audit'))});
test('suspended agent receives no client leads',async()=>{const x=setup({rows:{property_agents:[{id:A,source_user_id:U,status:'suspended',broker_id:B}],property_brokers:[{id:B,status:'verified'}],property_leads:[{id:L,source_user_id:V,assigned_agent_id:A,message:'private'}]}});const d=JSON.parse((await x.account.handler({httpMethod:'GET',headers:{}})).body);assert.equal(d.assigned.length,0);assert.equal(d.leads.length,0)});
test('wrong agent cannot change a lead status',async()=>{const x=setup({rows:{property_agents:[{id:A,source_user_id:V,status:'verified',broker_id:B}],property_brokers:[{id:B,status:'verified'}],property_leads:[{id:L,assigned_agent_id:A}]}});assert.equal((await post(x.account.handler,{action:'lead_status',id:L,status:'closed'})).statusCode,404);assert.equal(x.writes.length,0)});
test('unknown listing IDs are true 404s',async()=>{const x=setup();assert.equal((await x.publicApi.handler({httpMethod:'GET',queryStringParameters:{id:'missing'}})).statusCode,404);assert.equal((await x.publicApi.handler({httpMethod:'GET',queryStringParameters:{id:L}})).statusCode,404)});
test('publication requires agent and matching certified broker plus material',async()=>{const x=setup({rows:{property_agents:[{id:A,status:'verified',broker_id:B}],property_brokers:[{id:B,status:'verified'}]}});assert.equal(await x.core.publishable({id:L,authorization_confirmed:true,agent_id:A,broker_id:B}),false);x.rows.property_files=[{entity_type:'listing',entity_id:L,category:'photo',mime_type:'image/jpeg'},{entity_type:'listing',entity_id:L,category:'ownership',mime_type:'application/pdf'}];assert.equal(await x.core.publishable({id:L,authorization_confirmed:true,agent_id:A,broker_id:V}),false);assert.equal(await x.core.publishable({id:L,authorization_confirmed:true,agent_id:A,broker_id:B}),true);x.rows.property_brokers[0].status='suspended';assert.equal(await x.core.publishable({id:L,authorization_confirmed:true,agent_id:A,broker_id:B}),false)});
test('uploads reject PDF posing as photo and spoofed image content',()=>{const {core}=setup();assert.throws(()=>core.decodeFile({mime_type:'image/png',base64:Buffer.from('<script>alert(1)</script>').toString('base64'),category:'photo'}));assert.throws(()=>core.decodeFile({mime_type:'application/pdf',base64:Buffer.from('%PDF-1.7').toString('base64'),category:'photo'}));assert.throws(()=>core.decodeFile({mime_type:'image/png',base64:'x'.repeat(5592411),category:'photo'}))});
