const {authenticateUser,rest,safeText,SUPABASE_URL,SERVICE_KEY}=require('./_shared/supabase-admin');
const c=require('./_shared/property-core');
const json=(status,body)=>({statusCode:status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'},body:JSON.stringify(body)});
const table={listing:'property_listings',claim:'property_claims',agent:'property_agents'};
async function owned(type,id,user){const row=await c.one(table[type],id);if(!row||row.source_user_id!==user.id)c.fail('记录不存在或无权访问',404);return row}
async function limited(user,tableName){const rows=await rest(tableName,{query:{select:'id',source_user_id:'eq.'+user.id,created_at:'gte.'+new Date(Date.now()-3600000).toISOString(),limit:'21'}});if(rows.length>=20)c.fail('操作过于频繁，请稍后再试',429)}
function listingInput(b){for(const [k,min,max] of [['title',5,220],['address',5,300],['neighborhood',2,120],['property_type',2,80]]){if(typeof b[k]!=='string'||b[k].trim().length<min||b[k].length>max)c.fail('请完整填写标题、地址、社区与房屋类型')}if(!['sale','rent','commercial'].includes(b.listing_type)||!Number.isFinite(Number(b.price))||Number(b.price)<=0||Number(b.price)>1e9)c.fail('房源类型或价格无效');if(b.authorization_confirmed!==true)c.fail('请确认房源及材料授权');const n=(k,max)=>{if(b[k]===''||b[k]===null||b[k]===undefined)return null;const v=Number(b[k]);if(!Number.isFinite(v)||v<0||v>max||(k==='square_feet'&&!Number.isInteger(v)))c.fail('房屋面积或房间数量无效');return v};return{title:b.title.trim(),address:b.address.trim(),neighborhood:b.neighborhood.trim(),property_type:b.property_type.trim(),listing_type:b.listing_type,price:Number(b.price),bedrooms:n('bedrooms',100),bathrooms:n('bathrooms',100),square_feet:n('square_feet',10000000),description:safeText(b.description,20000),authorization_confirmed:true}}
exports.handler=async event=>{try{
if(!['GET','POST'].includes(event.httpMethod))return json(405,{error:'请求方式不支持'});
const b=event.httpMethod==='POST'?JSON.parse(event.body||'{}'):{};
if(event.httpMethod==='POST'&&b.action==='refresh'){if(typeof b.refresh_token!=='string'||b.refresh_token.length>4000)c.fail('请重新登录',401);const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:process.env.SUPABASE_ANON_KEY||SERVICE_KEY,'content-type':'application/json'},body:JSON.stringify({refresh_token:b.refresh_token})});if(!r.ok)return json(401,{error:'登录已过期，请重新登录'});return json(200,{session:await r.json()})}
const {user,token}=await authenticateUser(event);
if(event.httpMethod==='GET'){
const q=event.queryStringParameters||{};
if(q.action==='file_url'){const f=await c.one('property_files',q.id);if(!f||!table[f.entity_type])c.fail('材料不存在',404);await owned(f.entity_type,f.entity_id,user);return json(200,{url:await c.fileUrl(f),name:f.original_name})}
const ownQuery={source_user_id:'eq.'+user.id,order:'created_at.desc',limit:'100'};
const [listings,claims,leads,favorites,agentRows]=await Promise.all([rest('property_listings',{query:ownQuery}),rest('property_claims',{query:ownQuery}),rest('property_leads',{query:ownQuery}),rest('property_favorites',{query:{user_id:'eq.'+user.id,order:'created_at.desc',limit:'100'}}),rest('property_agents',{query:{source_user_id:'eq.'+user.id,limit:'100'}})]);
const active=[];for(const a of agentRows){const v=await c.verifiedAgent(a.id);if(v)active.push(v)}
const assigned=active.length?await rest('property_leads',{query:{assigned_agent_id:'in.('+active.map(a=>a.id).join(',')+')',order:'created_at.desc',limit:'100'}}):[];
const ids=listings.map(x=>x.id).concat(claims.map(x=>x.id));const files=ids.length?await rest('property_files',{query:{entity_id:'in.('+ids.join(',')+')',select:'id,entity_id,entity_type,category,original_name,size_bytes',limit:'300'}}):[];
return json(200,{user:{id:user.id,email:user.email,display_name:user.user_metadata?.display_name||user.email},listings,claims,leads,favorites,agents:agentRows,assigned,files})}
const action=b.action;
if(action==='logout'){await fetch(SUPABASE_URL+'/auth/v1/logout?scope=local',{method:'POST',headers:{apikey:process.env.SUPABASE_ANON_KEY||SERVICE_KEY,Authorization:'Bearer '+token}});return json(200,{ok:true})}
if(action==='save_listing'){
const fields=listingInput(b);let row;if(b.id){row=await owned('listing',b.id,user);if(!['draft','needs_evidence','rejected'].includes(row.status))c.fail('待审核或已发布房源不能直接修改',409)}else await limited(user,'property_listings');
const agents=await rest('property_agents',{query:{source_user_id:'eq.'+user.id,status:'eq.verified',limit:'10'}});let agent=null;for(const a of agents){agent=await c.verifiedAgent(a.id);if(agent)break}
const payload={...fields,source_user_id:user.id,submitter_email:user.email,submitter_name:safeText(b.submitter_name,120)||user.email,status:'draft',agent_id:agent?.id||null,broker_id:agent?.broker_id||null,updated_at:new Date().toISOString()};
const rows=await rest('property_listings',{method:row?'PATCH':'POST',query:row?{id:'eq.'+row.id,source_user_id:'eq.'+user.id}:{},prefer:'return=representation',body:payload});await c.audit(user,'listing.draft_saved','listing',rows[0].id);return json(200,{record:rows[0]})}
if(action==='upload_file'){if(!['listing','claim'].includes(b.entity_type))c.fail('不能上传到此对象');const row=await owned(b.entity_type,b.entity_id,user);if(b.entity_type==='listing'&&!['draft','needs_evidence','rejected'].includes(row.status))c.fail('该房源正在审核或已发布',409);if(b.entity_type==='claim'&&!['pending','needs_evidence'].includes(row.status))c.fail('该申请已处理',409);return json(201,{file:await c.upload(user,b)})}
if(action==='submit_listing'){const row=await owned('listing',b.id,user);if(row.status==='pending')return json(200,{record:row});if(!['draft','needs_evidence','rejected'].includes(row.status))c.fail('当前状态不能提交',409);if(!row.authorization_confirmed||!c.evidenceReady(await c.evidence('listing',row.id)))c.fail('请上传至少一张房源照片及产权证明或挂牌授权',409);const rows=await rest('property_listings',{method:'PATCH',query:{id:'eq.'+row.id,source_user_id:'eq.'+user.id},body:{status:'pending',updated_at:new Date().toISOString()},prefer:'return=representation'});await c.audit(user,'listing.submitted','listing',row.id);return json(200,{record:rows[0]})}
if(action==='create_claim'){if(safeText(b.claimant_name).length<2||safeText(b.relationship).length<5)c.fail('请填写姓名、执照和所属公司等认领说明');let agent;if(b.agent_id){if(!c.uuid(b.agent_id))c.fail('经纪主页编号无效');agent=await c.one('property_agents',b.agent_id);if(!agent)c.fail('经纪主页不存在',404);if(safeText(b.license_number).toLowerCase()!==String(agent.license_number||'').trim().toLowerCase())c.fail('执照号码与主页不匹配',409)}else{const license=safeText(b.license_number,100),brokerName=safeText(b.broker_name,180);if(license.length<3||brokerName.length<2)c.fail('请填写执照号码与所属 Broker');const matches=await rest('property_agents',{query:{license_number:'eq.'+license,license_state:'eq.NY',limit:'1'}});agent=matches[0];if(!agent){await limited(user,'property_claims');const brokers=await rest('property_brokers',{query:{legal_name:'eq.'+brokerName,limit:'1'}});let broker=brokers[0];if(!broker)broker=(await rest('property_brokers',{method:'POST',prefer:'return=representation',body:{legal_name:brokerName,status:'pending'}}))[0];agent=(await rest('property_agents',{method:'POST',prefer:'return=representation',body:{display_name:safeText(b.claimant_name,160),license_number:license,license_state:'NY',broker_id:broker.id,status:'pending'}}))[0]}}if(agent.source_user_id&&agent.source_user_id!==user.id)c.fail('此主页已绑定其他账号，请联系平台更正',409);await limited(user,'property_claims');const pending=await rest('property_claims',{query:{source_user_id:'eq.'+user.id,agent_id:'eq.'+agent.id,status:'in.(pending,needs_evidence)',limit:'1'}});if(pending.length)return json(200,{record:pending[0]});const rows=await rest('property_claims',{method:'POST',prefer:'return=representation',body:{source_user_id:user.id,claimant_name:safeText(b.claimant_name,160),claimant_email:user.email,claimant_phone:safeText(b.phone,60),agent_id:agent.id,relationship:safeText(b.relationship,3000),status:'pending'}});await c.audit(user,'claim.submitted','claim',rows[0].id);return json(201,{record:rows[0]})}
if(action==='create_lead'){if(!c.uuid(b.listing_id)||safeText(b.message).length<5||safeText(b.contact_name).length<2||(!safeText(b.contact_phone)&&!user.email))c.fail('请填写联系姓名和咨询内容');const row=await c.one('property_listings',b.listing_id);if(row?.status!=='published'||!await c.publishable(row))c.fail('该房源已下架或暂不接受咨询',409);await limited(user,'property_leads');const message=safeText(b.message,2000);const recent=await rest('property_leads',{query:{source_user_id:'eq.'+user.id,listing_id:'eq.'+row.id,message:'eq.'+message,created_at:'gte.'+new Date(Date.now()-60000).toISOString(),limit:'1'}});if(recent.length)return json(200,{record:recent[0]});const rows=await rest('property_leads',{method:'POST',prefer:'return=representation',body:{source_user_id:user.id,listing_id:row.id,assigned_agent_id:row.agent_id,contact_name:safeText(b.contact_name,120),contact_email:user.email,contact_phone:safeText(b.contact_phone,60),message,status:'assigned',assigned_at:new Date().toISOString()}});await c.audit(user,'lead.created','lead',rows[0].id,{listing_id:row.id,assigned_agent_id:row.agent_id});return json(201,{record:rows[0]})}
if(action==='favorite'){if(!c.uuid(b.listing_id)||typeof b.saved!=='boolean')c.fail('收藏请求无效');if(!b.saved){await rest('property_favorites',{method:'DELETE',query:{user_id:'eq.'+user.id,listing_id:'eq.'+b.listing_id}});return json(200,{saved:false})}const row=await c.one('property_listings',b.listing_id);if(row?.status!=='published'||!await c.publishable(row))c.fail('房源已下架',404);if(typeof b.saved!=='boolean')c.fail('收藏状态无效');if(b.saved)await rest('property_favorites',{method:'POST',query:{on_conflict:'user_id,listing_id'},prefer:'resolution=ignore-duplicates,return=minimal',body:{user_id:user.id,listing_id:row.id}});else await rest('property_favorites',{method:'DELETE',query:{user_id:'eq.'+user.id,listing_id:'eq.'+row.id}});return json(200,{saved:b.saved})}
if(action==='lead_status'){if(!['contacted','closed'].includes(b.status))c.fail('状态无效');const row=await c.one('property_leads',b.id);const agent=row?await c.verifiedAgent(row.assigned_agent_id):null;if(!agent||agent.source_user_id!==user.id)c.fail('线索不存在或未分配给您',404);const rows=await rest('property_leads',{method:'PATCH',query:{id:'eq.'+row.id,assigned_agent_id:'eq.'+agent.id},prefer:'return=representation',body:{status:b.status}});await c.audit(user,'lead.'+b.status,'lead',row.id);return json(200,{record:rows[0]})}
return json(400,{error:'操作不支持'});
}catch(e){console.error('property-account',e.statusCode||500);return json(e.statusCode||500,{error:e.statusCode&&e.statusCode<500?e.message:'处理失败，请稍后重试；尚未确认成功'})}};
exports._test={listingInput};
