const { authenticateStaff, rest, SUPABASE_URL, SERVICE_KEY, safeText } = require("./_shared/supabase-admin");
const json=(status,body)=>({statusCode:status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"},body:JSON.stringify(body)});
const uuid=v=>/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(String(v||""));
const tables={listing:"property_listings",agent:"property_agents",broker:"property_brokers",claim:"property_claims",lead:"property_leads"};
const statuses={listing:["draft","pending","needs_evidence","approved","published","rejected","withdrawn"],agent:["unclaimed","pending","verified","rejected","suspended"],broker:["pending","verified","rejected","suspended"],claim:["pending","needs_evidence","approved","rejected","cancelled"],lead:["new","assigned","contacted","closed","spam"]};
async function audit(i,action,type,id,detail={}){await rest("property_admin_audit",{method:"POST",prefer:"return=minimal",body:{actor_user_id:i.user.id,actor_email:i.user.email||i.admin.email||null,action,entity_type:type,entity_id:String(id),detail}})}
async function list(table,limit=100){return rest(table,{query:{select:"*",order:"created_at.desc",limit:String(limit)}})}
async function dashboard(){const [listings,agents,brokers,claims,leads,files]=await Promise.all([list("property_listings"),list("property_agents"),list("property_brokers"),list("property_claims"),list("property_leads"),list("property_files",200)]);const n=(rows,s)=>rows.filter(x=>x.status===s).length;return{counts:{listings:listings.length,pendingListings:n(listings,"pending")+n(listings,"needs_evidence"),pendingAgents:n(agents,"pending"),brokers:brokers.length,pendingClaims:n(claims,"pending")+n(claims,"needs_evidence"),newLeads:n(leads,"new")},listings,agents,brokers,claims,leads,files}}
async function upload(i,b){const type=safeText(b.entity_type,30),id=safeText(b.entity_id,80),category=safeText(b.category,40),name=safeText(b.name,180),mime=safeText(b.mime_type,80),data=String(b.base64||"").replace(/^data:[^;]+;base64,/,"");if(!["listing","agent","broker","claim"].includes(type)||!uuid(id))throw Object.assign(new Error("文件关联对象无效"),{statusCode:400});if(!["photo","ownership","authorization","license","broker_proof","identity","other"].includes(category))throw Object.assign(new Error("证明类型无效"),{statusCode:400});if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(mime))throw Object.assign(new Error("仅支持 JPG、PNG、WebP 或 PDF"),{statusCode:400});const bytes=Buffer.from(data,"base64");if(!bytes.length||bytes.length>12582912)throw Object.assign(new Error("文件必须小于12MB"),{statusCode:400});const exists=await rest(tables[type],{query:{select:"id",id:"eq."+id,limit:"1"}});if(!exists.length)throw Object.assign(new Error("关联记录不存在"),{statusCode:404});const ext=mime==="application/pdf"?"pdf":mime.split("/")[1].replace("jpeg","jpg"),path=type+"/"+id+"/"+crypto.randomUUID()+"."+ext;const response=await fetch(SUPABASE_URL+"/storage/v1/object/property-private/"+path,{method:"POST",headers:{apikey:SERVICE_KEY,Authorization:"Bearer "+SERVICE_KEY,"content-type":mime,"x-upsert":"false"},body:bytes});if(!response.ok)throw Object.assign(new Error(await response.text()||"文件上传失败"),{statusCode:response.status});const rows=await rest("property_files",{method:"POST",prefer:"return=representation",body:{entity_type:type,entity_id:id,category,storage_path:path,original_name:name||"document."+ext,mime_type:mime,size_bytes:bytes.length,uploaded_by:i.user.id}});await audit(i,"file.uploaded",type,id,{category,file_id:rows[0]?.id});return rows[0]}
exports.handler=async event=>{if(event.httpMethod==="OPTIONS")return json(204,{});try{const identity=await authenticateStaff(event,["owner","admin","editor"]);if(event.httpMethod==="GET")return json(200,await dashboard());if(event.httpMethod!=="POST")return json(405,{error:"Method not allowed"});const b=JSON.parse(event.body||"{}"),action=safeText(b.action,60);
if(action==="create_listing"){for(const k of ["title","address","neighborhood","listing_type","property_type","price"])if(!String(b[k]??"").trim())return json(400,{error:"请完整填写房源、地址、类型和价格"});if(!["sale","rent","commercial"].includes(b.listing_type)||!(Number(b.price)>0))return json(400,{error:"房源类型或价格无效"});const rows=await rest("property_listings",{method:"POST",prefer:"return=representation",body:{title:safeText(b.title,220),address:safeText(b.address,300),neighborhood:safeText(b.neighborhood,120),listing_type:b.listing_type,property_type:safeText(b.property_type,80),price:Number(b.price),bedrooms:b.bedrooms===""?null:Number(b.bedrooms),bathrooms:b.bathrooms===""?null:Number(b.bathrooms),square_feet:b.square_feet===""?null:Number(b.square_feet),description:safeText(b.description,20000),submitter_name:safeText(b.submitter_name,120)||null,submitter_email:safeText(b.submitter_email,200)||null,authorization_confirmed:Boolean(b.authorization_confirmed),status:"pending"}});await audit(identity,"listing.created","listing",rows[0].id,{status:"pending"});return json(201,{record:rows[0]})}
if(action==="upload_file")return json(201,{file:await upload(identity,b)});
if(action==="set_status"){const type=safeText(b.entity_type,30),id=safeText(b.entity_id,80),status=safeText(b.status,40);if(!tables[type]||!uuid(id)||!statuses[type]?.includes(status))return json(400,{error:"审核对象或状态无效"});const patch={status,review_note:safeText(b.review_note,3000)||null,reviewed_by:identity.user.id,reviewed_at:new Date().toISOString()};if(type==="listing"&&status==="published"){if(!b.confirm_publish)return json(400,{error:"发布房源必须二次确认"});patch.published_at=new Date().toISOString()}const rows=await rest(tables[type],{method:"PATCH",query:{id:"eq."+id},prefer:"return=representation",body:patch});if(!rows.length)return json(404,{error:"记录不存在"});await audit(identity,type+".status_changed",type,id,{status,review_note:patch.review_note});return json(200,{record:rows[0]})}
if(action==="assign_lead"){const id=safeText(b.entity_id,80),agentId=safeText(b.agent_id,80);if(!uuid(id)||!uuid(agentId))return json(400,{error:"线索或经纪ID无效"});const agents=await rest("property_agents",{query:{select:"id,status",id:"eq."+agentId,status:"eq.verified",limit:"1"}});if(!agents.length)return json(400,{error:"只能把线索分配给已认证经纪"});const rows=await rest("property_leads",{method:"PATCH",query:{id:"eq."+id},prefer:"return=representation",body:{assigned_agent_id:agentId,status:"assigned",assigned_by:identity.user.id,assigned_at:new Date().toISOString()}});await audit(identity,"lead.assigned","lead",id,{agent_id:agentId});return json(200,{record:rows[0]})}
return json(400,{error:"未知操作"})}catch(e){console.error("property-admin",e);return json(e.statusCode||500,{error:e.message||"房产后台处理失败"})}};