const core = require('./_shared/property-core');
const { authenticateStaff, rest, SUPABASE_URL, SERVICE_KEY, safeText } = require("./_shared/supabase-admin");
const json=(status,body)=>({statusCode:status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"},body:JSON.stringify(body)});
const uuid=v=>/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(String(v||""));
const tables={listing:"property_listings",agent:"property_agents",broker:"property_brokers",claim:"property_claims",lead:"property_leads"};
const statuses={listing:["draft","pending","needs_evidence","approved","published","rejected","withdrawn"],agent:["unclaimed","pending","verified","rejected","suspended"],broker:["pending","verified","rejected","suspended"],claim:["pending","needs_evidence","approved","rejected","cancelled"],lead:["new","assigned","contacted","closed","spam"]};
async function audit(i,action,type,id,detail={}){await rest("property_admin_audit",{method:"POST",prefer:"return=minimal",body:{actor_user_id:i.user.id,actor_email:i.user.email||i.admin.email||null,action,entity_type:type,entity_id:String(id),detail}})}
async function list(table,limit=100){return rest(table,{query:{select:"*",order:"created_at.desc",limit:String(limit)}})}
async function dashboard(){const [listings,agents,brokers,claims,leads,files]=await Promise.all([list("property_listings"),list("property_agents"),list("property_brokers"),list("property_claims"),list("property_leads"),list("property_files",200)]);const n=(rows,s)=>rows.filter(x=>x.status===s).length;return{counts:{listings:listings.length,pendingListings:n(listings,"pending")+n(listings,"needs_evidence"),pendingAgents:n(agents,"pending"),brokers:brokers.length,pendingClaims:n(claims,"pending")+n(claims,"needs_evidence"),newLeads:n(leads,"new")},listings,agents,brokers,claims,leads,files}}
async function upload(i,b){const table={listing:'property_listings',agent:'property_agents',broker:'property_brokers',claim:'property_claims'}[b.entity_type];if(!table||!await core.one(table,b.entity_id))core.fail('关联记录不存在',404);return core.upload(i.user,b)}
exports.handler=async event=>{if(event.httpMethod==="OPTIONS")return json(204,{});try{const identity=await authenticateStaff(event,["owner","admin","editor"]);if(event.httpMethod==="GET"){const q=event.queryStringParameters||{};if(q.action==="file_url"){const id=safeText(q.id,80);const rows=await rest("property_files",{query:{select:"id,storage_path,original_name,mime_type",id:"eq."+id,limit:"1"}});if(!rows.length)return json(404,{error:"文件不存在"});return json(200,{url:await core.fileUrl(rows[0]),name:rows[0].original_name})}return json(200,await dashboard())}if(event.httpMethod!=="POST")return json(405,{error:"Method not allowed"});const b=JSON.parse(event.body||"{}"),action=safeText(b.action,60);
if(action==="create_listing"){for(const k of ["title","address","neighborhood","listing_type","property_type","price"])if(!String(b[k]??"").trim())return json(400,{error:"请完整填写房源、地址、类型和价格"});if(!["sale","rent","commercial"].includes(b.listing_type)||!(Number(b.price)>0))return json(400,{error:"房源类型或价格无效"});const rows=await rest("property_listings",{method:"POST",prefer:"return=representation",body:{title:safeText(b.title,220),address:safeText(b.address,300),neighborhood:safeText(b.neighborhood,120),listing_type:b.listing_type,property_type:safeText(b.property_type,80),price:Number(b.price),bedrooms:b.bedrooms===""?null:Number(b.bedrooms),bathrooms:b.bathrooms===""?null:Number(b.bathrooms),square_feet:b.square_feet===""?null:Number(b.square_feet),description:safeText(b.description,20000),submitter_name:safeText(b.submitter_name,120)||null,submitter_email:safeText(b.submitter_email,200)||null,authorization_confirmed:b.authorization_confirmed===true,agent_id:core.uuid(b.agent_id)?b.agent_id:null,broker_id:core.uuid(b.broker_id)?b.broker_id:null,status:"pending"}});await audit(identity,"listing.created","listing",rows[0].id,{status:"pending"});return json(201,{record:rows[0]})}
if(action==="upload_file")return json(201,{file:await upload(identity,b)});
if(action==="create_broker"){if(safeText(b.legal_name).length<2||!safeText(b.license_number))core.fail("请填写 Broker 名称与执照号");const rows=await rest("property_brokers",{method:"POST",prefer:"return=representation",body:{legal_name:safeText(b.legal_name,180),license_number:safeText(b.license_number,100)||null,contact_email:safeText(b.email,200)||null,contact_phone:safeText(b.phone,60)||null,status:"pending"}});await audit(identity,"broker.created","broker",rows[0].id,{});return json(201,{record:rows[0]})}
if(action==="create_agent"){if(safeText(b.display_name).length<2||!safeText(b.license_number))core.fail("请填写经纪姓名与执照号");const broker=safeText(b.broker_id,80);if(broker&&!uuid(broker))return json(400,{error:"Broker ID无效"});const rows=await rest("property_agents",{method:"POST",prefer:"return=representation",body:{display_name:safeText(b.display_name,160),email:safeText(b.email,200)||null,phone:safeText(b.phone,60)||null,license_number:safeText(b.license_number,100)||null,license_state:safeText(b.license_state,20)||"NY",broker_id:broker||null,status:"pending"}});await audit(identity,"agent.created","agent",rows[0].id,{});return json(201,{record:rows[0]})}
if(action==="create_claim"){const rows=await rest("property_claims",{method:"POST",prefer:"return=representation",body:{claimant_name:safeText(b.claimant_name,160),claimant_email:safeText(b.email,200)||null,claimant_phone:safeText(b.phone,60)||null,relationship:safeText(b.relationship,100),agent_id:uuid(b.agent_id)?b.agent_id:null,listing_id:uuid(b.listing_id)?b.listing_id:null,status:"pending"}});await audit(identity,"claim.created","claim",rows[0].id,{});return json(201,{record:rows[0]})}
if(action==="edit_identity"){const type=b.entity_type;if(!["broker","agent"].includes(type)||!core.uuid(b.entity_id))core.fail("对象无效");const row=await core.one(tables[type],b.entity_id);if(!row)core.fail("记录不存在",404);if(!safeText(b.license_number))core.fail("请填写执照号");const patch={license_number:safeText(b.license_number,100),status:"pending",updated_at:new Date().toISOString()};const rows=await rest(tables[type],{method:"PATCH",query:{id:"eq."+b.entity_id},prefer:"return=representation",body:patch});await audit(identity,"identity.updated",type,b.entity_id,patch);return json(200,{record:rows[0]})}
if(action==="link_record"){const type=b.entity_type,id=b.entity_id;if(!["listing","agent"].includes(type)||!core.uuid(id))core.fail("关联对象无效");const row=await core.one(tables[type],id);if(!row)core.fail("记录不存在",404);let patch;if(type==="agent"){if(!await core.one("property_brokers",b.broker_id))core.fail("Broker 不存在");patch={broker_id:b.broker_id}}else{const agent=await core.one("property_agents",b.agent_id);if(!agent?.broker_id)core.fail("请先给经纪绑定 Broker");patch={agent_id:agent.id,broker_id:agent.broker_id}}const rows=await rest(tables[type],{method:"PATCH",query:{id:"eq."+id},prefer:"return=representation",body:patch});await audit(identity,"record.linked",type,id,patch);return json(200,{record:rows[0]})}
if(action==="set_status"){const type=safeText(b.entity_type,30),id=safeText(b.entity_id,80),status=safeText(b.status,40);if(!tables[type]||!uuid(id)||!statuses[type]?.includes(status))return json(400,{error:"审核对象或状态无效"});if(status==="verified"&&["agent","broker"].includes(type)){const row=await core.one(tables[type],id),files=await core.evidence(type,id);if(!row?.license_number||!files.some(f=>["license","broker_proof"].includes(f.category)))core.fail("请先补齐执照号码和执照证明",409);if(type==="agent"){const broker=await core.one("property_brokers",row.broker_id);if(broker?.status!=="verified")core.fail("所属 Broker 须先认证",409)}}const patch={status,review_note:safeText(b.review_note,3000)||null,reviewed_by:identity.user.id,reviewed_at:new Date().toISOString()};if(type==="listing"&&status==="published"){if(!b.confirm_publish)return json(400,{error:"发布房源必须二次确认"});const listing=await core.one('property_listings',id);if(!await core.publishable(listing))return json(409,{error:'发布必须具备授权确认、照片、产权或挂牌证明，以及相互匹配的已认证经纪和 Broker'});patch.published_at=new Date().toISOString()}const rows=await rest(tables[type],{method:"PATCH",query:{id:"eq."+id},prefer:"return=representation",body:patch});if(!rows.length)return json(404,{error:"记录不存在"});await audit(identity,type+".status_changed",type,id,{status,review_note:patch.review_note});return json(200,{record:rows[0]})}
if(action==="assign_lead"){const id=safeText(b.entity_id,80),agentId=safeText(b.agent_id,80);if(!uuid(id)||!uuid(agentId))return json(400,{error:"线索或经纪ID无效"});const verified=await core.verifiedAgent(agentId);if(!verified)return json(400,{error:"只能把线索分配给已认证经纪"});const rows=await rest("property_leads",{method:"PATCH",query:{id:"eq."+id},prefer:"return=representation",body:{assigned_agent_id:agentId,status:"assigned",assigned_by:identity.user.id,assigned_at:new Date().toISOString()}});if(!rows.length)return json(404,{error:"线索不存在"});await audit(identity,"lead.assigned","lead",id,{agent_id:agentId});return json(200,{record:rows[0]})}
return json(400,{error:"未知操作"})}catch(e){console.error("property-admin",e);return json(e.statusCode||500,{error:e.statusCode&&e.statusCode<500?e.message:"操作未完成，请检查材料、绑定关系与审核状态后重试"})}};