const assert=require('node:assert/strict');
const test=require('node:test');
const vm=require('node:vm');
const fs=require('node:fs');
const geography=require('./_shared/job-geography');
const source=fs.readFileSync(require.resolve('./public-jobs'),'utf8');
function runWith(rest){const sandbox={exports:{},require:name=>name.includes('job-geography')?{...geography,locations:async()=>({centers:[],cities:[]})}:{rest},console,URL,Date};vm.runInNewContext(source,sandbox);return async params=>JSON.parse((await sandbox.exports.handler({httpMethod:'GET',queryStringParameters:params})).body);}
const job={id:'11111111-1111-4111-8111-111111111111',title:'CNA',category_slug:'truck-driver',effective_category:'home-care',city:'Wilmington',state_code:'MA',status:'open',map_latitude:42.56,map_longitude:-71.16,location_approximate:true,contact_public:true,contact_method:'phone',contact_value:'5551234567',employer_user_id:'private'};
test('state-qualified duplicate cities resolve correctly and ambiguous names do not pick an arbitrary state',()=>{assert.equal(geography.resolve('Wilmington, MA').state,'MA');assert.equal(geography.resolve('Wilmington, DE').state,'DE');assert.equal(geography.resolve('Wilmington'),null);assert.equal(geography.resolve('法拉盛').state,'NY');assert.equal(geography.resolve('LA').state,'CA');assert.equal(geography.resolve('Hyannis','MA').state,'MA');assert.equal(geography.resolve('Charlestown','MA').state,'MA');});
test('Chinese and English aliases match identical places; multi-city filters retain each state',async()=>{let options;const run=runWith(async(_,args)=>{options=args.body.p_options;return [job];});await run({place:'亚特兰大'});const first=JSON.stringify(options.places);await run({place:'Atlanta'});assert.equal(JSON.stringify(options.places),first);await run({place:'Wilmington, MA;Wilmington, DE'});assert.deepEqual(Array.from(options.places,p=>p.state),['MA','DE']);});
test('public response includes corrected category and approximate map coordinates without private fields',async()=>{const run=runWith(async()=>[job]);const data=await run({place:'Wilmington, MA'});assert.equal(data.items[0].category_slug,'home-care');assert.equal(data.items[0].latitude,42.56);assert.equal(data.items[0].location_approximate,true);assert.equal(data.items[0].employer_user_id,undefined);assert.equal(data.items[0].contact.type,'phone');});
test('ZIP search uses a verified ZCTA center and supports nearby pagination',async()=>{let opts;const run=runWith(async(_,args)=>{opts=args.body.p_options;return [job];});const data=await run({zip:'11354',nearby:'25',offset:'60'});assert.equal(opts.radius,25);assert.equal(opts.offset,60);assert.equal(opts.origins.length,1);assert.ok(opts.origins[0].lat>40&&opts.origins[0].lat<41);assert.equal(data.recommendation.radius_miles,25);});
test('empty first city page expands, while an empty later page keeps local scope',async()=>{let calls=0;const run=runWith(async(_,args)=>{calls++;return args.body.p_options.radius?[job]:[];});const first=await run({place:'Suwanee'});assert.equal(first.recommendation.radius_miles,50);assert.equal(calls,2);calls=0;const end=await run({place:'Atlanta',offset:'60'});assert.equal(end.recommendation,null);assert.equal(calls,1);});
test('invalid ZIP returns a useful error instead of unrelated jobs',async()=>{const data=await runWith(async()=>{throw Error('should not query')})({zip:'ABCDE'});assert.equal(data.error,'Invalid ZIP Code');});
