[build]
  publish = "."


[[redirects]]
  from = "/wp-content/uploads/:year/:month/:file"
  to = "/assets/news-images/:year/:month/:file"
  status = 200

[[redirects]]
  from = "http://new.trrb.net/*"
  to = "https://new.trrb.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/data/trump-pending.json"
  to = "/"
  status = 404
  force = true
