-- 唐人日报 V3 新闻引擎：在 Supabase SQL Editor 中执行一次
alter table public.articles add column if not exists source_url text default '';
alter table public.articles add column if not exists source_name text default '';
alter table public.articles add column if not exists source_account text default '';
alter table public.articles add column if not exists source_level text default '';
alter table public.articles add column if not exists ai_confidence integer default 0;
alter table public.articles add column if not exists ai_review_reason text default '';
alter table public.articles add column if not exists automation_source text default '';
alter table public.articles add column if not exists external_id text;
alter table public.articles add column if not exists event_date timestamptz;
alter table public.articles add column if not exists arrest_count integer;
alter table public.articles add column if not exists city text default '';
alter table public.articles add column if not exists state text default '';
alter table public.articles add column if not exists count_in_ice_stats boolean default false;
alter table public.articles add column if not exists primary_section text default '';
alter table public.articles add column if not exists related_sections jsonb default '[]'::jsonb;
alter table public.articles add column if not exists updated_at timestamptz default now();
create unique index if not exists articles_external_id_uidx on public.articles(external_id) where external_id is not null;

create table if not exists public.news_sources (
  id text primary key,
  name text not null,
  agency text default '',
  branch text default '',
  level text not null default 'media',
  state text default '',
  city text default '',
  coverage_area jsonb default '[]'::jsonb,
  source_type text not null default 'media',
  source_level text not null default 'C',
  website text default '',
  newsroom_url text default '',
  rss_url text default '',
  x_account text default '',
  active boolean default true,
  last_checked_at timestamptz,
  last_success_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.automation_logs (
  id bigint generated by default as identity primary key,
  pipeline text not null,
  run_at timestamptz default now(),
  fetched integer default 0,
  processed integer default 0,
  published integer default 0,
  drafted integer default 0,
  duplicates integer default 0,
  failed integer default 0,
  details jsonb default '{}'::jsonb
);

create table if not exists public.article_versions (
  id bigint generated by default as identity primary key,
  article_id uuid not null references public.articles(id) on delete cascade,
  snapshot jsonb not null,
  changed_by uuid,
  created_at timestamptz default now()
);

create or replace function public.capture_article_version()
returns trigger language plpgsql security definer as $$
begin
  if tg_op = 'UPDATE' then
    insert into public.article_versions(article_id, snapshot, changed_by)
    values (old.id, to_jsonb(old), auth.uid());
    new.updated_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_capture_article_version on public.articles;
create trigger trg_capture_article_version before update on public.articles
for each row execute function public.capture_article_version();

alter table public.news_sources enable row level security;
alter table public.automation_logs enable row level security;
alter table public.article_versions enable row level security;

-- 已有 admin_users 表时，管理员可读取；自动化使用 service_role 写入并绕过 RLS。
drop policy if exists "admins read news sources" on public.news_sources;
create policy "admins read news sources" on public.news_sources for select to authenticated using (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
);
drop policy if exists "admins manage news sources" on public.news_sources;
create policy "admins manage news sources" on public.news_sources for all to authenticated using (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
) with check (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
);
drop policy if exists "admins read automation logs" on public.automation_logs;
create policy "admins read automation logs" on public.automation_logs for select to authenticated using (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
);
drop policy if exists "admins read article versions" on public.article_versions;
create policy "admins read article versions" on public.article_versions for select to authenticated using (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
);


-- V3.1 高标准补丁：SEO、来源发现、URL重定向、状态与安全约束
alter table public.articles add column if not exists seo_title text default '';
alter table public.articles add column if not exists seo_description text default '';
alter table public.articles add column if not exists canonical_url text default '';
alter table public.articles add column if not exists image_alt text default '';
alter table public.articles add column if not exists visibility text default 'private';
alter table public.articles add column if not exists hidden_at timestamptz;
alter table public.articles add column if not exists archived_at timestamptz;
alter table public.articles add column if not exists risk_flags jsonb default '[]'::jsonb;
alter table public.articles add column if not exists independent_source_count integer default 0;
alter table public.articles add column if not exists supporting_sources jsonb default '[]'::jsonb;
alter table public.articles add column if not exists slug_locked boolean default false;

alter table public.news_sources add column if not exists topics jsonb default '[]'::jsonb;
alter table public.news_sources add column if not exists auto_publish boolean default false;
alter table public.news_sources add column if not exists blacklisted boolean default false;
alter table public.news_sources add column if not exists notes text default '';

create table if not exists public.discovered_sources (
  id bigint generated by default as identity primary key,
  name text not null,
  agency_guess text default '',
  source_url text default '',
  x_account text default '',
  discovered_from text default '',
  status text not null default 'pending',
  confidence integer default 0,
  created_at timestamptz default now(),
  reviewed_at timestamptz,
  reviewed_by uuid
);

create table if not exists public.url_redirects (
  id bigint generated by default as identity primary key,
  old_path text not null unique,
  new_path text not null,
  article_id uuid references public.articles(id) on delete cascade,
  created_at timestamptz default now()
);

alter table public.discovered_sources enable row level security;
alter table public.url_redirects enable row level security;
create policy "admins manage discovered sources" on public.discovered_sources for all to authenticated using (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
) with check (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
);
create policy "admins read redirects" on public.url_redirects for select to authenticated using (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
);

create or replace function public.lock_article_slug_after_publish()
returns trigger language plpgsql as $$
begin
  if old.status='published' and old.slug_locked=true and new.slug is distinct from old.slug then
    insert into public.url_redirects(old_path,new_path,article_id)
    values('/article.html?id='||old.id,'/article.html?id='||new.id,new.id)
    on conflict(old_path) do update set new_path=excluded.new_path;
  end if;
  if new.status='published' then new.slug_locked=true; end if;
  if new.status='hidden' then new.hidden_at=coalesce(new.hidden_at,now()); new.visibility='private'; end if;
  if new.status='published' then new.hidden_at=null; new.visibility='public'; end if;
  return new;
end;
$$;
drop trigger if exists trg_lock_article_slug on public.articles;
create trigger trg_lock_article_slug before update on public.articles for each row execute function public.lock_article_slug_after_publish();

create index if not exists articles_public_category_idx on public.articles(status,category_name,published_at desc);
create index if not exists articles_ice_stats_idx on public.articles(count_in_ice_stats,event_date);

-- V4 unified candidate pool and stricter automation indexes
create table if not exists public.news_candidates (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  pipeline text not null,
  source_url text default '',
  source_account text default '',
  source_name text default '',
  source_level text default '',
  raw_text text default '',
  raw_payload jsonb default '{}'::jsonb,
  ai_payload jsonb default '{}'::jsonb,
  proposed_section text default '',
  confidence integer default 0,
  decision text not null default 'pending',
  decision_reason text default '',
  article_id uuid references public.articles(id) on delete set null,
  collected_at timestamptz default now(),
  processed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.news_candidates enable row level security;
drop policy if exists "admins manage news candidates" on public.news_candidates;
create policy "admins manage news candidates" on public.news_candidates for all to authenticated using (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
) with check (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
);

create index if not exists news_candidates_pipeline_decision_idx
  on public.news_candidates(pipeline, decision, collected_at desc);
create index if not exists automation_logs_pipeline_run_idx
  on public.automation_logs(pipeline, run_at desc);
create index if not exists articles_primary_section_status_idx
  on public.articles(primary_section, status, published_at desc);

-- Ensure V4 source registry fields exist even on databases created from older migrations.
alter table public.news_sources add column if not exists topics jsonb default '[]'::jsonb;
alter table public.news_sources add column if not exists auto_publish boolean default false;
alter table public.news_sources add column if not exists blacklisted boolean default false;
alter table public.news_sources add column if not exists notes text default '';
