-- 唐人日报 V3 新闻引擎：在 Supabase SQL Editor 中执行一次
alter table public.articles add column if not exists source_url text default '';
alter table public.articles add column if not exists source_name text default '';
alter table public.articles add column if not exists source_account text default '';
alter table public.articles add column if not exists source_level text default '';
alter table public.articles add column if not exists ai_confidence integer default 0;
alter table public.articles add column if not exists ai_review_reason text default '';
alter table public.articles add column if not exists automation_source text default '';
alter table public.articles add column if not exists external_id text;
alter table public.articles add column if not exists event_date timestamptz;
alter table public.articles add column if not exists arrest_count integer;
alter table public.articles add column if not exists city text default '';
alter table public.articles add column if not exists state text default '';
alter table public.articles add column if not exists count_in_ice_stats boolean default false;
alter table public.articles add column if not exists primary_section text default '';
alter table public.articles add column if not exists related_sections jsonb default '[]'::jsonb;
alter table public.articles add column if not exists updated_at timestamptz default now();
create unique index if not exists articles_external_id_uidx on public.articles(external_id) where external_id is not null;

create table if not exists public.news_sources (
  id text primary key,
  name text not null,
  agency text default '',
  branch text default '',
  level text not null default 'media',
  state text default '',
  city text default '',
  coverage_area jsonb default '[]'::jsonb,
  source_type text not null default 'media',
  source_level text not null default 'C',
  website text default '',
  newsroom_url text default '',
  rss_url text default '',
  x_account text default '',
  active boolean default true,
  last_checked_at timestamptz,
  last_success_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.automation_logs (
  id bigint generated by default as identity primary key,
  pipeline text not null,
  run_at timestamptz default now(),
  fetched integer default 0,
  processed integer default 0,
  published integer default 0,
  drafted integer default 0,
  duplicates integer default 0,
  failed integer default 0,
  details jsonb default '{}'::jsonb
);

create table if not exists public.article_versions (
  id bigint generated by default as identity primary key,
  article_id uuid not null references public.articles(id) on delete cascade,
  snapshot jsonb not null,
  changed_by uuid,
  created_at timestamptz default now()
);

create or replace function public.capture_article_version()
returns trigger language plpgsql security definer as $$
begin
  if tg_op = 'UPDATE' then
    insert into public.article_versions(article_id, snapshot, changed_by)
    values (old.id, to_jsonb(old), auth.uid());
    new.updated_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_capture_article_version on public.articles;
create trigger trg_capture_article_version before update on public.articles
for each row execute function public.capture_article_version();

alter table public.news_sources enable row level security;
alter table public.automation_logs enable row level security;
alter table public.article_versions enable row level security;

-- 已有 admin_users 表时，管理员可读取；自动化使用 service_role 写入并绕过 RLS。
drop policy if exists "admins read news sources" on public.news_sources;
create policy "admins read news sources" on public.news_sources for select to authenticated using (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
);
drop policy if exists "admins manage news sources" on public.news_sources;
create policy "admins manage news sources" on public.news_sources for all to authenticated using (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
) with check (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
);
drop policy if exists "admins read automation logs" on public.automation_logs;
create policy "admins read automation logs" on public.automation_logs for select to authenticated using (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
);
drop policy if exists "admins read article versions" on public.article_versions;
create policy "admins read article versions" on public.article_versions for select to authenticated using (
  exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true)
);
