(function(){
  const D=window.FinanceData;if(!D)return;const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const params=new URLSearchParams(location.search),symbol=(params.get('symbol')||'SPY').toUpperCase(),ref={symbol,exchange:params.get('exchange')||'',assetType:params.get('type')||'ETF',route:'fund'};
  function renderNotFound(){document.title=`${symbol} 未找到｜唐人财经`;const top=$('#fundSymbol');if(top)top.textContent=symbol;const main=$('.stock-content');if(main)main.innerHTML=`<section class="not-found" role="status"><div class="code">${symbol}</div><h1>没有找到这个 ETF / 基金</h1><p>当前 V1 演示数据中没有 ${symbol}。系统不会用 SPY 或其他基金的数据代替，以避免产品信息和费用数据产生误导。</p><a href="./#funds">返回基金研究中心</a></section>`;const fixed=$('.fixed');if(fixed)fixed.hidden=true;document.documentElement.classList.add('detail-ready')}
  async function boot(){
  let f=D.getCachedQuote?.(ref)||D.getFund(symbol);if(D.getFundAsync){try{f=await D.getFundAsync(ref)||f}catch(e){}}const meta=D.getMeta?D.getMeta():null;
  if(!f){renderNotFound();return}
  const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}),unit=f.currency&&f.currency!=='USD'?`${f.currency} `:'$';
  function notify(text){let t=$('#financeToast');if(!t){t=document.createElement('div');t.id='financeToast';t.className='finance-toast';t.setAttribute('role','status');t.setAttribute('aria-live','polite');document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.classList.remove('show'),2200)}
  function recordHistory(){let h=[];try{h=JSON.parse(localStorage.getItem('trfinance.history')||'[]')}catch(e){}h=[{type:'fund',symbol:f.symbol,name:f.name,exchange:f.exchange||f.market,assetType:f.assetType||'ETF',ts:Date.now()},...h.filter(x=>!(x.type==='fund'&&x.symbol===f.symbol&&(x.exchange||'')===(f.exchange||f.market||'')))].slice(0,20);try{localStorage.setItem('trfinance.history',JSON.stringify(h))}catch(e){}}recordHistory();
  document.title=`${f.name} (${f.symbol})｜唐人财经`;$('#fundSymbol').textContent=f.symbol;$('#fundName').textContent=f.name;$('#fundPrice').textContent=`${unit}${money(f.price)}`;$('#fundChange').textContent=`${f.change>=0?'▲':'▼'} ${Math.abs(f.change).toFixed(2)}%`;$('#fundChange').className=`move ${f.change>=0?'up':'down'}`;$('#fundCat').textContent=f.category;$('#fundExpense').textContent=f.expense;$('#fundAum').textContent=f.aum;$('#fundRisk').textContent=f.risk;
  if(meta&&$('#fundChange'))$('#fundChange').insertAdjacentHTML('afterend',`<div class="detail-data-note">${meta.source} · ${meta.realTime?'正式接口':'测试数据'}</div>`);
  $('#holdings').innerHTML=(f.holdings||[]).length?f.holdings.map((h,i)=>`<div class="event"><div><b>${h}</b><small>示例核心持仓 ${i+1}</small></div><div class="right"><b>${[8.4,7.8,6.6][i]||5.1}%</b><small>示例权重</small></div></div>`).join(''):'<div class="empty">正式基金持仓接口尚未启用；基础行情与证券身份已可测试。</div>';
  let activeRange='1M',chartPoints=[],chartPairs=[];
  function priceAt(raw,index){const max=Math.max(...raw),min=Math.min(...raw),norm=(raw[index]-min)/(max-min||1),spread={ '1M':.06,'3M':.09,'YTD':.12,'1Y':.16,'3Y':.24,'5Y':.34 }[activeRange]||.08;return f.price*(1-spread+norm*spread*2)}
  function chart(factor=1){const base=Array.isArray(f.series)&&f.series.length>4?f.series.map(point=>Number(point.close)).filter(Number.isFinite):D.spark(f.symbol);const points=Array.isArray(f.series)&&f.series.length>4?base:Array.from({length:48},(_,i)=>base[i%base.length]+Math.sin((i+factor)/4)*factor*1.8+(i*factor%7)/4);const max=Math.max(...points),min=Math.min(...points),w=800,h=400,floor=h-24,color=f.change>=0?'#00c805':'#ff4d2e',gid=`fundFill-${f.symbol.replace(/[^A-Z0-9]/g,'')}`;const pairs=points.map((v,i)=>[(i/(points.length-1))*w,floor-((v-min)/(max-min||1))*(h-76)]);const pts=pairs.map(p=>`${p[0]},${p[1]}`).join(' '),end=pairs[pairs.length-1];chartPoints=points;chartPairs=pairs;return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="${f.symbol} ETF 走势图"><defs><linearGradient id="${gid}" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="${color}" stop-opacity=".16"/><stop offset="65%" stop-color="${color}" stop-opacity=".04"/><stop offset="100%" stop-color="${color}" stop-opacity="0"/></linearGradient></defs><line x1="0" y1="112" x2="800" y2="112" stroke="#e9eeeb" stroke-width="1"/><line x1="0" y1="220" x2="800" y2="220" stroke="#edf1ef" stroke-width="1"/><line x1="0" y1="320" x2="800" y2="320" stroke="#edf1ef" stroke-width="1"/><polygon points="0,${floor} ${pts} ${w},${floor}" fill="url(#${gid})"/><polyline points="${pts}" fill="none" stroke="${color}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${end[0]}" cy="${end[1]}" r="12" fill="${color}" opacity=".12"/><circle cx="${end[0]}" cy="${end[1]}" r="6" fill="${color}"/><g data-scrub-overlay visibility="hidden" pointer-events="none"><line data-scrub-line x1="0" x2="0" y1="20" y2="376" stroke="#6f777d" stroke-width="1" stroke-dasharray="3 4" opacity=".7"/><circle data-scrub-dot cx="0" cy="0" r="7" fill="${color}" stroke="#fff" stroke-width="3"/></g></svg>`}
  const chartEl=$('#fundChart');
  function ensureTip(){let tip=$('.chart-scrub-tip',chartEl);if(!tip){tip=document.createElement('div');tip.className='chart-scrub-tip';tip.setAttribute('aria-hidden','true');tip.style.cssText='position:absolute;z-index:5;top:12px;min-width:128px;padding:8px 10px;border-radius:12px;background:rgba(17,22,19,.94);color:#fff;font-size:14px;font-weight:750;line-height:1.2;box-shadow:0 8px 24px rgba(0,0,0,.16);pointer-events:none;opacity:0;transform:translateY(3px);transition:opacity .12s,transform .12s;white-space:nowrap';chartEl.appendChild(tip)}return tip}
  function bindScrub(){const svg=$('svg',chartEl),overlay=$('[data-scrub-overlay]',chartEl),lineEl=$('[data-scrub-line]',chartEl),dot=$('[data-scrub-dot]',chartEl),tip=ensureTip();if(!svg||!overlay||!chartPairs.length)return;chartEl.style.touchAction='pan-y';chartEl.tabIndex=0;chartEl.setAttribute('aria-label',`${f.symbol} ${activeRange} ETF 演示走势图。鼠标或手指横向移动可查看演示读数，键盘左右键也可浏览。`);let selected=chartPairs.length-1,raf=0,touching=false;const hide=()=>{overlay.setAttribute('visibility','hidden');tip.style.opacity='0';tip.style.transform='translateY(3px)'};const showIndex=i=>{selected=Math.max(0,Math.min(chartPairs.length-1,i));const p=chartPairs[selected],x=p[0],y=p[1],rect=chartEl.getBoundingClientRect(),px=(x/800)*rect.width;lineEl.setAttribute('x1',x);lineEl.setAttribute('x2',x);dot.setAttribute('cx',x);dot.setAttribute('cy',y);tip.innerHTML=`$${money(priceAt(chartPoints,selected))}<small style="display:block;margin-top:3px;color:#bfc6c1;font-size:10px;font-weight:650">演示读数 · ${activeRange}</small>`;tip.style.left=`${Math.max(6,Math.min(rect.width-142,px>rect.width*.78?px-136:px+8))}px`;overlay.setAttribute('visibility','visible');tip.style.opacity='1';tip.style.transform='translateY(0)'};const fromPointer=e=>{const r=chartEl.getBoundingClientRect(),x=Math.max(0,Math.min(r.width,e.clientX-r.left)),i=Math.round((x/r.width)*(chartPairs.length-1));cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>showIndex(i))};chartEl.onpointerenter=e=>{if(e.pointerType!=='touch')fromPointer(e)};chartEl.onpointermove=e=>{if(e.pointerType!=='touch'||touching)fromPointer(e)};chartEl.onpointerleave=e=>{if(e.pointerType!=='touch')hide()};chartEl.onpointerdown=e=>{if(e.pointerType==='touch'){touching=true;fromPointer(e)}};chartEl.onpointerup=chartEl.onpointercancel=()=>{touching=false;hide()};chartEl.onfocus=()=>showIndex(selected);chartEl.onblur=hide;chartEl.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();showIndex(selected+(e.key==='ArrowRight'?1:-1))}else if(e.key==='Home'){e.preventDefault();showIndex(0)}else if(e.key==='End'){e.preventDefault();showIndex(chartPairs.length-1)}else if(e.key==='Escape')hide()}}
  function renderChart(factor){chartEl.innerHTML=chart(factor);bindScrub()}
  renderChart(1);
  $$('.range button[data-range]').forEach((b,i)=>b.addEventListener('click',()=>{$$('.range button[data-range]').forEach(x=>{const on=x===b;x.classList.toggle('on',on);x.setAttribute('aria-pressed',String(on))});activeRange=b.dataset.range;renderChart(i+1);notify(`已切换到 ${activeRange} 走势图`)}));
  const btn=$('#fundWatchBtn');function sync(){const on=D.isSecurityWatched?D.isSecurityWatched(f):D.getFundWatchlist().includes(f.symbol);btn.textContent=on?'✓ 已关注':'+ 加入基金自选';btn.setAttribute('aria-pressed',String(on))}sync();btn.addEventListener('click',()=>{const on=D.toggleSecurityWatch?D.toggleSecurityWatch(f):D.toggleFundWatch(f.symbol);sync();notify(`${f.symbol} 已${on?'加入':'移出'}基金自选`)});
  const back=$('#fundBackBtn');if(back)back.addEventListener('click',()=>{if(history.length>1)history.back();else location.href='./#funds'});
  requestAnimationFrame(()=>document.documentElement.classList.add('detail-ready'));
  }
  boot().catch(()=>renderNotFound());
})();
