(function(){
  const D=window.FinanceData;if(!D)return;
  const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const symbol=(new URLSearchParams(location.search).get('symbol')||'AAPL').toUpperCase();
  const q=D.getQuote(symbol);const meta=D.getMeta?D.getMeta():null;
  function renderNotFound(){document.title=`${symbol} 未找到｜唐人财经`;const top=$('#topSymbol');if(top)top.textContent=symbol;const price=$('#topPrice');if(price)price.textContent='—';const main=$('.stock-content');if(main)main.innerHTML=`<section class="not-found" role="status"><div class="code">${symbol}</div><h1>没有找到这只股票</h1><p>当前 V1 演示数据中没有 ${symbol}。我们不会用其他股票的数据替代它，以避免产生错误行情或公司信息。</p><a href="./#watch">返回自选与搜索</a></section>`;const fixed=$('.fixed');if(fixed)fixed.hidden=true;const share=$('#shareBtn');if(share)share.hidden=true;document.documentElement.classList.add('detail-ready')}
  if(!q){renderNotFound();return}
  const money=v=>typeof v==='number'?v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):v;const cls=v=>v>=0?'up':'down';
  function notify(text){let t=$('#financeToast');if(!t){t=document.createElement('div');t.id='financeToast';t.className='finance-toast';t.setAttribute('role','status');t.setAttribute('aria-live','polite');document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.classList.remove('show'),2200)}
  document.title=`${q.name} (${q.symbol})｜唐人财经`;
  function recordHistory(){let h=[];try{h=JSON.parse(localStorage.getItem('trfinance.history')||'[]')}catch(e){}h=[{type:'stock',symbol:q.symbol,name:q.name,ts:Date.now()},...h.filter(x=>!(x.type==='stock'&&x.symbol===q.symbol))].slice(0,20);try{localStorage.setItem('trfinance.history',JSON.stringify(h))}catch(e){}}
  recordHistory();
  $('#symbol').textContent=q.symbol;$('#name').textContent=q.name;$('#topSymbol').textContent=q.symbol;$('#topPrice').textContent=`$${money(q.price)}`;$('#price').textContent=`$${money(q.price)}`;$('#market').textContent=q.market;
  $('#move').className=`move ${cls(q.change)}`;$('#move').textContent=`${q.change>=0?'▲':'▼'} $${Math.abs(q.price-q.prev).toFixed(2)} (${Math.abs(q.change).toFixed(2)}%)  Today`;
  $('#after').className=`after ${cls(q.after)}`;$('#after').textContent=`${q.after>=0?'▲':'▼'} ${Math.abs(q.after).toFixed(2)}%  After-hours`;
  if(meta&&$('#after'))$('#after').insertAdjacentHTML('afterend',`<div class="detail-data-note">${meta.source} · 非实时</div>`);
  const note=$('.detail-data-note')||$('#after');if(note)note.insertAdjacentHTML('afterend',`<div class="stock-quickfacts" aria-label="当日关键行情"><span><small>高</small><b>$${money(q.high)}</b></span><span><small>低</small><b>$${money(q.low)}</b></span><span><small>成交量</small><b>${q.volume}</b></span></div>`);
  const metrics=[['今开',q.open],['最高',q.high],['最低',q.low],['昨收',q.prev],['市值',q.marketCap],['市盈率',q.pe],['成交量',q.volume],['52周区间',q.range52]];$('#metrics').innerHTML=metrics.map(x=>`<div class="metric"><small>${x[0]}</small><b>${typeof x[1]==='number'?money(x[1]):x[1]}</b></div>`).join('');
  $('#stockNews').innerHTML=q.news.map(n=>`<article class="news"><div><b>${n.title}</b><small>${n.source} · ${n.time}</small></div><div class="thumb" aria-hidden="true">${n.tag}</div></article>`).join('');
  $('#description').textContent=q.description;$('#sector').textContent=q.sector;
  let activeRange='1D',chartPoints=[],chartPairs=[];
  function priceAt(raw,index){const max=Math.max(...raw),min=Math.min(...raw),norm=(raw[index]-min)/(max-min||1);if(activeRange==='1D')return q.low+norm*(q.high-q.low);const spread={ '1W':.045,'1M':.07,'3M':.10,'YTD':.13,'1Y':.18,'5Y':.34 }[activeRange]||.08;return q.price*(1-spread+norm*spread*2)}
  function chart(points){
    const max=Math.max(...points),min=Math.min(...points),w=800,h=400,floor=h-24,color=q.change>=0?'#00c805':'#ff4d2e',soft=color;
    const pairs=points.map((v,i)=>[(i/(points.length-1))*w,floor-((v-min)/(max-min||1))*(h-76)]);const pts=pairs.map(p=>`${p[0]},${p[1]}`).join(' ');const end=pairs[pairs.length-1];const gid=`chartFill-${q.symbol.replace(/[^A-Z0-9]/g,'')}`;
    chartPoints=points;chartPairs=pairs;
    return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="${q.symbol} 价格走势图，当前${q.change>=0?'上涨':'下跌'} ${Math.abs(q.change).toFixed(2)}%"><defs><linearGradient id="${gid}" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="${soft}" stop-opacity=".18"/><stop offset="62%" stop-color="${soft}" stop-opacity=".045"/><stop offset="100%" stop-color="${soft}" stop-opacity="0"/></linearGradient></defs><line x1="0" y1="${h*.28}" x2="${w}" y2="${h*.28}" stroke="#e9eeeb" stroke-width="1"/><line x1="0" y1="${h*.55}" x2="${w}" y2="${h*.55}" stroke="#edf1ef" stroke-width="1"/><line x1="0" y1="${h*.8}" x2="${w}" y2="${h*.8}" stroke="#edf1ef" stroke-width="1"/><polygon points="0,${floor} ${pts} ${w},${floor}" fill="url(#${gid})"/><polyline points="${pts}" fill="none" stroke="${color}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${end[0]}" cy="${end[1]}" r="13" fill="${color}" opacity=".12"/><circle cx="${end[0]}" cy="${end[1]}" r="6" fill="${color}"/><g data-scrub-overlay visibility="hidden" pointer-events="none"><line data-scrub-line x1="0" x2="0" y1="22" y2="376" stroke="#6f777d" stroke-width="1" stroke-dasharray="3 4" opacity=".7"/><circle data-scrub-dot cx="0" cy="0" r="7" fill="${color}" stroke="#fff" stroke-width="3"/></g></svg>`
  }
  const chartEl=$('#chart');
  function ensureTip(){let tip=$('.chart-scrub-tip',chartEl);if(!tip){tip=document.createElement('div');tip.className='chart-scrub-tip';tip.setAttribute('aria-hidden','true');tip.style.cssText='position:absolute;z-index:5;top:12px;min-width:128px;padding:8px 10px;border-radius:12px;background:rgba(17,22,19,.94);color:#fff;font-size:14px;font-weight:750;line-height:1.2;box-shadow:0 8px 24px rgba(0,0,0,.16);pointer-events:none;opacity:0;transform:translateY(3px);transition:opacity .12s,transform .12s;white-space:nowrap';chartEl.appendChild(tip)}return tip}
  function bindScrub(){const svg=$('svg',chartEl),overlay=$('[data-scrub-overlay]',chartEl),lineEl=$('[data-scrub-line]',chartEl),dot=$('[data-scrub-dot]',chartEl),tip=ensureTip();if(!svg||!overlay||!chartPairs.length)return;chartEl.style.touchAction='pan-y';chartEl.tabIndex=0;chartEl.setAttribute('aria-label',`${q.symbol} ${activeRange} 演示走势图。鼠标或手指横向移动可查看演示读数，键盘左右键也可浏览。`);let selected=chartPairs.length-1,raf=0,touching=false;const hide=()=>{overlay.setAttribute('visibility','hidden');tip.style.opacity='0';tip.style.transform='translateY(3px)'};const showIndex=i=>{selected=Math.max(0,Math.min(chartPairs.length-1,i));const p=chartPairs[selected],x=p[0],y=p[1],rect=chartEl.getBoundingClientRect(),px=(x/800)*rect.width;lineEl.setAttribute('x1',x);lineEl.setAttribute('x2',x);dot.setAttribute('cx',x);dot.setAttribute('cy',y);tip.innerHTML=`$${money(priceAt(chartPoints,selected))}<small style="display:block;margin-top:3px;color:#bfc6c1;font-size:10px;font-weight:650">演示读数 · ${activeRange}</small>`;tip.style.left=`${Math.max(6,Math.min(rect.width-142,px>rect.width*.78?px-136:px+8))}px`;overlay.setAttribute('visibility','visible');tip.style.opacity='1';tip.style.transform='translateY(0)'};const fromPointer=e=>{const r=chartEl.getBoundingClientRect(),x=Math.max(0,Math.min(r.width,e.clientX-r.left)),i=Math.round((x/r.width)*(chartPairs.length-1));cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>showIndex(i))};chartEl.onpointerenter=e=>{if(e.pointerType!=='touch')fromPointer(e)};chartEl.onpointermove=e=>{if(e.pointerType!=='touch'||touching)fromPointer(e)};chartEl.onpointerleave=e=>{if(e.pointerType!=='touch')hide()};chartEl.onpointerdown=e=>{if(e.pointerType==='touch'){touching=true;fromPointer(e)}};chartEl.onpointerup=chartEl.onpointercancel=()=>{touching=false;hide()};chartEl.onfocus=()=>showIndex(selected);chartEl.onblur=hide;chartEl.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();showIndex(selected+(e.key==='ArrowRight'?1:-1))}else if(e.key==='Home'){e.preventDefault();showIndex(0)}else if(e.key==='End'){e.preventDefault();showIndex(chartPairs.length-1)}else if(e.key==='Escape')hide()}}
  function renderChart(points){chartEl.innerHTML=chart(points);bindScrub()}
  renderChart([...q.spark,...q.spark.map((v,i)=>v+(i%4)-2),...q.spark.slice(4)]);
  $$('.range button[data-range]').forEach((b,i)=>b.addEventListener('click',()=>{$$('.range button[data-range]').forEach(x=>{const on=x===b;x.classList.toggle('on',on);x.setAttribute('aria-pressed',String(on))});activeRange=b.dataset.range;const factor=i+1;renderChart(Array.from({length:46},(_,n)=>24+Math.sin((n+factor*3)/3)*11+Math.sin(n/7)*8+(n*factor%13)/3));notify(`已切换到 ${activeRange} 走势图`)}));
  const watchBtn=$('#watchBtn');function syncWatch(){const on=D.getWatchlist().includes(q.symbol);watchBtn.textContent=on?'✓ 已自选':'+ 加入自选';watchBtn.setAttribute('aria-pressed',String(on))}syncWatch();watchBtn.addEventListener('click',()=>{const on=D.toggleWatch(q.symbol);syncWatch();notify(`${q.symbol} 已${on?'加入':'移出'}自选`)});
  const alertBtn=$('#alertBtn');function syncAlert(){const on=D.isAlertOn?D.isAlertOn(q.symbol):false;alertBtn.textContent=on?'✓ 已设置提醒':'设置提醒';alertBtn.setAttribute('aria-pressed',String(on))}syncAlert();alertBtn.addEventListener('click',()=>{const on=D.toggleAlert?D.toggleAlert(q.symbol):false;syncAlert();notify(`${q.symbol} 价格提醒已${on?'开启':'关闭'}`)});
  $('#shareBtn').addEventListener('click',async()=>{try{if(navigator.share){await navigator.share({title:document.title,url:location.href});notify('已打开分享菜单')}else if(navigator.clipboard){await navigator.clipboard.writeText(location.href);notify('链接已复制')}else{notify('当前浏览器不支持自动复制')}}catch(e){if(e&&e.name!=='AbortError')notify('分享暂时不可用')}});
  const advanced=$('#advancedChartBtn');if(advanced)advanced.addEventListener('click',()=>notify('高级图表将在正式行情数据接入后启用'));
  requestAnimationFrame(()=>document.documentElement.classList.add('detail-ready'));
})();