(()=>{
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const menu=$('.ice-menu');if(!menu)return;
  const pageUrl=()=>location.href.split('#')[0];
  const toast=t=>{const el=$('#share-toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2600)};
  document.body.insertAdjacentHTML('beforeend',`<button id="share-backdrop" class="share-backdrop" aria-label="关闭分享菜单"></button><section id="share-sheet" class="share-sheet" role="dialog" aria-modal="true" aria-labelledby="share-title"><div class="share-sheet-head"><h2 id="share-title">分享 ICE 执法追踪</h2><button id="share-close" class="share-sheet-close" aria-label="关闭">×</button></div><div class="share-actions"><button id="share-page" class="share-action primary">转发当前页面<small>发送给朋友或分享到其他应用</small></button><button id="share-poster" class="share-action">生成长图并分享<small>自动生成热力图、数据和二维码</small></button><button id="share-copy" class="share-action">复制链接<small>复制当前页面地址</small></button></div></section><div id="poster-modal" class="poster-modal" role="dialog" aria-modal="true"><div class="poster-card"><img id="poster-image" alt="ICE执法追踪分享长图"><div class="poster-buttons"><a id="poster-save" download="ICE执法追踪.jpg">保存长图</a><button id="poster-system-share" class="poster-share">系统分享</button><button id="poster-close">关闭</button></div><p class="poster-tip">微信内请长按图片保存，再发送给好友或朋友圈</p></div></div><div id="share-toast" class="share-toast" role="status" aria-live="polite"></div>`);
  const open=()=>{document.documentElement.classList.add('share-sheet-open');document.body.classList.add('share-sheet-open');menu.setAttribute('aria-expanded','true')};
  const close=()=>{document.documentElement.classList.remove('share-sheet-open');document.body.classList.remove('share-sheet-open');menu.setAttribute('aria-expanded','false')};
  menu.addEventListener('click',open);$('#share-close').onclick=close;$('#share-backdrop').onclick=close;addEventListener('keydown',e=>{if(e.key==='Escape'){close();$('#poster-modal').classList.remove('show')}});
  const copy=async()=>{try{await navigator.clipboard.writeText(pageUrl())}catch{const x=document.createElement('textarea');x.value=pageUrl();x.style.cssText='position:fixed;opacity:0';document.body.append(x);x.select();document.execCommand('copy');x.remove()}toast('链接已复制，可粘贴发送给朋友')};
  $('#share-copy').onclick=copy;$('#share-page').onclick=async()=>{try{if(navigator.share){await navigator.share({title:'ICE执法追踪 - 唐人日报',text:'唐人日报 ICE执法追踪',url:pageUrl()});close()}else await copy()}catch(e){if(e.name!=='AbortError')await copy()}};
  const font='-apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif';
  const rr=(g,x,y,w,h,r,fill,stroke)=>{g.beginPath();g.roundRect?g.roundRect(x,y,w,h,r):g.rect(x,y,w,h);if(fill){g.fillStyle=fill;g.fill()}if(stroke){g.strokeStyle=stroke;g.stroke()}};
  const wrap=(g,text,x,y,max,line=40,maxLines=2)=>{let cur='',lines=[];for(const ch of text){if(g.measureText(cur+ch).width>max&&cur){lines.push(cur);cur=ch}else cur+=ch}if(cur)lines.push(cur);lines.slice(0,maxLines).forEach((l,i)=>g.fillText(l,x,y+i*line));return Math.min(lines.length,maxLines)*line};
  const loadImage=src=>new Promise((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=reject;img.src=src});
  async function makeQrCanvas(){const qr=document.createElement('canvas');if(window.QRCode?.toCanvas){await window.QRCode.toCanvas(qr,pageUrl(),{width:190,margin:1,errorCorrectionLevel:'M'});return qr}const r=await fetch('https://api.qrserver.com/v1/create-qr-code/?size=190x190&margin=6&data='+encodeURIComponent(pageUrl()),{cache:'no-store'});if(!r.ok)throw new Error('二维码服务不可用');const u=URL.createObjectURL(await r.blob());try{const img=await loadImage(u);qr.width=190;qr.height=190;qr.getContext('2d').drawImage(img,0,0,190,190);return qr}finally{URL.revokeObjectURL(u)}}
  async function drawMapSnapshot(g,x,y,w,h){
    g.save();rr(g,x,y,w,h,24,'#dff1fb','#cbd5e1');g.beginPath();g.roundRect?g.roundRect(x,y,w,h,24):g.rect(x,y,w,h);g.clip();
    const map=$('#ice-map');let tilesDrawn=0;
    if(map){const mr=map.getBoundingClientRect();for(const tile of $$('.leaflet-tile-loaded',map).slice(0,20)){try{const tr=tile.getBoundingClientRect();const img=await loadImage(tile.currentSrc||tile.src);const dx=x+(tr.left-mr.left)/mr.width*w,dy=y+(tr.top-mr.top)/mr.height*h,dw=tr.width/mr.width*w,dh=tr.height/mr.height*h;g.drawImage(img,dx,dy,dw,dh);tilesDrawn++}catch{}}
      const markers=$$('.leaflet-interactive',map).filter(el=>{const r=el.getBoundingClientRect();return r.width>5&&r.height>5});markers.forEach(el=>{const r=el.getBoundingClientRect(),cx=x+(r.left+r.width/2-mr.left)/mr.width*w,cy=y+(r.top+r.height/2-mr.top)/mr.height*h,fill=getComputedStyle(el).fill||el.getAttribute('fill')||'#d92d20',rad=Math.max(22,Math.min(48,r.width/mr.width*w*1.25));const halo=g.createRadialGradient(cx,cy,2,cx,cy,rad*1.9);halo.addColorStop(0,fill);halo.addColorStop(.3,fill);halo.addColorStop(1,'rgba(255,255,255,0)');g.globalAlpha=.28;g.fillStyle=halo;g.beginPath();g.arc(cx,cy,rad*1.9,0,Math.PI*2);g.fill();g.globalAlpha=1;g.fillStyle=fill;g.strokeStyle='#243049';g.lineWidth=4;g.beginPath();g.arc(cx,cy,Math.max(10,rad*.42),0,Math.PI*2);g.fill();g.stroke()})}
    if(!tilesDrawn){const grad=g.createLinearGradient(x,y,x+w,y+h);grad.addColorStop(0,'#d9eef8');grad.addColorStop(1,'#eff7fb');g.fillStyle=grad;g.fillRect(x,y,w,h);g.fillStyle='rgba(52,64,84,.45)';g.font=`700 26px ${font}`;g.fillText('美国执法动态分布',x+32,y+58)}
    rr(g,x+22,y+20,w-44,66,14,'rgba(255,255,255,.94)','#d0d5dd');g.fillStyle='#101828';g.font=`700 24px ${font}`;g.fillText(`实时热力图 · ${$('#today-places')?.textContent||'--'} · ${$('#today-count')?.textContent||'--'}`,x+46,y+62);
    const ly=y+h-62;rr(g,x+22,ly,w-44,42,12,'rgba(255,255,255,.94)','#d0d5dd');const legends=[['#d92d20','抓捕/拘留'],['#175cd3','遣返'],['#7f56d9','其他行动']];let lx=x+62;g.font=`700 20px ${font}`;legends.forEach(([c,t])=>{g.fillStyle=c;g.beginPath();g.arc(lx,ly+21,9,0,Math.PI*2);g.fill();g.fillStyle='#475467';g.fillText(t,lx+18,ly+28);lx+=190});g.restore();
  }
  async function poster(){
    toast('正在生成长图…');await new Promise(r=>setTimeout(r,80));
    const news=$$('.ice-news-copy h3').slice(0,6).map(x=>x.textContent.trim()).filter(Boolean),W=1080,pad=64,row=88,H=1770+Math.max(1,news.length)*row;
    const c=document.createElement('canvas');c.width=W;c.height=H;const g=c.getContext('2d',{alpha:false});g.fillStyle='#f3f6fb';g.fillRect(0,0,W,H);
    rr(g,34,34,W-68,H-68,30,'#ffffff','#e3e8ef');
    g.fillStyle='#e60012';g.font=`900 56px ${font}`;g.fillText('唐',pad+10,112);g.fillStyle='#101828';g.fillText('人日报',pad+74,112);
    g.fillStyle='#0f172a';g.font=`900 62px ${font}`;g.fillText('ICE执法追踪',pad+10,210);g.fillStyle='#667085';g.font=`27px ${font}`;g.fillText(new Date().toLocaleString('zh-CN',{timeZone:'America/New_York'}),pad+10,258);
    rr(g,pad,300,W-pad*2,188,22,'#f8fafc','#e4e7ec');g.strokeStyle='#e4e7ec';g.beginPath();g.moveTo(W/2,322);g.lineTo(W/2,466);g.stroke();
    g.fillStyle='#475467';g.font=`700 26px ${font}`;g.fillText('近24小时涉及人数',pad+34,352);g.fillText('近24小时涉及地点',W/2+34,352);
    g.fillStyle='#101828';g.font=`900 54px ${font}`;g.fillText($('#today-count')?.textContent||'--',pad+34,430);g.fillText($('#today-places')?.textContent||'--',W/2+34,430);
    g.fillStyle='#101828';g.font=`900 38px ${font}`;g.fillText('ICE动态热力图',pad,558);g.fillStyle='#667085';g.font=`24px ${font}`;g.fillText('根据当前页面公开数据生成',pad,598);
    await drawMapSnapshot(g,pad,630,W-pad*2,480);
    g.fillStyle='#101828';g.font=`900 38px ${font}`;g.fillText('最新动态',pad,1192);g.fillStyle='#667085';g.font=`24px ${font}`;g.fillText('最近发布的ICE相关公开信息',pad,1232);
    let y=1302;g.font=`28px ${font}`;if(news.length){news.forEach((t,i)=>{rr(g,pad,y-42,W-pad*2,72,14,i%2?'#ffffff':'#f8fafc','#edf0f4');g.fillStyle='#1677ff';g.font=`800 25px ${font}`;g.fillText(String(i+1).padStart(2,'0'),pad+24,y);g.fillStyle='#344054';g.font=`27px ${font}`;wrap(g,t,pad+82,y,W-pad*2-110,36,1);y+=row})}else{g.fillStyle='#667085';g.fillText('暂无最新动态',pad,y);y+=row}
    const footerTop=H-300;g.strokeStyle='#e4e7ec';g.beginPath();g.moveTo(pad,footerTop-28);g.lineTo(W-pad,footerTop-28);g.stroke();g.fillStyle='#101828';g.font=`900 30px ${font}`;g.fillText('扫码查看实时动态',pad,footerTop+35);g.fillStyle='#667085';g.font=`23px ${font}`;g.fillText('数据持续更新，以页面实时内容为准',pad,footerTop+78);g.fillStyle='#175cd3';g.font=`800 25px ${font}`;g.fillText('trrb.net/ice',pad,footerTop+132);
    const qr=await makeQrCanvas();rr(g,W-pad-214,footerTop-8,214,214,18,'#fff','#d0d5dd');g.drawImage(qr,W-pad-202,footerTop+4,190,190);
    return c;
  }
  let lastBlob=null,lastUrl='';
  $('#share-poster').onclick=async()=>{const btn=$('#share-poster');btn.disabled=true;try{const c=await poster();lastBlob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('无法生成图片')),'image/jpeg',0.96));if(lastUrl)URL.revokeObjectURL(lastUrl);lastUrl=URL.createObjectURL(lastBlob);$('#poster-image').src=lastUrl;$('#poster-save').href=lastUrl;$('#poster-save').download='ICE执法追踪.jpg';$('#poster-modal').classList.add('show');close();toast('长图已生成')}catch(e){console.error('ICE poster error:',e);toast('长图生成失败，请刷新后重试')}finally{btn.disabled=false}};
  $('#poster-close').onclick=()=>$('#poster-modal').classList.remove('show');
  $('#poster-system-share').onclick=async()=>{if(!lastBlob){toast('请先生成长图');return}const file=new File([lastBlob],'ICE执法追踪.jpg',{type:'image/jpeg',lastModified:Date.now()});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'ICE执法追踪',text:'唐人日报 ICE执法追踪热力图'})}else toast('请长按图片保存后发送给微信好友')}catch(e){if(e.name!=='AbortError')toast('请长按图片保存后发送给微信好友')}};
})();