(()=>{
  const U='https://fwiznbpsqkfgkvyznebz.supabase.co',K='sb_publishable_hSmKJghvQoJKg0m5loDQ2g_f1gu8qak',c=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}}),$=id=>document.getElementById(id);let user=null,rows=[],editing=null;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]));const image=p=>`${U}/storage/v1/object/public/secondhand-images/${String(p).split('/').map(encodeURIComponent).join('/')}`;
  const statuses={draft:'草稿',pending:'审核中',published:'已上架',paused:'已下架',sold:'已售出',deleted:'已删除'};
  function split(v){const raw=String(v||'').trim(),lines=raw.split(/\r?\n/),first=lines.findIndex(x=>x.trim());return{title:(lines[first]||'').trim().slice(0,60),description:lines.slice(first+1).join('\n').trim()}}
  async function signed(u){user=u||null;$('manage-login').hidden=!!user;if(user)await load()}
  async function login(){const b=$('manage-login-button');b.disabled=true;$('manage-auth-status').textContent='正在登录…';try{const r=await TRUnifiedAccount.loginOrRegister(c,$('manage-identifier').value,$('manage-password').value);await signed(r.user)}catch(e){$('manage-auth-status').textContent=e.message}finally{b.disabled=false}}
  async function load(){const{data,error}=await c.from('secondhand_listings').select('*,secondhand_listing_images(id,storage_path,sort_order)').eq('seller_user_id',user.id).order('updated_at',{ascending:false});if(error){$('manage-list').innerHTML=`<p>${esc(error.message)}</p>`;return}rows=data||[];render()}
  function actions(row){const a=[`<button data-edit="${row.id}">修改</button>`];if(row.status==='published')a.push(`<button data-status="paused" data-id="${row.id}">下架</button>`);if(row.status==='published'||row.status==='paused')a.push(`<button data-status="sold" data-id="${row.id}">标记已售</button>`);if(['paused','sold','deleted'].includes(row.status))a.push(`<button data-status="pending" data-id="${row.id}">${row.status==='deleted'?'恢复':'重新上架'}</button>`);if(row.status!=='deleted')a.push(`<button class="danger" data-status="deleted" data-id="${row.id}">删除</button>`);return a.join('')}
  function render(){$('manage-empty').hidden=rows.length>0;$('manage-list').innerHTML=rows.map(row=>{const imgs=[...(row.secondhand_listing_images||[])].sort((a,b)=>a.sort_order-b.sort_order);return`<article class="manage-card"><div class="manage-gallery">${imgs.map(x=>`<img src="${image(x.storage_path)}" alt="${esc(row.title)}">`).join('')}</div><div class="manage-info"><span class="status-pill">${statuses[row.status]||row.status}</span><h2>${esc(row.title)}</h2><div class="manage-meta"><span>${row.category_slug==='free'?'免费':Number(row.price)===0?'面议':`$${Number(row.price).toLocaleString()}`}</span><span>${esc(row.location_label)}</span><span>${imgs.length}张图</span></div><div class="manage-actions">${actions(row)}</div></div></article>`}).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit));document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>change(b.dataset.id,b.dataset.status))}
  async function change(id,status){const labels={paused:'确定下架这件商品吗？',sold:'确定标记为已售出吗？',deleted:'确定删除吗？30天内仍可恢复。',pending:'确定重新提交审核吗？'};if(!confirm(labels[status]||'确定继续吗？'))return;const{error}=await c.from('secondhand_listings').update({status,status_reason:status==='pending'?'owner_resubmitted':`owner_${status}`}).eq('id',id);if(error)return alert(error.message);await load()}
  function openEdit(id){editing=rows.find(x=>x.id===id);if(!editing)return;$('edit-text').value=[editing.title,editing.description].filter(Boolean).join('\n\n');$('edit-category').value=editing.category_slug;$('edit-condition').value=editing.item_condition;$('edit-price').value=editing.price;$('edit-location').value=editing.location_label;$('edit-contact').value=editing.contact_value;$('edit-panel').hidden=false}
  $('edit-close').onclick=()=>{$('edit-panel').hidden=true};$('edit-form').onsubmit=async e=>{e.preventDefault();const t=split($('edit-text').value);if(!t.title)return $('edit-status').textContent='请在第一行填写标题';$('edit-status').textContent='正在保存…';const loc=$('edit-location').value.trim(),match=loc.match(/(?:,|\s)\s*([A-Za-z]{2})$/);const{error}=await c.from('secondhand_listings').update({title:t.title,description:t.description,category_slug:$('edit-category').value,item_condition:$('edit-condition').value,price:Number($('edit-price').value)||0,location_label:loc,city:loc.replace(/(?:,|\s)\s*[A-Za-z]{2}$/,'').trim()||loc,state_code:match?match[1].toUpperCase():editing.state_code,contact_value:$('edit-contact').value.trim(),status:'pending',status_reason:'owner_edited'}).eq('id',editing.id);if(error)return $('edit-status').textContent=error.message;$('edit-panel').hidden=true;await load()};
  $('manage-login-button').onclick=login;$('manage-password').onkeydown=e=>{if(e.key==='Enter')login()};document.addEventListener('DOMContentLoaded',async()=>{const{data}=await c.auth.getSession();await signed(data.session?.user||null)});
})();
