(function(){
  const D=window.FinanceData;if(!D)return;
  const snap=D.getMarketSnapshot();
  const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const money=v=>typeof v==='number'?v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):v;
  const pct=v=>`${v>=0?'▲':'▼'} ${Math.abs(v).toFixed(2)}%`;const cls=v=>v>=0?'up':'down';
  const line=(points,positive=true)=>{const max=Math.max(...points),min=Math.min(...points),w=86,h=34;const p=points.map((v,i)=>`${(i/(points.length-1))*w},${h-3-((v-min)/(max-min||1))*(h-6)}`).join(' ');return `<svg class="spark" viewBox="0 0 ${w} ${h}" aria-hidden="true"><polyline points="${p}" fill="none" stroke="${positive?'#00c805':'#ff4d2e'}" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg>`};
  function announce(text){let el=$('#financeAnnouncer');if(!el){el=document.createElement('div');el.id='financeAnnouncer';el.className='sr-only';el.setAttribute('aria-live','polite');el.setAttribute('aria-atomic','true');document.body.appendChild(el)}el.textContent='';requestAnimationFrame(()=>{el.textContent=text})}
  function renderIndices(){const el=$('#indices');if(el)el.innerHTML=snap.indices.map(i=>`<div class="indexcard"><b>${i.name}</b><strong class="${cls(i.change)}">${money(i.price)}</strong><small class="${cls(i.change)}">${pct(i.change)}</small></div>`).join('')}
  function heatClass(v){const a=Math.abs(v);return `${v>=0?'pos':'neg'}${a>3?3:a>1?2:1}`}
  function renderHeat(){const el=$('#heat');if(el)el.innerHTML=snap.heatmap.map((x,i)=>`<a class="${i===0?'s5 ':i===4?'s4 ':''}${heatClass(x.change)}" href="stock.html?symbol=${x.symbol}" aria-label="${x.symbol} ${x.change>=0?'上涨':'下跌'} ${Math.abs(x.change).toFixed(2)}%">${x.symbol}<small class="${cls(x.change)}">${x.change>=0?'+':''}${x.change.toFixed(2)}%</small></a>`).join('')}
  function renderMovers(){const el=$('#movers');if(el)el.innerHTML=snap.movers.map(x=>`<a class="mover" href="stock.html?symbol=${x.symbol}">${x.symbol}<b class="${cls(x.change)}">${pct(x.change)}</b></a>`).join('')}
  function renderEarnings(list=snap.earnings){const el=$('#earnings');if(el)el.innerHTML=list.map(x=>`<div class="event"><div><b>${x.name}</b><small>${x.symbol} · ${x.when} <span class="${cls(x.change)}">${pct(x.change)}</span></small></div><div class="right"><b>${x.status}</b><small>${x.eps}</small></div></div>`).join('')}
  function renderMacro(){const el=$('#macroList');if(el)el.innerHTML=snap.macro.map(x=>`<div class="macro-row"><div><b>${x.name}</b><small>${x.time} · ${x.consensus}</small></div><span class="badge ${x.importance==='高'?'high':'mid'}">${x.importance}重要</span></div>`).join('')}
  function renderCrypto(){const el=$('#cryptoList');if(el)el.innerHTML=snap.crypto.map(x=>`<div class="crypto-row"><div><b>${x.name}</b><small>${x.symbol}</small></div><div style="text-align:right"><b>$${money(x.price)}</b><small class="${cls(x.change)}">${pct(x.change)}</small></div></div>`).join('')}
  function newsHtml(items=snap.news){return items.map(n=>`<article class="news"><div><b>${n.title}</b><small>${n.source} · ${n.time}</small></div><div class="thumb" aria-hidden="true">${n.tag}</div></article>`).join('')}
  function renderNews(){const el=$('#marketNews');if(el)el.innerHTML=newsHtml()}
  let watchView=localStorage.getItem('trfinance.watchView')||'list';let watchFilter='all';
  function watchStocks(){return D.getWatchlist().map(s=>D.getQuote(s))}
  function watchFunds(){return D.getFundWatchlist().map(symbol=>{const f=D.getFund(symbol);return {...f,market:'ETF',spark:D.spark(f.symbol),type:'fund'}})}
  function watchRecords(filter='all'){const stocks=watchStocks().map(x=>({...x,type:'stock'})),funds=watchFunds();if(filter==='etf')return funds;if(filter==='us')return stocks.filter(s=>['NASDAQ','NYSE'].includes(s.market));if(filter==='china')return stocks.filter(s=>s.symbol==='BABA');if(filter==='hk'||filter==='cn')return [];return [...stocks,...funds]}
  function watchMarkup(items){if(watchView==='heat')return `<div class="watch-heat">${items.map(s=>`<a class="watch-tile ${s.change>=0?'pos':'neg'}" href="${s.type==='fund'?'fund.html':'stock.html'}?symbol=${s.symbol}"><div><b>${s.symbol}</b><div class="ticker">${s.name}</div></div><div><strong>${s.change>=0?'+':''}${s.change.toFixed(2)}%</strong><div>$${money(s.price)}</div></div></a>`).join('')}</div>`;return items.map(s=>`<a class="watch" href="${s.type==='fund'?'fund.html':'stock.html'}?symbol=${s.symbol}"><div><div class="name">${s.name}</div><div class="ticker">${s.symbol} · ${s.market}</div></div>${line(s.spark,s.change>=0)}<div class="price">$${money(s.price)}</div><div class="change ${s.change>=0?'upbg':'downbg'}">${s.change>=0?'+':''}${s.change.toFixed(2)}%</div></a>`).join('')}
  function renderWatch(){const el=$('#watchlist');if(!el)return;const items=watchRecords(watchFilter);$('#watchCount').textContent=`${items.length} 项`;el.innerHTML=items.length?watchMarkup(items):`<div class="empty">${watchFilter==='all'?'还没有自选。搜索股票并加入自选后会显示在这里。':'这个分类暂时没有自选。'}</div>`;$$('.view-switch button').forEach(b=>{const on=b.dataset.view===watchView;b.classList.toggle('on',on);b.setAttribute('aria-pressed',String(on))})}
  function renderFunds(){const el=$('#fundList');if(el)el.innerHTML=snap.funds.map(f=>`<a class="fund" href="fund.html?symbol=${f.symbol}"><div><b>${f.name}</b><small>${f.symbol} · ${f.category} · 费率 ${f.expense}</small></div><div>$${money(f.price)}</div><div class="ret ${cls(f.change)}">${f.change>=0?'+':''}${f.change.toFixed(2)}%</div></a>`).join('')}
  function setPage(target,{updateHash=true,scroll=true}={}){const valid=['watch','market','funds','profile'];if(!valid.includes(target))target='market';$$('.bottom button').forEach(b=>{const on=b.dataset.target===target;b.classList.toggle('on',on);b.setAttribute('aria-current',on?'page':'false')});$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===target));if(updateHash&&location.hash!==`#${target}`)history.pushState(null,'',`#${target}`);if(scroll)window.scrollTo({top:0,behavior:document.documentElement.classList.contains('reduce-motion')?'auto':'smooth'});announce(`已切换到${target==='watch'?'自选':target==='market'?'行情':target==='funds'?'基金':'我的'}`)}
  function initNav(){ $$('.bottom button').forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.target)));window.addEventListener('popstate',()=>setPage(location.hash.slice(1),{updateHash:false,scroll:false}));setPage(location.hash.slice(1)||'market',{updateHash:false,scroll:false}) }
  function setMarketPanel(button){$$('.market-tab').forEach(x=>{const on=x===button;x.classList.toggle('on',on);x.setAttribute('aria-selected',String(on));x.setAttribute('tabindex',on?'0':'-1')});$$('.market-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===button.dataset.panel))}
  function initMarketTabs(){const tabs=$$('.market-tab');tabs.forEach((b,i)=>{b.addEventListener('click',()=>setMarketPanel(b));b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let n=i;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='ArrowLeft')n=(i-1+tabs.length)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;tabs[n].focus();setMarketPanel(tabs[n])})})}
  function initWatchTabs(){ $$('.watch-filter').forEach(b=>b.addEventListener('click',()=>{$$('.watch-filter').forEach(x=>{const on=x===b;x.classList.toggle('on',on);x.setAttribute('aria-pressed',String(on))});watchFilter=b.dataset.filter;renderWatch()})) }
  function initViews(){ $$('.view-switch button').forEach(b=>b.addEventListener('click',()=>{watchView=b.dataset.view;localStorage.setItem('trfinance.watchView',watchView);renderWatch()})) }
  function initSearch(){const input=$('#searchInput'),box=$('#searchResults');if(!input||!box)return;let hits=[];let active=-1;function close(){box.classList.remove('open');input.setAttribute('aria-expanded','false');active=-1}function select(i){const links=$$('.search-hit',box);links.forEach((a,n)=>a.classList.toggle('active',n===i));active=i;if(links[i])links[i].scrollIntoView({block:'nearest'})}input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-controls','searchResults');input.setAttribute('aria-expanded','false');input.addEventListener('input',()=>{hits=D.search(input.value);box.innerHTML=hits.map((x,i)=>`<a id="search-option-${i}" role="option" class="search-hit" href="${x.type==='stock'?'stock.html':'fund.html'}?symbol=${x.symbol}"><div><b>${x.name}</b><small>${x.symbol} · ${x.type==='stock'?x.market:x.category}</small></div><span class="${cls(x.change||0)}">${(x.change||0)>=0?'+':''}${(x.change||0).toFixed(2)}%</span></a>`).join('');box.classList.toggle('open',hits.length>0);input.setAttribute('aria-expanded',String(hits.length>0));active=-1});input.addEventListener('keydown',e=>{const links=$$('.search-hit',box);if(e.key==='Escape'){close();return}if(!links.length)return;if(e.key==='ArrowDown'){e.preventDefault();select((active+1)%links.length)}else if(e.key==='ArrowUp'){e.preventDefault();select((active-1+links.length)%links.length)}else if(e.key==='Enter'&&active>=0){e.preventDefault();links[active].click()}});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))close()})}
  function initPrefs(){if(!$('#prefStyles')){const st=document.createElement('style');st.id='prefStyles';st.textContent='.compact .watch{padding:9px 0}.compact .watch .name{font-size:15px}.compact .news{padding:11px 0}.reduce-motion *{scroll-behavior:auto!important;animation:none!important;transition:none!important}';document.head.appendChild(st)}const compact=$('#compactToggle'),motion=$('#motionToggle');let prefs={};try{prefs=JSON.parse(localStorage.getItem('trfinance.prefs')||'{}')}catch(e){};function apply(){document.documentElement.classList.toggle('compact',!!prefs.compact);document.documentElement.classList.toggle('reduce-motion',prefs.motion===false);if(compact){compact.classList.toggle('on',!!prefs.compact);compact.setAttribute('aria-pressed',String(!!prefs.compact))}if(motion){motion.classList.toggle('on',prefs.motion!==false);motion.setAttribute('aria-pressed',String(prefs.motion!==false))}}apply();$$('.toggle').forEach(t=>t.addEventListener('click',()=>{t.classList.toggle('on');prefs[t.dataset.pref]=t.classList.contains('on');localStorage.setItem('trfinance.prefs',JSON.stringify(prefs));apply();announce(`${t.closest('.service')?.querySelector('span')?.textContent||'偏好'}已${t.classList.contains('on')?'开启':'关闭'}`)}))}
  function renderProfileState(){const list=$('#historyList'),count=$('#historyCount'),alerts=$('#alertCount');if(list&&count){let h=[];try{h=JSON.parse(localStorage.getItem('trfinance.history')||'[]')}catch(e){};count.textContent=`${h.length} 条`;list.innerHTML=h.length?h.slice(0,5).map(x=>`<a class="service" style="text-decoration:none;color:inherit" href="${x.type==='fund'?'fund.html':'stock.html'}?symbol=${x.symbol}"><span><b>${x.symbol}</b> · ${x.name}</span><span aria-hidden="true">›</span></a>`).join(''):'<div class="empty">浏览股票或 ETF 后会显示在这里。</div>'}if(alerts){let n=0;for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('trfinance.alert.')&&localStorage.getItem(k)==='1')n++}alerts.textContent=n}}
  renderIndices();renderHeat();renderMovers();renderEarnings();renderMacro();renderCrypto();renderNews();renderWatch();renderFunds();renderProfileState();initNav();initMarketTabs();initWatchTabs();initViews();initSearch();initPrefs();
})();