(function(){
  const D=window.FinanceData; if(!D)return;
  const snap=D.getMarketSnapshot();
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const money=v=>typeof v==='number'?v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):v;
  const pct=v=>`${v>=0?'▲':'▼'} ${Math.abs(v).toFixed(2)}%`;
  const cls=v=>v>=0?'up':'down';
  const line=(points,positive=true)=>{const max=Math.max(...points),min=Math.min(...points),w=86,h=34;const p=points.map((v,i)=>`${(i/(points.length-1))*w},${h-3-((v-min)/(max-min||1))*(h-6)}`).join(' ');return `<svg class="spark" viewBox="0 0 ${w} ${h}" aria-hidden="true"><polyline points="${p}" fill="none" stroke="${positive?'#00c805':'#ff4d2e'}" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg>`};
  function renderIndices(){const el=$('#indices');if(!el)return;el.innerHTML=snap.indices.map(i=>`<div class="indexcard"><b>${i.name}</b><strong class="${cls(i.change)}">${money(i.price)}</strong><small class="${cls(i.change)}">${pct(i.change)}</small></div>`).join('')}
  function heatClass(v){const a=Math.abs(v);return `${v>=0?'pos':'neg'}${a>3?3:a>1?2:1}`}
  function renderHeat(){const el=$('#heat');if(!el)return;el.innerHTML=snap.heatmap.map((x,i)=>`<a class="${i===0?'s5 ':i===4?'s4 ':''}${heatClass(x.change)}" href="stock.html?symbol=${x.symbol}">${x.symbol}<small class="${cls(x.change)}">${x.change>=0?'+':''}${x.change.toFixed(2)}%</small></a>`).join('')}
  function renderMovers(){const el=$('#movers');if(!el)return;el.innerHTML=snap.movers.map(x=>`<a class="mover" href="stock.html?symbol=${x.symbol}">${x.symbol}<b class="${cls(x.change)}">${pct(x.change)}</b></a>`).join('')}
  function renderEarnings(list=snap.earnings){const el=$('#earnings');if(!el)return;el.innerHTML=list.map(x=>`<div class="event"><div><b>${x.name}</b><small>${x.symbol} · ${x.when} <span class="${cls(x.change)}">${pct(x.change)}</span></small></div><div class="right"><b>${x.status}</b><small>${x.eps}</small></div></div>`).join('')}
  function renderMacro(){const el=$('#macroList');if(!el)return;el.innerHTML=snap.macro.map(x=>`<div class="macro-row"><div><b>${x.name}</b><small>${x.time} · ${x.consensus}</small></div><span class="badge ${x.importance==='高'?'high':'mid'}">${x.importance}重要</span></div>`).join('')}
  function renderCrypto(){const el=$('#cryptoList');if(!el)return;el.innerHTML=snap.crypto.map(x=>`<div class="crypto-row"><div><b>${x.name}</b><small>${x.symbol}</small></div><div style="text-align:right"><b>$${money(x.price)}</b><small class="${cls(x.change)}">${pct(x.change)}</small></div></div>`).join('')}
  function newsHtml(items=snap.news){return items.map(n=>`<a class="news" href="#"><div><b>${n.title}</b><small>${n.source} · ${n.time}</small></div><div class="thumb">${n.tag}</div></a>`).join('')}
  function renderNews(){const el=$('#marketNews');if(el)el.innerHTML=newsHtml()}
  let watchView=localStorage.getItem('trfinance.watchView')||'list';
  function watchStocks(){return D.getWatchlist().map(s=>D.getQuote(s))}
  function watchFunds(){return D.getFundWatchlist().map(symbol=>{const f=D.getFund(symbol);return {...f,market:'ETF',spark:D.spark(f.symbol),type:'fund'};})}
  function watchRecords(filter='all'){const stocks=watchStocks().map(x=>({...x,type:'stock'})),funds=watchFunds();if(filter==='etf')return funds;if(filter==='us')return stocks.filter(s=>['NASDAQ','NYSE'].includes(s.market));if(filter==='china')return stocks.filter(s=>s.symbol==='BABA');if(filter==='hk'||filter==='cn')return [];return [...stocks,...funds];}
  function renderWatch(){const el=$('#watchlist');if(!el)return;const items=watchRecords();$('#watchCount').textContent=`${items.length} 项`;
    if(!items.length){el.innerHTML='<div class="empty">还没有自选。搜索股票并加入自选后会显示在这里。</div>';return}
    if(watchView==='heat') el.innerHTML=`<div class="watch-heat">${items.map(s=>`<a class="watch-tile ${s.change>=0?'pos':'neg'}" href="${s.type==='fund'?'fund.html':'stock.html'}?symbol=${s.symbol}"><div><b>${s.symbol}</b><div class="ticker">${s.name}</div></div><div><strong>${s.change>=0?'+':''}${s.change.toFixed(2)}%</strong><div>$${money(s.price)}</div></div></a>`).join('')}</div>`;
    else el.innerHTML=items.map(s=>`<a class="watch" href="${s.type==='fund'?'fund.html':'stock.html'}?symbol=${s.symbol}"><div><div class="name">${s.name}</div><div class="ticker">${s.symbol} · ${s.market}</div></div>${line(s.spark,s.change>=0)}<div class="price">$${money(s.price)}</div><div class="change ${s.change>=0?'upbg':'downbg'}">${s.change>=0?'+':''}${s.change.toFixed(2)}%</div></a>`).join('');
    $$('.view-switch button').forEach(b=>b.classList.toggle('on',b.dataset.view===watchView));
  }
  function renderFunds(){const el=$('#fundList');if(!el)return;el.innerHTML=snap.funds.map(f=>`<a class="fund" href="fund.html?symbol=${f.symbol}"><div><b>${f.name}</b><small>${f.symbol} · ${f.category} · 费率 ${f.expense}</small></div><div>$${money(f.price)}</div><div class="ret ${cls(f.change)}">${f.change>=0?'+':''}${f.change.toFixed(2)}%</div></a>`).join('')}
  function initNav(){ $$('.bottom button').forEach(b=>b.addEventListener('click',()=>{$$('.bottom button').forEach(x=>x.classList.toggle('on',x===b));$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===b.dataset.target));window.scrollTo({top:0,behavior:'smooth'})})) }
  function initMarketTabs(){ $$('.market-tab').forEach(b=>b.addEventListener('click',()=>{$$('.market-tab').forEach(x=>x.classList.toggle('on',x===b));$$('.market-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.panel))})) }
  function initWatchTabs(){ $$('.watch-filter').forEach(b=>b.addEventListener('click',()=>{$$('.watch-filter').forEach(x=>x.classList.toggle('on',x===b));const filtered=watchRecords(b.dataset.filter);const el=$('#watchlist');$('#watchCount').textContent=`${filtered.length} 项`;if(!filtered.length){el.innerHTML='<div class="empty">这个分类暂时没有自选。</div>';return}if(watchView==='heat')el.innerHTML=`<div class="watch-heat">${filtered.map(s=>`<a class="watch-tile ${s.change>=0?'pos':'neg'}" href="${s.type==='fund'?'fund.html':'stock.html'}?symbol=${s.symbol}"><div><b>${s.symbol}</b><div class="ticker">${s.name}</div></div><div><strong>${s.change>=0?'+':''}${s.change.toFixed(2)}%</strong><div>$${money(s.price)}</div></div></a>`).join('')}</div>`;else el.innerHTML=filtered.map(s=>`<a class="watch" href="${s.type==='fund'?'fund.html':'stock.html'}?symbol=${s.symbol}"><div><div class="name">${s.name}</div><div class="ticker">${s.symbol} · ${s.market}</div></div>${line(s.spark,s.change>=0)}<div class="price">$${money(s.price)}</div><div class="change ${s.change>=0?'upbg':'downbg'}">${s.change>=0?'+':''}${s.change.toFixed(2)}%</div></a>`).join('')})) }
  function initViews(){ $$('.view-switch button').forEach(b=>b.addEventListener('click',()=>{watchView=b.dataset.view;localStorage.setItem('trfinance.watchView',watchView);renderWatch()})) }
  function initSearch(){const input=$('#searchInput'),box=$('#searchResults');if(!input||!box)return;input.addEventListener('input',()=>{const r=D.search(input.value);box.innerHTML=r.map(x=>`<a class="search-hit" href="${x.type==='stock'?'stock.html':'fund.html'}?symbol=${x.symbol}"><div><b>${x.name}</b><small>${x.symbol} · ${x.type==='stock'?x.market:x.category}</small></div><span class="${cls(x.change||0)}">${(x.change||0)>=0?'+':''}${(x.change||0).toFixed(2)}%</span></a>`).join('');box.classList.toggle('open',r.length>0)});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))box.classList.remove('open')})}
  function initPrefs(){const compact=$('#compactToggle'),motion=$('#motionToggle');const prefs=JSON.parse(localStorage.getItem('trfinance.prefs')||'{}');if(compact)compact.classList.toggle('on',!!prefs.compact);if(motion)motion.classList.toggle('on',prefs.motion!==false);$$('.toggle').forEach(t=>t.addEventListener('click',()=>{t.classList.toggle('on');prefs[t.dataset.pref]=t.classList.contains('on');localStorage.setItem('trfinance.prefs',JSON.stringify(prefs))}))}
  renderIndices();renderHeat();renderMovers();renderEarnings();renderMacro();renderCrypto();renderNews();renderWatch();renderFunds();initNav();initMarketTabs();initWatchTabs();initViews();initSearch();initPrefs();
})();
