(function(){
  const D=window.FinanceData;if(!D)return;const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const symbol=(new URLSearchParams(location.search).get('symbol')||'SPY').toUpperCase();const f=D.getFund(symbol);const money=v=>v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
  function notify(text){let t=$('#financeToast');if(!t){t=document.createElement('div');t.id='financeToast';t.className='finance-toast';t.setAttribute('role','status');t.setAttribute('aria-live','polite');document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.classList.remove('show'),2200)}
  function recordHistory(){let h=[];try{h=JSON.parse(localStorage.getItem('trfinance.history')||'[]')}catch(e){}h=[{type:'fund',symbol:f.symbol,name:f.name,ts:Date.now()},...h.filter(x=>!(x.type==='fund'&&x.symbol===f.symbol))].slice(0,20);localStorage.setItem('trfinance.history',JSON.stringify(h))}recordHistory();
  document.title=`${f.name} (${f.symbol})｜唐人财经`;$('#fundSymbol').textContent=f.symbol;$('#fundName').textContent=f.name;$('#fundPrice').textContent=`$${money(f.price)}`;$('#fundChange').textContent=`${f.change>=0?'▲':'▼'} ${Math.abs(f.change).toFixed(2)}%`;$('#fundChange').className=`move ${f.change>=0?'up':'down'}`;$('#fundCat').textContent=f.category;$('#fundExpense').textContent=f.expense;$('#fundAum').textContent=f.aum;$('#fundRisk').textContent=f.risk;
  $('#holdings').innerHTML=f.holdings.map((h,i)=>`<div class="event"><div><b>${h}</b><small>示例核心持仓 ${i+1}</small></div><div class="right"><b>${[8.4,7.8,6.6][i]||5.1}%</b><small>示例权重</small></div></div>`).join('');
  function chart(factor=1){const base=D.spark(f.symbol);const points=Array.from({length:48},(_,i)=>base[i%base.length]+Math.sin((i+factor)/4)*factor*1.8+(i*factor%7)/4);const max=Math.max(...points),min=Math.min(...points),w=800,h=400;const pts=points.map((v,i)=>`${(i/(points.length-1))*w},${h-28-((v-min)/(max-min||1))*(h-70)}`).join(' ');return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="${f.symbol} ETF 演示走势图"><polyline points="${pts}" fill="none" stroke="${f.change>=0?'#00c805':'#ff4d2e'}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg>`}$('#fundChart').innerHTML=chart(1);
  $$('.range button[data-range]').forEach((b,i)=>b.addEventListener('click',()=>{$$('.range button[data-range]').forEach(x=>{const on=x===b;x.classList.toggle('on',on);x.setAttribute('aria-pressed',String(on))});$('#fundChart').innerHTML=chart(i+1);notify(`已切换到 ${b.dataset.range} 走势图`)}));
  const btn=$('#fundWatchBtn');function sync(){const on=D.getFundWatchlist().includes(f.symbol);btn.textContent=on?'✓ 已关注':'+ 加入基金自选';btn.setAttribute('aria-pressed',String(on))}sync();btn.addEventListener('click',()=>{const on=D.toggleFundWatch(f.symbol);sync();notify(`${f.symbol} 已${on?'加入':'移出'}基金自选`)});
  const back=$('#fundBackBtn');if(back)back.addEventListener('click',()=>{if(history.length>1)history.back();else location.href='./#funds'});
})();