Warning: truncated output (original token count: 38926)
Total output lines: 431

(() => {
  const locales = ['en', 'es', 'fr', 'pt-BR', 'hi', 'zh-Hans', 'zh-Hant', 'ru', 'ar', 'tr'];
  const aliases = { zh: 'zh-Hans', 'zh-CN': 'zh-Hans', 'zh-SG': 'zh-Hans', 'zh-TW': 'zh-Hant', 'zh-HK': 'zh-Hant', pt: 'pt-BR', 'pt-PT': 'pt-BR' };
  const localePaths = { en: 'en', es: 'es', fr: 'fr', 'pt-BR': 'pt-br', hi: 'hi', 'zh-Hans': '', 'zh-Hant': 'zh-hant', ru: 'ru', ar: 'ar', tr: 'tr' };
  const pathLocales = new Map(Object.entries(localePaths).filter(([, path]) => path).map(([key, path]) => [path, key]));
  const normalize = (value) => {
    const raw = String(value || '');
    if (locales.includes(raw)) return raw;
    if (aliases[raw]) return aliases[raw];
    const base = raw.split('-')[0].toLowerCase();
    return locales.find((item) => item.toLowerCase() === base) || (base === 'pt' ? 'pt-BR' : base === 'zh' ? 'zh-Hans' : 'zh-Hans');
  };
  const firstPathSegment = location.pathname.split('/').filter(Boolean)[0]?.toLowerCase() || '';
  const localeFromPath = pathLocales.get(firstPathSegment) || '';
  let locale = normalize(localeFromPath || new URLSearchParams(location.search).get('lang') || (() => { try { return localStorage.getItem('asylumjudge-language'); } catch { return ''; } })() || 'zh-Hans');

  const pathForLocale = (pathname, nextLocale) => {
    const parts = String(pathname || '/').split('/').filter(Boolean);
    if (parts.length && pathLocales.has(parts[0].toLowerCase())) parts.shift();
    const base = `/${parts.join('/')}${String(pathname || '').endsWith('/') && parts.length ? '/' : ''}` || '/';
    const prefix = localePaths[nextLocale] || '';
    if (!prefix) return base === '' ? '/' : base;
    return `/${prefix}${base === '/' ? '/' : base}`;
  };

  // Source, EN, ES, FR, PT-BR, HI, ZH-HANT, RU, AR, TR.
  const rows = [
    ['最近 24 个月（读取中）','Last 24 months (loading)','Últimos 24 meses (cargando)','24 derniers mois (chargement)','Últimos 24 meses (carregando)','पिछले 24 महीने (लोड हो रहा है)','最近 24 個月（讀取中）','Последние 24 месяца (загрузка)','آخر 24 شهرًا (جارٍ التحميل)','Son 24 ay (yükleniyor)'],
    ['最近 24 个月','Last 24 months','Últimos 24 meses','24 derniers mois','Últimos 24 meses','पिछले 24 महीने','最近 24 個月','Последние 24 месяца','آخر 24 شهرًا','Son 24 ay'],
    ['选择趋势周期','Select trend interval','Elegir intervalo','Choisir la période','Selecionar período','रुझान अवधि चुनें','選擇趨勢週期','Выберите период','اختر فترة الاتجاه','Eğilim dönemini seçin'],
    ['按月','Monthly','Mensual','Mensuel','Mensal','मासिक','按月','По месяцам','شهري','Aylık'],
    ['按财年','By fiscal year','Por año fiscal','Par exercice','Por ano fiscal','वित्त वर्ष के अनुसार','按財年','По финансовым годам','حسب السنة المالية','Mali yıla göre'],
    ['批准率','Approval rate','Tasa de aprobación','Taux d’approbation','Taxa de aprovação','अनुमोदन दर','批准率','Доля одобрений','نسبة الموافقة','Onay oranı'],
    ['拒绝率','Denial rate','Tasa de denegación','Taux de refus','Taxa de negativa','अस्वीकृति दर','拒絕率','Доля отказов','نسبة الرفض','Ret oranı'],
    ['其他占比','Other outcomes','Otros resultados','Autres résultats','Outros resultados','अन्य परिणाम','其他占比','Другие исходы','نتائج أخرى','Diğer sonuçlar'],
    ['结案量','Decisions','Decisiones','Décisions','Decisões','निर्णय','結案量','Решения','القرارات','Kararlar'],
    ['正在读取州趋势数据…','Loading state trend data…','Cargando tendencias estatales…','Chargement des tendances par État…','Carregando tendências estaduais…','राज्य रुझान डेटा लोड हो रहा है…','正在讀取州趨勢資料…','Загрузка тренда штата…','جارٍ تحميل اتجاه الولاية…','Eyalet eğilimi yükleniyor…'],
    ['按州查看','View by state','Ver por estado','Voir par État','Ver por estado','राज्य के अनुसार देखें','按州查看','По штату','عرض حسب الولاية','Eyalete göre görüntüle'],
    ['按城市／法院查看','View by city / court','Ver por ciudad / tribunal','Voir par ville / tribunal','Ver por cidade / tribunal','शहर / अदालत के अनुसार','按城市／法院查看','По городу / суду','حسب المدينة / المحكمة','Şehir / mahkemeye göre'],
    ['选择州','Select a state','Seleccione un estado','Sélectionner un État','Selecione um estado','राज्य चुनें','選擇州','Выберите штат','اختر ولاية','Eyalet seçin'],
    ['选择城市或移民法院','Select a city or immigration court','Seleccione una ciudad o tribunal','Sélectionner une ville ou un tribunal','Selecione uma cidade ou tribunal','शहर या इमिग्रेशन कोर्ट चुनें','選擇城市或移民法院','Выберите город или иммиграционный суд','اختر مدينة أو محكمة هجرة','Şehir veya göçmenlik mahkemesi seçin'],
    ['请选择城市／移民法院','Choose a city / immigration court','Elija una ciudad / tribunal','Choisissez une ville / tribunal','Escolha uma cidade / tribunal','शहर / इमिग्रेशन कोर्ट चुनें','請選擇城市／移民法院','Выберите город / суд','اختر مدينة / محكمة هجرة','Şehir / göçmenlik mahkemesi seçin'],
    ['华人聚集城市快捷入口','Popular city shortcuts','Accesos a ciudades populares','Raccourcis vers les villes populaires','Atalhos de cidades populares','लोकप्रिय शहर शॉर्टकट','華人聚集城市快捷入口','Популярные города','اختصارات المدن الشائعة','Popüler şehir kısayolları'],
    ['常用城市','Popular cities','Ciudades populares','Villes populaires','Cidades populares','लोकप्रिय शहर','常用城市','Популярные города','مدن شائعة','Popüler şehirler'],
    ['点按或移动到图中数据点，查看该期案件数量。','Tap or move across a point to see decisions for that period.','Toque o mueva sobre un punto para ver las decisiones del período.','Touchez ou parcourez un point pour voir les décisions de la période.','Toque ou deslize sobre um ponto para ver as decisões do período.','उस अवधि के निर्णय देखने के लिए बिंदु पर टैप या खिसकाएँ।','點按或移動到圖中資料點，查看該期案件數量。','Коснитесь точки или проведите по ней, чтобы увидеть решения за период.','المس نقطة أو حرّك عليها لعرض قرارات الفترة.','Dönemin kararlarını görmek için noktaya dokunun veya üzerinde hareket edin.'],
    ['法官、法院或城市','Judge, court, or city','Juez, tribunal o ciudad','Juge, tribunal ou ville','Juiz, tribunal ou cidade','न्यायाधीश, अदालत या शहर','法官、法院或城市','Судья, суд или город','القاضي أو المحكمة أو المدينة','Hâkim, mahkeme veya şehir'],
    ['例如：法官姓名、New York、Houston','For example: judge name, New York, Houston','Ej.: nombre del juez, New York, Houston','Ex. : nom du juge, New York, Houston','Ex.: nome do juiz, New York, Houston','उदाहरण: न्यायाधीश का नाम, New York, Houston','例如：法官姓名、New York、Houston','Например: имя судьи, New York, Houston','مثال: اسم القاضي أو New York أو Houston','Örn. hâkim adı, New York, Houston'],
    ['筛选法官','Filter judges','Filtrar jueces','Filtrer les juges','Filtrar juízes','न्यायाधीश फ़िल्टर करें','篩選法官','Фильтр судей','تصفية القضاة','Hâkimleri filtrele'],
    ['热门查询','Popular searches','Búsquedas populares','Recherches populaires','Pesquisas populares','लोकप्रिय खोजें','熱門查詢','Популярные запросы','عمليات بحث شائعة','Popüler aramalar'],
    ['历史统计仅供信息参考，不构成法律意见，也不能预测个案结果。','Historical statistics are informational only, not legal advice, and cannot predict an individual case.','Las estadísticas históricas son solo informativas, no constituyen asesoría legal ni predicen un caso individual.','Les statistiques historiques sont informatives, ne constituent pas un avis juridique et ne prédisent aucun dossier.','As estatísticas históricas são apenas informativas, não constituem aconselhamento jurídico nem preveem um caso individual.','ऐतिहासिक आँकड़े केवल जानकारी के लिए हैं, कानूनी सलाह नहीं हैं और किसी मामले के परिणाम की भविष्यवाणी नहीं करते।','歷史統計僅供資訊參考，不構成法律意見，也不能預測個案結果。','Историческая статистика носит справочный характер, не является юридической консультацией и не предсказывает исход дела.','الإحصاءات التاريخية للمعلومات فقط وليست نصيحة قانونية ولا تتنبأ بنتيجة قضية فردية.','Tarihsel istatistikler yalnızca bilgi amaçlıdır; hukuki tavsiye değildir ve tek bir davayı öngöremez.'],
    ['全美数据库概览','National database overview','Resumen de la base nacional','Aperçu de la base nationale','Visão geral da base nacional','राष्ट्रीय डेटाबेस अवलोकन','全美資料庫概覽','Обзор национальной базы','نظرة عامة على قاعدة البيانات الوطنية','Ulusal veri tabanı özeti'],
    ['庇护裁决数据','Asylum decision data','Datos de decisiones de asilo','Données des décisions d’asile','Dados de decisões de asilo','शरण निर्णय डेटा','庇護裁決資料','Данные решений об убежище','بيانات قرارات اللجوء','Sığınma kararı verileri'],
    ['选择财政年度','Select fiscal year','Seleccione el año fiscal','Sélectionner l’exercice','Selecione o ano fiscal','वित्त वर्ष चुनें','選擇財政年度','Выберите финансовый год','اختر السنة المالية','Mali yılı seçin'],
    ['读取中','Loading','Cargando','Chargement','Carregando','लोड हो रहा है','讀取中','Загрузка','جارٍ التحميل','Yükleniyor'],
    ['全美裁决批准率','National decision approval rate','Tasa nacional de aprobación','Taux national d’approbation','Taxa nacional de aprovação','राष्ट्रीय निर्णय अनुमोदन दर','全美裁決批准率','Национальная доля одобрений','نسبة الموافقة الوطنية','Ulusal karar onay oranı'],
    ['正在汇总州级样本','Aggregating state samples','Agregando muestras estatales','Agrégation des échantillons par État','Agregando amostras estaduais','राज्य नमूनों का सार बनाया जा रहा है','正在彙總州級樣本','Свод данных по штатам','جارٍ تجميع عينات الولايات','Eyalet örnekleri toplanıyor'],
    ['法院','Courts','Tribunales','Tribunaux','Tribunais','अदालतें','法院','Суды','المحاكم','Mahkemeler'],
    ['法官','Judges','Jueces','Juges','Juízes','न्यायाधीश','法官','Судьи','القضاة','Hâkimler'],
    ['庇护裁决','Asylum decisions','Decisiones de asilo','Décisions d’asile','Decisões de asilo','शरण निर्णय','庇護裁決','Решения об убежище','قرارات اللجوء','Sığınma kararları'],
    ['主要州数据','Major state data','Datos de los principales estados','Données des principaux États','Dados dos principais estados','प्रमुख राज्य डेटा','主要州資料','Данные основных штатов','بيانات الولايات الرئيسية','Başlıca eyalet verileri'],
    ['裁决批准率','Decision approval rate','Tasa de aprobación de decisiones','Taux d’approbation des décisions','Taxa de aprovação das decisões','निर्णय अनुमोदन दर','裁決批准率','Доля одобренных решений','نسبة الموافقة على القرارات','Karar onay oranı'],
    ['查看全部州数据','View all state data','Ver todos los estados','Voir toutes les données par État','Ver todos os estados','सभी राज्य डेटा देखें','查看全部州資料','Все данные штатов','عرض جميع بيانات الولايات','Tüm eyalet verilerini görüntüle'],
    ['全部移民法官','All immigration judges','Todos los jueces de inmigración','Tous les juges de l’immigration','Todos os juízes de imigração','सभी इमिग्रेशन जज','全部移民法官','Все иммиграционные судьи','جميع قضاة الهجرة','Tüm göçmenlik hâkimleri'],
    ['展示截至数据库最新批次的全部法官。可在上方按姓名、法院、城市或州筛选，点击法官查看完整通过率资料。','Shows every judge in the latest database release. Filter above by name, court, city, or state, then open a judge profile for complete rate data.','Muestra todos los jueces de la última versión. Filtre por nombre, tribunal, ciudad o estado y abra el perfil completo.','Affiche tous les juges de la dernière version. Filtrez par nom, tribunal, ville ou État, puis ouvrez le profil complet.','Mostra todos os juízes da versão mais recente. Filtre por nome, tribunal, cidade ou estado e abra o perfil completo.','नवीनतम डेटाबेस के सभी न्यायाधीश दिखाता है। नाम, अदालत, शहर या राज्य से फ़िल्टर कर पूरी प्रोफ़ाइल खोलें।','展示截至資料庫最新批次的全部法官。可在上方按姓名、法院、城市或州篩選，點擊法官查看完整批准率資料。','Показаны все судьи из последней версии базы. Фильтруйте по имени, суду, городу или штату и откройте профиль.','يعرض جميع القضاة في أحدث إصدار من قاعدة البيانات. صفِّ حسب الاسم أو المحكمة أو المدينة أو الولاية ثم افتح الملف الكامل.','En son veri tabanındaki tüm hâkimleri gösterir. Ad, mahkeme, şehir veya eyalete göre filtreleyip profili açın.'],
    ['正在读取全部法官…','Loading all judges…','Cargando todos los jueces…','Chargement de tous les juges…','Carregando todos os juízes…','सभी न्यायाधीश लोड हो रहे हैं…','正在讀取全部法官…','Загрузка всех судей…','جارٍ تحميل جميع القضاة…','Tüm hâkimler yükleniyor…'],
    ['法官与法院','Judge and court','Juez y tribunal','Juge et tribunal','Juiz e tribunal','न्यायाधीश और अदालत','法官與法院','Судья и суд','القاضي والمحكمة','Hâkim ve mahkeme'],
    ['裁决','Decisions','Decisiones','Décisions','Decisões','निर्णय','裁決','Решения','القرارات','Kararlar'],
    ['批准','Approved','Aprobadas','Approuvées','Aprovados','अनुमोदित','批准','Одобрено','موافق عليها','Onay'],
    ['拒绝','Denied','Denegadas','Refusées','Negados','अस्वीकृत','拒絕','Отказано','مرفوضة','Ret'],
    ['其他','Other','Otros','Autres','Outros','अन्य','其他','Другое','أخرى','Diğer'],
    ['每日庇护知识','Daily asylum knowledge','Conocimiento diario sobre asilo','Connaissances quotidiennes sur l’asile','Conhecimento diário sobre asilo','दैनिक शरण जानकारी','每日庇護知識','Ежедневно об убежище','معلومات يومية عن اللجوء','Günlük sığınma bilgisi'],
    ['与唐人日报“移民美国 · 庇护知识”同步，每日更新。','Synced daily with Tang Ren Daily’s U.S. immigration and asylum knowledge center.','Sincronizado a diario con el centro de inmigración y asilo de Tang Ren Daily.','Synchronisé chaque jour avec le centre immigration et asile de Tang Ren Daily.','Sincronizado diariamente com o centro de imigração e asilo do Tang Ren Daily.','Tang Ren Daily के अमेरिकी इमिग्रेशन और शरण केंद्र से रोज़ सिंक।','與唐人日報「移民美國 · 庇護知識」同步，每日更新。','Ежедневная синхронизация с центром знаний Tang Ren Daily.','مزامنة يومية مع مركز الهجرة واللجوء في صحيفة تانغ رن.','Tang Ren Daily göç ve sığınma merkeziyle günlük eşitlenir.'],
    ['进入庇护知识库','Open asylum knowledge center','Abrir el centro de asilo','Ouvrir le centre d’asile','Abrir o centro de asilo','शरण जानकारी केंद्र खोलें','進入庇護知識庫','Открыть центр знаний','فتح مركز معلومات اللجوء','Sığınma bilgi merkezini aç'],
    ['正在读取今日庇护知识…','Loading today’s asylum knowledge…','Cargando información de hoy…','Chargement des informations du jour…','Carregando informações de hoje…','आज की शरण जानकारी लोड हो रही है…','正在讀取今日庇護知識…','Загрузка материалов дня…','جارٍ تحميل معلومات اليوم…','Bugünün sığınma bilgileri yükleniyor…'],
    ['查询入口','Search tools','Herramientas de búsqueda','Outils de recherche','Ferramentas de busca','खोज उपकरण','查詢入口','Инструменты поиска','أدوات البحث','Arama araçları'],
    ['查移民法官','Find an immigration judge','Buscar un juez de inmigración','Trouver un juge de l’immigration','Buscar juiz de imigração','इमिग्रेशन जज खोजें','查移民法官','Найти иммиграционного судью','البحث عن قاضي هجرة','Göçmenlik hâkimi ara'],
    ['姓名、法院或城市','Name, court, or city','Nombre, tribunal o ciudad','Nom, tribunal ou ville','Nome, tribunal ou cidade','नाम, अदालत या शहर','姓名、法院或城市','Имя, суд или город','الاسم أو المحكمة أو المدينة','Ad, mahkeme veya şehir'],
    ['对比','Compare','Comparar','Comparer','Comparar','तुलना','對比','Сравнить','مقارنة','Karşılaştır'],
    ['法官对比','Compare judges','Comparar jueces','Comparer les juges','Comparar juízes','न्यायाधीशों की तुलना','法官比較','Сравнение судей','مقارنة القضاة','Hâkimleri karşılaştır'],
    ['同时比较2至4名法官','Compare 2–4 judges side by side','Compare entre 2 y 4 jueces','Comparez 2 à 4 juges','Compare de 2 a 4 juízes','2–4 न्यायाधीशों की तुलना करें','同時比較2至4名法官','Сравните 2–4 судей','قارن بين قاضيين و4 قضاة','2–4 hâkimi karşılaştırın'],
    ['同时选择2至4名法官，对比批准率、样本量、年度趋势、国籍和官方背景。','Select 2–4 judges to compare approval rates, sample sizes, yearly trends, nationalities, and official backgrounds.','Seleccione de 2 a 4 jueces para comparar tasas, muestras, tendencias, nacionalidades y antecedentes oficiales.','Sélectionnez 2 à 4 juges pour comparer les taux, échantillons, tendances, nationalités et parcours officiels.','Selecione de 2 a 4 juízes para comparar taxas, amostras, tendências, nacionalidades e históricos oficiais.','अनुमोदन दर, नमूने, वार्षिक रुझान, राष्ट्रीयता और आधिकारिक पृष्ठभूमि की तुलना के लिए 2–4 न्यायाधीश चुनें।','同時選擇2至4名法官，比較批准率、樣本量、年度趨勢、國籍和官方背景。','Выберите 2–4 судей для сравнения долей одобрения, выборок, годовых трендов, гражданства и официальных биографий.','اختر من قاضيين إلى أربعة لمقارنة نسب الموافقة والعينات والاتجاهات السنوية والجنسيات والسير الرسمية.','Onay oranlarını, örneklemleri, yıllık eğilimleri, uyrukları ve resmî geçmişleri karşılaştırmak için 2–4 hâkim seçin.'],
    ['开始对比','Start comparing','Iniciar comparación','Commencer la comparaison','Iniciar comparação','तुलना शुरू करें','開始比較','Начать сравнение','ابدأ المقارنة','Karşılaştırmaya başla'],
    ['全部移民法院','All immigration courts','Todos los tribunales de inmigración','Tous les tribunaux de l’immigration','Todos os tribunais de imigração','सभी इमिग्रेशन कोर्ट','全部移民法院','Все иммиграционные суды','جميع محاكم الهجرة','Tüm göçmenlik mahkemeleri'],
    ['比较法院裁决数据','Compare court decision data','Comparar datos de tribunales','Comparer les données des tribunaux','Comparar dados dos tribunais','अदालत निर्णय डेटा की तुलना','比較法院裁決資料','Сравнить данные судов','مقارنة بيانات المحاكم','Mahkeme karar verilerini karşılaştır'],
    ['各州','States','Estados','États','Estados','राज्य','各州','Штаты','الولايات','Eyaletler'],
    ['州级法院与法官汇总','State-level court and judge summary','Resumen estatal de tribunales y jueces','Résumé des tribunaux et juges par État','Resumo estadual de tribunais e juízes','राज्य स्तर पर अदालत और न्यायाधीश सारांश','州級法院與法官彙總','Сводка судов и судей по штатам','ملخص المحاكم والقضاة حسب الولاية','Eyalet düzeyinde mahkeme ve hâkim özeti'],
    ['国际','Global','Global','Mondial','Global','वैश्विक','國際','Мир','عالمي','Küresel'],
    ['国际批准率','Nationality approval rates','Tasas por nacionalidad','Taux par nationalité','Taxas por nacionalidade','राष्ट्रीयता अनुमोदन दर','國際批准率','Одобрение по гражданству','نسب الموافقة حسب الجنسية','Uyruğa göre onay oranları'],
    ['搜索中国、古巴、韩国等国籍','Search China, Cuba, Korea, and more','Buscar China, Cuba, Corea y más','Rechercher Chine, Cuba, Corée et plus','Buscar China, Cuba, Coreia e mais','चीन, क्यूबा, कोरिया आदि खोजें','搜尋中國、古巴、韓國等國籍','Поиск Китая, Кубы, Кореи и других','ابحث عن الصين وكوبا وكوريا وغيرها','Çin, Küba, Kore ve daha fazlasını ara'],
    ['查询移民法官','Search immigration judges','Buscar jueces de inmigración','Rechercher des juges de l’immigration','Buscar juízes de imigração','इमिग्रेशन जज खोजें','查詢移民法官','Поиск иммиграционных судей','البحث عن قضاة الهجرة','Göçmenlik hâkimlerini ara'],
    ['按姓名查找法官，并打开包含法院、国籍、年度趋势和案件样本量的资料页。','Find a judge by name and open a profile with court, nationality, yearly trends, and sample size.','Busque por nombre y abra un perfil con tribunal, nacionalidad, tendencias y muestra.','Recherchez un juge par nom et ouvrez son profil avec tribunal, nationalité, tendances et échantillon.','Busque por nome e abra o perfil com tribunal, nacionalidade, tendências e amostra.','नाम से न्यायाधीश खोजें और अदालत, राष्ट्रीयता, वार्षिक रुझान व नमूना आकार वाली प्रोफ़ाइल खोलें।','按姓名查找法官，並開啟包含法院、國籍、年度趨勢和案件樣本量的資料頁。','Найдите судью по имени и откройте профиль с судом, гражданством, трендами и выборкой.','ابحث عن القاضي بالاسم وافتح ملفًا يتضمن المحكمة والجنسية والاتجاهات وحجم العينة.','Hâkimi adına göre bulun; mahkeme, uyruk, yıllık eğilim ve örneklem bilgilerini açın.'],
    ['法院批准率','Court approval rates','Tasas de aprobación por tribunal','Taux d’approbation des tribunaux','Taxas de aprovação dos tribunais','अदालत अनुमोदन दर','法院批准率','Одобрение по судам','نسب الموافقة حسب المحكمة','Mahkeme onay oranları'],
    ['查看各移民法院的法官人数、裁决量和历史批准率。','View judge counts, decision volume, and historical approval rates for every court.','Vea jueces, volumen de decisiones y tasas históricas de cada tribunal.','Consultez le nombre de juges, le volume et les taux historiques de chaque tribunal.','Veja juízes, volume de decisões e taxas históricas de cada tribunal.','हर अदालत के न्यायाधीश, निर्णय संख्या और ऐतिहासिक अनुमोदन दर देखें।','查看各移民法院的法官人數、裁決量和歷史批准率。','Смотрите число судей, объём решений и исторические доли по каждому суду.','اعرض عدد القضاة وحجم القرارات والنسب التاريخية لكل محكمة.','Her mahkemenin hâkim sayısını, karar hacmini ve tarihsel oranlarını görün.'],
    ['查看法院','View courts','Ver tribunales','Voir les tribunaux','Ver tribunais','अदालतें देखें','查看法院','Смотреть суды','عرض المحاكم','Mahkemeleri görüntüle'],
    ['年度趋势','Yearly trends','Tendencias anuales','Tendances annuelles','Tendências anuais','वार्षिक रुझान','年度趨勢','Годовые тренды','الاتجاهات السنوية','Yıllık eğilimler'],
    ['百分比必须和样本量一起看','Always read percentages with sample size','Lea los porcentajes junto con la muestra','Toujours lire le pourcentage avec l’échantillon','Leia percentuais junto com a amostra','प्रतिशत को नमूना आकार के साथ देखें','百分比必須和樣本量一起看','Процент нужно оценивать вместе с выборкой','يجب قراءة النسبة مع حجم العينة','Yüzdeyi örneklem büyüklüğüyle birlikte okuyun'],
    ['查看完整说明','View full methodology','Ver metodología completa','Voir la méthodologie complète','Ver metodologia completa','पूरी कार्यप्रणाली देखें','查看完整說明','Полная методика','عرض المنهجية الكاملة','Tam yöntemi görüntüle'],
    ['美国各州移民法院庇护数据','U.S. asylum data by state','Datos de asilo por estado','Données d’asile par État','Dados de asilo por estado','राज्य के अनुसार अमेरिकी शरण डेटा','美國各州移民法院庇護資料','Данные об убежище по штатам','بيانات اللجوء حسب الولاية','Eyalete göre ABD sığınma verileri'],
    ['数据按案件裁决当时的移民法院归州，并按财政年度分别统计。','Cases are assigned to the state of the deciding court and reported separately by fiscal year.','Los casos se asignan al estado del tribunal que decidió y se informan por año fiscal.','Les dossiers sont attribués à l’État du tribunal décisionnaire et ventilés par exercice.','Os casos são atribuídos ao estado do tribunal decisor e separados por ano fiscal.','मामले निर्णय देने वाली अदालत के राज्य और वित्त वर्ष के अनुसार गिने जाते हैं।','資料按案件裁決當時的移民法院歸州，並按財政年度分別統計。','Дела относятся к штату решающего суда и учитываются по финансовым годам.','تُنسب القضايا إلى ولاية المحكمة التي أصدرت القرار وتُعرض حسب السنة المالية.','Davalar karar veren mahkemenin eyaletine ve mali yıla göre raporlanır.'],
    ['正在读取财政年度范围…','Loading fiscal-year range…','Cargando rango del año fiscal…','Chargement de la période fiscale…','Carregando período fiscal…','वित्त वर्ष अवधि लोड हो रही है…','正在讀取財政年度範圍…','Загрузка периода финансового года…','جارٍ تحميل نطاق السنة المالية…','Mali yıl aralığı yükleniyor…'],
    ['筛选州，例如 NY、CA、TX','Filter states, e.g. NY, CA, TX','Filtrar estados, p. ej. NY, CA, TX','Filtrer les États, ex. NY, CA, TX','Filtrar estados, ex.: NY, CA, TX','राज्य फ़िल्टर करें, जैसे NY, CA, TX','篩選州，例如 NY、CA、TX','Фильтр штатов, например NY, CA, TX','تصفية الولايات، مثل NY وCA وTX','Eyaletleri filtrele, örn. NY, CA, TX'],
    ['筛选','Filter','Filtrar','Filtrer','Filtrar','फ़िल्टर','篩選','Фильтр','تصفية','Filtrele'],
    ['州级汇总','State summary','Resumen estatal','Résumé par État','Resumo estadual','राज्य सारांश','州級彙總','Сводка по штатам','ملخص الولاية','Eyalet özeti'],
    ['按庇护裁决量排序','Sorted by asylum decision volume','Ordenado por volumen de decisiones','Trié par volume de décisions','Ordenado por volume de decisões','शरण निर्णय संख्या के अनुसार','按庇護裁決量排序','По объёму решений','مرتّب حسب حجم القرارات','Karar hacmine göre sıralı'],
    ['点击州可继续查看该州法院','Select a state to view its courts','Seleccione un estado para ver sus tribunales','Sélectionnez un État pour voir ses tribunaux','Selecione um estado para ver seus tribunais','अदालतें देखने के लिए राज्य चुनें','點擊州可繼續查看該州法院','Выберите штат, чтобы увидеть его суды','اختر ولاية لعرض محاكمها','Mahkemelerini görmek için eyalet seçin'],
    ['正在读取州级数据…','Loading state data…','Cargando datos estatales…','Chargement des données par État…','Carregando dados estaduais…','राज्य डेटा लोड हो रहा है…','正在讀取州級資料…','Загрузка данных штатов…','جارٍ تحميل بيانات الولايات…','Eyalet verileri yükleniyor…'],
    ['美国移民法院庇护通过率','U.S. immigration court asylum approval rates','Tasas de aprobación de asilo por tribunal','Taux d’approbation de l’asile par tribunal','Taxas de aprovação de asilo por tribunal','अमेरिकी इमिग्रेशन कोर्ट शरण अनुमोदन दर','美國移民法院庇護通過率','Одобрение убежища в иммиграционных судах США','نسب الموافقة على اللجوء في محاكم الهجرة','ABD göçmenlik mahkemesi sığınma onay oranları'],
    ['搜索法院、城市或州，例如 New York','Search court, city, or state, e.g. New York','Buscar tribunal, ciudad o estado, p. ej. New York','Rechercher tribunal, ville ou État, ex. New York','Buscar tribunal, cidade ou estado, ex.: New York','अदालत, शहर या राज्य खोजें, जैसे New York','搜尋法院、城市或州，例如 New York','Искать суд, город или штат, например New York','ابحث عن محكمة أو مدينة أو ولاية، مثل New York','Mahkeme, şehir veya eyalet ara, örn. New York'],
    ['搜索','Search','Buscar','Rechercher','Buscar','खोजें','搜尋','Поиск','بحث','Ara'],
    ['法院汇总','Court summary','Resumen de tribunales','Résumé des tribunaux','Resumo dos tribunais','अदालत सारांश','法院彙總','Сводка судов','ملخص المحاكم','Mahkeme özeti'],
    ['正在读取法院数据…','Loading court data…','Cargando datos judiciales…','Chargement des tribunaux…','Carregando dados dos tribunais…','अदालत डेटा लोड हो रहा है…','正在讀取法院資料…','Загрузка данных судов…','جارٍ تحميل بيانات المحاكم…','Mahkeme verileri yükleniyor…'],
    ['正在读取 EOIR 法官数据…','Loading EOIR judge data…','Cargando datos EOIR del juez…','Chargement des données EOIR du juge…','Carregando dados EOIR do juiz…','EOIR न्यायाधीश डेटा लोड हो रहा है…','正在讀取 EOIR 法官資料…','Загрузка данных судьи EOIR…','جارٍ تحميل بيانات قاضي EOIR…','EOIR hâkim verileri yükleniyor…'],
    ['数据来源：EOIR','Source: EOIR','Fuente: EOIR','Source : EOIR','Fonte: EOIR','स्रोत: EOIR','資料來源：EOIR','Источник: EOIR','المصدر: EOIR','Kaynak: EOIR'],
    ['全部结案中批准占比','Approved share of all outcomes','Porcentaje aprobado de todos los resultados','Part approuvée de tous les résultats','Parcela aprovada de todos os resultados','सभी परिणामों में अनुमोदित हिस्सा','全部結案中批准占比','Доля одобрений среди всех исходов','حصة الموافقات من جميع النتائج','Tüm sonuçlarda onay payı'],
    ['批准 ÷ 全部结案结果','Approved ÷ all outcomes','Aprobadas ÷ todos los resultados','Approuvées ÷ tous les résultats','Aprovados ÷ todos os resultados','अनुमोदित ÷ सभी परिणाम','批准 ÷ 全部結案結果','Одобрено ÷ все исходы','الموافق عليها ÷ جميع النتائج','Onay ÷ tüm sonuçlar'],
    ['批准 / 拒绝','Approved / denied','Aprobadas / denegadas','Approuvées / refusées','Aprovados / negados','अनुमोदित / अस्वीकृत','批准 / 拒絕','Одобрено / отказано','موافق عليها / مرفوضة','Onay / ret'],
    ['仅显示数据库记录','Database records only','Solo registros de la base','Données de la base uniquement','Somente registros da base','केवल डेटाबेस रिकॉर्ड','僅顯示資料庫記錄','Только записи базы','سجلات قاعدة البيانات فقط','Yalnızca veri tabanı kayıtları'],
    ['年度变化','Yearly changes','Cambios anuales','Évolution annuelle','Mudanças anuais','वार्षिक परिवर्तन','年度變化','Изменения по годам','التغيرات السنوية','Yıllık değişimler'],
    ['庇护裁决年度趋势','Yearly asylum decision trend','Tendencia anual de decisiones','Tendance annuelle des décisions','Tendência anual de decisões','वार्षिक शरण निर्णय रुझान','庇護裁決年度趨勢','Годовой тренд решений','الاتجاه السنوي للقرارات','Yıllık sığınma kararı eğilimi'],
    ['申请人来源','Applicant origin','Origen del solicitante','Origine du demandeur','Origem do requerente','आवेदक का मूल देश','申請人來源','Происхождение заявителя','بلد مقدم الطلب','Başvuru sahibinin kökeni'],
    ['按财年和国籍查看庇护裁决','Asylum decisions by fiscal year and nationality','Decisiones por año fiscal y nacionalidad','Décisions par exercice et nationalité','Decisões por ano fiscal e nacionalidade','वित्त वर्ष और राष्ट्रीयता के अनुसार निर्णय','按財年和國籍查看庇護裁決','Решения по финансовому году и гражданству','القرارات حسب السنة المالية والجنسية','Mali yıl ve uyruğa göre kararlar'],
    ['输入中文或英文国籍，例如：古巴、Cuba、中国、China','Enter a nationality, e.g. Cuba, China, India','Ingrese una nacionalidad, p. ej. Cuba, China, India','Saisissez une nationalité, ex. Cuba, Chine, Inde','Digite uma nacionalidade, ex.: Cuba, China, Índia','राष्ट्रीयता लिखें, जैसे Cuba, China, India','輸入中文或英文國籍，例如：古巴、Cuba、中國、China','Введите гражданство, например Cuba, China, India','أدخل الجنسية، مثل Cuba أو China أو India','Uyruk girin, örn. Cuba, China, India'],
    ['每行明确显示财政年度、国籍、有效裁决数和批准率。','Each row shows fiscal year, nationality, valid decisions, and approval rate.','Cada fila muestra año fiscal, nacionalidad, decisiones válidas y tasa de aprobación.','Chaque ligne indique l’exercice, la nationalité, les décisions valides et le taux.','Cada linha mostra ano fiscal, nacionalidade, decisões válidas e taxa.','हर पंक्ति में वित्त वर्ष, राष्ट्रीयता, वैध निर्णय और अनुमोदन दर है।','每行明確顯示財政年度、國籍、有效裁決數和批准率。','В каждой строке указан год, гражданство, решения и доля одобрений.','يعرض كل صف السنة المالية والجنسية والقرارات الصالحة ونسبة الموافقة.','Her satır mali yıl, uyruk, geçerli karar ve onay oranını gösterir.'],
    ['官方任命资料','Official appointment record','Registro oficial de nombramiento','Dossier officiel de nomination','Registro oficial de nomeação','आधिकारिक नियुक्ति रिकॉर्ड','官方任命資料','Официальные сведения о назначении','سجل التعيين الرسمي','Resmî atama kaydı'],
    ['法官背景与任命信息','Judge background and appointment','Antecedentes y nombramiento del juez','Parcours et nomination du juge','Histórico e nomeação do juiz','न्यायाधीश पृष्ठभूमि और नियुक्ति','法官背景與任命資訊','Биография и назначение судьи','خلفية القاضي وتعيينه','Hâkim geçmişi ve ataması'],
    ['任命时间','Appointment date','Fecha de nombramiento','Date de nomination','Data da nomeação','नियुक्ति तिथि','任命時間','Дата назначения','تاريخ التعيين','Atama tarihi'],
    ['任命法院','Appointed court','Tribunal de nombramiento','Tribunal de nomination','Tribunal da nomeação','नियुक्त अदालत','任命法院','Суд назначения','محكمة التعيين','Atandığı mahkeme'],
    ['任命类型','Appointment type','Tipo de nombramiento','Type de nomination','Tipo de nomeação','नियुक्ति प्रकार','任命類型','Тип назначения','نوع التعيين','Atama türü'],
    ['官方履历原文','Official biography','Biografía oficial','Biographie officielle','Biografia oficial','आधिकारिक जीवनी','官方履歷原文','Официальная биография','السيرة الرسمية','Resmî biyografi'],
    ['查看 DOJ/EOIR 官方来源','View official DOJ/EOIR source','Ver fuente oficial DOJ/EOIR','Voir la source officielle DOJ/EOIR','Ver fonte oficial DOJ/EOIR','आधिकारिक DOJ/EOIR स्रोत देखें','查看 DOJ/EOIR 官方來源','Официальный источник DOJ/EOIR','عرض المصدر الرسمي DOJ/EOIR','Resmî DOJ/EOIR kaynağını görüntüle'],
    ['如何理解通过率','How to read approval rates','Cómo interpretar las tasas','Comment lire les taux','Como interpretar as taxas','अनुमोदन दर को कैसे समझें','如何理解通過率','Как понимать долю одобрений','كيفية فهم نسب الموافقة','Onay oranları nasıl okunur'],
    ['查看数据口径与来源说明','View methodology and sources','Ver metodología y fuentes','Voir la méthodologie et les sources','Ver metodologia e fontes','कार्यप्रणाली और स्रोत देखें','查看資料口徑與來源說明','Методика и источники','عرض المنهجية والمصادر','Yöntem ve kaynakları görüntüle'],
    ['唐人日报仅整理公开数据，不提供针对具体案件的法律结论。','Tang Ren Daily organizes public data only and provides no legal conclusion for any individual case.','Tang Ren Daily solo organiza datos públicos y no ofrece conclusiones legales sobre casos individuales.','Tang Ren Daily organise uniquement des données publiques et ne fournit aucune conclusion juridique individuelle.','Tang Ren Daily apenas organiza dados públicos e não fornece conclusão jurídica individual.','Tang Ren Daily केवल सार्वजनिक डेटा व्यवस्थित करता है और किसी मामले पर कानूनी निष्कर्ष नहीं देता।','唐人日報僅整理公開資料，不提供針對具體案件的法律結論。','Tang Ren Daily систематизирует открытые данные и не даёт правовых выводов по отдельным делам.','تنظم صحيفة تانغ رن البيانات العامة فقط ولا تقدم رأيًا قانونيًا لقضية فردية.','Tang Ren Daily yalnızca kamu verilerini düzenler ve tek bir dava için hukuki sonuç sunmaz.'],
    ['语言','Language','Idioma','Langue','Idioma','भाषा','語言','Язык','اللغة','Dil'],
    ['查法官','Find judges','Buscar jueces','Trouver des juges','Buscar juízes','न्यायाधीश खोजें','查法官','Найти судей','البحث عن القضاة','Hâkimleri bul'],
    ['查法院','Find courts','Buscar tribunales','Trouver des tribunaux','Buscar tribunais','अदालतें खोजें','查法院','Найти суды','البحث عن المحاكم','Mahkemeleri bul'],
    ['各州数据','State data','Datos estatales','Données par État','Dados estaduais','राज्य डेटा','各州資料','Данные штатов','بيانات الولايات','Eyalet verileri'],
    ['各国国籍批准率','Nationality approval rates','Tasas por nacionalidad','Taux par nationalité','Taxas por nacionalidade','राष्ट्रीयता अनुमोदन दर','各國國籍批准率','Одобрения по гражданству','نسب الموافقة حسب الجنسية','Uyruğa göre onay oranları'],
    ['纽约','New York','Nueva York','New York','Nova York','न्यूयॉर्क','紐約','Нью-Йорк','نيويورك','New York'],
    ['洛杉矶','Los Angeles','Los Ángeles','Los Angeles','Los Angeles','लॉस एंजेलिस','洛杉磯','Лос-Анджелес','لوس أنجلوس','Los Angeles'],
    ['休斯敦','Houston','Houston','Houston','Houston','ह्यूस्टन','休士頓','Хьюстон','هيوستن','Houston'],
    ['迈阿密','Miami','Miami','Miami','Miami','मियामी','邁阿密','Майами','ميامي','Miami'],
    ['正在读取全部移民法官资料…','Loading all immigration judge profiles…','Cargando perfiles de jueces…','Chargement des profils des juges…','Carregando perfis dos juízes…','सभी न्यायाधीश प्रोफ़ाइल लोड हो रही हैं…','正在讀取全部移民法官資料…','Загрузка профилей судей…','جارٍ تحميل ملفات القضاة…','Hâkim profilleri yükleniyor…'],
    ['数据口径','Methodology','Metodología','Méthodologie','Metodologia','कार्यप्रणाली','資料口徑','Методика','المنهجية','Yöntem'],
    ['搜索全部 227 个已记录国籍，并查看月度、季度与年度真实趋势。','Search all 227 recorded nationalities and view real monthly, quarterly, and yearly trends.','Busque las 227 nacionalidades registradas y vea tendencias mensuales, trimestrales y anuales.','Recherchez les 227 nationalités et consultez les tendances mensuelles, trimestrielles et annuelles.','Pesquise as 227 nacionalidades e veja tendências mensais, trimestrais e anuais.','सभी 227 दर्ज राष्ट्रीयताएँ खोजें और मासिक, तिमाही व वार्षिक रुझान देखें।','搜尋全部 227 個已記錄國籍，並查看月度、季度與年度真實走勢。','Ищите по 227 гражданствам и смотрите месячные, квартальные и годовые тренды.','ابحث في 227 جنسية مسجلة واعرض الاتجاهات الشهرية والفصلية والسنوية.','Kayıtlı 227 uyruğu arayın; aylık, üç aylık ve yıllık eğilimleri görün.'],
    ['查看全球国籍数据','View global nationality data','Ver datos mundiales de nacionalidad','Voir les données mondiales par nationalité','Ver dados globais de nacionalidade','वैश्विक राष्ट्रीयता डेटा देखें','查看全球國籍資料','Мировые данные по гражданству','عرض بيانات الجنسيات العالمية','Küresel uyruk verilerini görüntüle'],
    ['先查询法官，再查看每年裁决量和批准率变化。','Find a judge first, then review yearly decision volume and approval-rate changes.','Busque un juez y revise los cambios anuales de decisiones y aprobación.','Trouvez un juge puis consultez l’évolution annuelle des décisions et du taux.','Encontre um juiz e veja as mudanças anuais de decisões e aprovação.','पहले न्यायाधीश खोजें, फिर वार्षिक निर्णय और अनुमोदन दर में बदलाव देखें।','先查詢法官，再查看每年裁決量和批准率變化。','Сначала найдите судью, затем изучите годовые решения и долю одобрений.','ابحث عن القاضي أولًا ثم راجع تغير القرارات ونسبة الموافقة سنويًا.','Önce hâkimi bulun, sonra yıllık karar ve onay oranı değişimini inceleyin.'],
    ['查询法官','Find a judge','Buscar un juez','Trouver un juge','Buscar um juiz','न्यायाधीश खोजें','查詢法官','Найти судью','البحث عن قاضٍ','Hâkim ara'],
    ['裁决批准率按“批准 ÷（批准 + 拒绝）”计算，撤回、未裁决等程序性结果不计入分母。小样本数据会被抑制或提示，避免只看一个百分比造成误解。','Decision approval rate is approved ÷ (approved + denied). Withdrawn, unadjudicated, and other procedural outcomes are excluded. Small samples are suppressed or flagged.','La tasa es aprobadas ÷ (aprobadas + denegadas). Se excluyen retiros y resultados procesales; las muestras pequeñas se ocultan o advierten.','Le taux est approuvées ÷ (approuvées + refusées). Les retraits et résultats procéduraux sont exclus ; les petits échantillons sont signalés.','A taxa é aprovados ÷ (aprovados + negados). Retiradas e resultados processuais são excluídos; amostras pequenas são sinalizadas.','दर अनुमोदित ÷ (अनुमोदित + अस्वीकृत) है। वापस लिए गए और प्रक्रियात्मक परिणाम बाहर रहते हैं; छोटे नमूने छिपाए या चिह्नित किए जाते हैं।','裁決批准率按「批准 ÷（批准 + 拒絕）」計算，撤回、未裁決等程序結果不計入分母；小樣本會被抑制或提示。','Доля одобрений: одобрено ÷ (одобрено + отказано). Процедурные исходы исключены; малые выборки скрываются или помечаются.','نسبة الموافقة = الموافق عليها ÷ (الموافق عليها + المرفوضة). تُستبعد النتائج الإجرائية وتُخفى العينات الصغيرة أو يُنبه إليها.','Onay oranı = onay ÷ (onay + ret). Usule ilişkin sonuçlar hariç tutulur; küçük örnekler gizlenir veya uyarılır.'],
    ['与唐人日报共用 EOIR 数据库 · 持续更新','Shared EOIR database with Tang Ren Daily · continuously updated','Base EOIR compartida con Tang Ren Daily · actualización continua','Base EOIR partagée avec Tang Ren Daily · mise à jour continue','Base EOIR compartilhada com Tang Ren Daily · atualização contínua','Tang Ren Daily के साथ साझा EOIR डेटाबेस · लगातार अपडेट','與唐人日報共用 EOIR 資料庫 · 持續更新','Общая база EOIR с Tang Ren Daily · постоянно обновляется','قاعدة EOIR مشتركة مع صحيفة تانغ رن · تحديث مستمر','Tang Ren Daily ile ortak EOIR veri tabanı · sürekli güncellenir'],
    ['立足美国 · 服务华人','Based in America · serving Chinese communities','En EE. UU. · al servicio de la comunidad china','Aux États-Unis · au service de la communauté chinoise','Nos EUA · servindo a comunidade chinesa','अमेरिका में · चीनी समुदाय की सेवा','立足美國 · 服務華人','В США · для китайской общины','في أمريكا · لخدمة الجالية الصينية','ABD’de · Çin toplumuna hizmet'],
    ['返回法官查询','Back to judge search','Volver a jueces','Retour à la recherche de juges','Voltar à busca de juízes','न्यायाधीश खोज पर लौटें','返回法官查詢','Назад к поиску судей','العودة إلى بحث القضاة','Hâkim aramasına dön'],
    ['返回法院查询','Back to court search','Volver a tribunales','Retour à la recherche de tribunaux','Voltar à busca de tribunais','अदालत खोज पर लौटें','返回法院查詢','Назад к поиску судов','العودة إلى بحث المحاكم','Mahkeme aramasına dön'],
    ['按案件作出裁决时所在法院归属州；可切换财政年度核对案件量。','Cases are assigned to the state of the court at decision time; switch fiscal years to compare volume.','Los casos se asignan al estado del tribunal al decidirse; cambie de año fiscal para comparar volumen.','Les dossiers sont rattachés à l’État du tribunal au moment de la décision ; changez d’exercice pour comparer.','Os casos são atribuídos ao estado do tribunal na decisão; altere o ano fiscal para comparar o volume.','मामले निर्णय के समय अदालत के राज्य से जुड़े हैं; संख्या तुलना के लिए वित्त वर्ष बदलें।','案件按裁決時所在法院歸州；可切換財年核對案件量。','Дела отнесены к штату суда на момент решения; переключайте годы для сравнения.','تُنسب القضايا إلى ولاية المحكمة وقت القرار؛ بدّل السنة المالية للمقارنة.','Davalar karar anındaki mahkemenin eyaletine atanır; hacmi karşılaştırmak için mali yılı değiştirin.'],
    ['裁决批准率＝批准 ÷（批准 + 拒绝）','Decision approval rate = approved ÷ (approved + denied)','Tasa = aprobadas ÷ (aprobadas + denegadas)','Taux = approuvées ÷ (approuvées + refusées)','Taxa = aprovados ÷ (aprovados + negados)','दर = अनुमोदित ÷ (अनुमोदित + अस्वीकृत)','裁決批准率＝批准 ÷（批准 + 拒絕）','Доля = одобрено ÷ (одобрено + отказано)','النسبة = الموافق عليها ÷ (الموافق عليها + المرفوضة)','Oran = onay ÷ (onay + ret)'],
    ['法院法官','Court judges','Jueces del tribunal','Juges du tribunal','Juízes do tribunal','अदालत के न्यायाधीश','法院法官','Судьи суда','قضاة المحكمة','Mahkeme hâkimleri'],
    ['该法院移民法官','Immigration judges at this court','Jueces de inmigración de este tribunal','Juges de l’immigration de ce tribunal','Juízes de imigração deste tribunal','इस अदालत के इमिग्रेशन जज','該法院移民法官','Иммиграционные судьи этого суда','قضاة الهجرة في هذه المحكمة','Bu mahkemedeki göçmenlik hâkimleri'],
    ['点击法官查看年度与国籍数据','Select a judge to view yearly and nationality data','Seleccione un juez para ver datos anuales y por nacionalidad','Sélectionnez un juge pour les données annuelles et par nationalité','Selecione um juiz para ver dados anuais e por nacionalidade','वार्षिक और राष्ट्रीयता डेटा के लिए न्यायाधीश चुनें','點擊法官查看年度與國籍資料','Выберите судью для данных по годам и гражданству','اختر قاضيًا لعرض البيانات السنوية وحسب الجنسية','Yıllık ve uyruk verileri için hâkimi seçin'],
    ['选择国籍数据财政年度','Select nationality fiscal year','Elegir año fiscal de nacionalidad','Choisir l’exercice des nationalités','Selecionar ano fiscal de nacionalidade','राष्ट्रीयता डेटा का वित्त वर्ष चुनें','選擇國籍資料財政年度','Выберите год данных по гражданству','اختر السنة المالية لبيانات الجنسية','Uyruk verisi mali yılını seçin'],
    ['页面只展示可核验的官方任命与履历资料。未发现离任或被辞退记录，不等于确认仍在任；只有获得可靠来源时才会标注相关人事变动。','This page shows only verifiable official appointment and biography records. No departure record does not confirm current service; personnel changes are labeled only with reliable sources.','La página solo muestra nombramientos y biografías oficiales verificables. La ausencia de una salida no confirma servicio actual; los cambios se indican con fuentes fiables.','La page n’affiche que des nominations et biographies officielles vérifiables. L’absence de départ ne confirme pas le maintien en poste ; les changements exigent une source fiable.','A página mostra apenas nomeações e biografias oficiais verificáveis. A ausência de saída não confirma atuação atual; mudanças exigem fonte confiável.','यह पृष्ठ केवल सत्यापन योग्य आधिकारिक नियुक्ति और जीवनी दिखाता है। प्रस्थान रिकॉर्ड न होना वर्तमान सेवा की पुष्टि नहीं करता; बदलाव विश्वसनीय स्रोत पर ही दिखते हैं।','頁面只展示可核驗的官方任命與履歷。未發現離任記錄不等於確認仍在任；人事變動僅在有可靠來源時標註。','Показаны только проверяемые официальные назначения и биографии. Отсутствие записи об уходе не подтверждает текущую службу; изменения отмечаются лишь по надёжным источникам.','تعرض الصفحة سجلات التعيين والسيرة الرسمية القابلة للتحقق فقط. عدم وجود سجل مغادرة لا يؤكد استمرار الخدمة؛ ولا تُذكر التغييرات إلا بمصدر موثوق.','Yalnızca doğrulanabilir resmî atama ve özgeçmiş kayıtları gösterilir. Ayrılış kaydının olmaması görevde olduğunu kanıtlamaz; değişiklikler güvenilir kaynakla belirtilir.'],
    ['美国移民法官与法院数据','U.S. immigration judge and court data','Datos de jueces y tribunales de inmigración de EE. UU.','Données des juges et tribunaux de l’immigration aux États-Unis','Dados de juízes e tribunais de imigração dos EUA','अमेरिकी इमिग्रेशन जज और अदालत डेटा','美國移民法官與法院資料','Данные иммиграционных судей и судов США','بيانات قضاة ومحاكم الهجرة الأمريكية','ABD göçmenlik hâkimi ve mahkeme verileri'],
    ['移民法官数据导航','Immigration judge data navigation','Navegación de datos de jueces','Navigation des données des j…8926 tokens truncated… trend data for 2024–2026','No hay tendencias anuales para 2024–2026','Aucune tendance annuelle pour 2024–2026','Sem tendências anuais para 2024–2026','2024–2026 के लिए वार्षिक रुझान डेटा नहीं','2024–2026 暫無年度趨勢資料','Нет годового тренда за 2024–2026','لا توجد بيانات اتجاه سنوي للأعوام 2024–2026','2024–2026 için yıllık eğilim verisi yok'],
    ['按批准 ÷（批准 + 拒绝）计算；蓝色“其他”单独展示，包括可识别的暂缓/CAT保护、取消递解或调整身份、自愿离境、撤回/终止/驳回及行政结案，不进入批准率分母。','is approved ÷ (approved + denied). Blue “Other” is shown separately and includes identifiable withholding/CAT protection, cancellation or adjustment, voluntary departure, withdrawal, termination, dismissal, and administrative closure; it is excluded from the rate denominator.','es aprobadas ÷ (aprobadas + denegadas). “Otros” se muestra por separado e incluye protección CAT, cancelación o ajuste, salida voluntaria, retiro, terminación, desestimación y cierre administrativo; no entra en el denominador.','correspond à approuvées ÷ (approuvées + refusées). « Autres » est séparé et comprend CAT, annulation ou ajustement, départ volontaire, retrait, clôture et classement administratif ; il est exclu du dénominateur.','é aprovados ÷ (aprovados + negados). “Outros” aparece separadamente e inclui proteção CAT, cancelamento ou ajuste, saída voluntária, retirada, encerramento, arquivamento e fechamento administrativo; fica fora do denominador.','अनुमोदित ÷ (अनुमोदित + अस्वीकृत) है। नीला “अन्य” अलग दिखता है और CAT संरक्षण, रद्दीकरण/समायोजन, स्वैच्छिक प्रस्थान, वापसी, समाप्ति, खारिज और प्रशासनिक बंद शामिल करता है; यह दर के हर में नहीं आता।','按批准 ÷（批准 + 拒絕）計算；藍色「其他」單獨展示，包括可識別的暫緩/CAT 保護、取消遞解或調整身分、自願離境、撤回、終止、駁回及行政結案，不進入批准率分母。','равна одобрено ÷ (одобрено + отказано). «Другое» показано отдельно и включает CAT-защиту, отмену или изменение статуса, добровольный выезд, отзыв, прекращение, отклонение и административное закрытие; оно не входит в знаменатель.','هي الموافق عليها ÷ (الموافق عليها + المرفوضة). تظهر «أخرى» منفصلة وتشمل حماية CAT والإلغاء أو تعديل الوضع والمغادرة الطوعية والسحب والإنهاء والرفض والإغلاق الإداري؛ ولا تدخل المقام.','onay ÷ (onay + ret) olarak hesaplanır. “Diğer” ayrı gösterilir; CAT koruması, iptal/statü ayarı, gönüllü ayrılış, geri çekme, sonlandırma, ret ve idari kapatma dahildir ve paydada yer almaz.'],
    ['则把批准、拒绝和其他全部作为分母。','uses approved, denied, and other outcomes in the denominator.','usa aprobadas, denegadas y otros resultados en el denominador.','utilise les approbations, refus et autres résultats au dénominateur.','usa aprovados, negados e outros resultados no denominador.','अनुमोदित, अस्वीकृत और अन्य सभी परिणामों को हर में रखता है।','則把批准、拒絕和其他全部作為分母。','использует в знаменателе одобрения, отказы и другие исходы.','تستخدم الموافق عليها والمرفوضة والنتائج الأخرى في المقام.','paydada onay, ret ve diğer sonuçların tümünü kullanır.'],
    ['样本量较小时，百分比可能因少量案件发生较大波动。页面会对不足 50 件和不足 200 件的裁决样本进行提示。','With small samples, a few cases can move the percentage sharply. The page flags samples below 50 and below 200 decisions.','Con muestras pequeñas, pocos casos pueden mover mucho el porcentaje. La página advierte muestras inferiores a 50 y 200 decisiones.','Avec un petit échantillon, quelques dossiers peuvent fortement modifier le pourcentage. La page signale les échantillons sous 50 et sous 200 décisions.','Com amostras pequenas, poucos casos podem alterar muito a porcentagem. A página sinaliza amostras abaixo de 50 e de 200 decisões.','छोटे नमूने में कुछ मामले प्रतिशत को काफी बदल सकते हैं। पृष्ठ 50 और 200 से कम निर्णय वाले नमूनों को चिह्नित करता है।','樣本量較小時，少量案件可能造成百分比大幅波動。頁面會提示不足 50 件及不足 200 件的裁決樣本。','В малой выборке несколько дел могут сильно изменить процент. Страница помечает выборки менее 50 и менее 200 решений.','في العينات الصغيرة قد تغير قضايا قليلة النسبة كثيرًا. تنبه الصفحة إلى العينات الأقل من 50 والأقل من 200 قرار.','Küçük örneklerde birkaç dava yüzdede büyük değişim yaratabilir. Sayfa 50 ve 200 kararın altındaki örnekleri işaretler.']
    ,['返回查询','Back to search','Volver a la búsqueda','Retour à la recherche','Voltar à busca','खोज पर लौटें','返回查詢','Назад к поиску','العودة إلى البحث','Aramaya dön']
    ,['法官年度批准、拒绝与其他裁决对比图','Annual comparison of a judge’s approved, denied, and other decisions','Comparación anual de decisiones aprobadas, denegadas y otras del juez','Comparaison annuelle des décisions approuvées, refusées et autres du juge','Comparação anual das decisões aprovadas, negadas e outras do juiz','न्यायाधीश के वार्षिक अनुमोदित, अस्वीकृत और अन्य निर्णयों की तुलना','法官年度批准、拒絕與其他裁決比較圖','Годовое сравнение одобренных, отклонённых и других решений судьи','مقارنة سنوية لقرارات القاضي الموافق عليها والمرفوضة والأخرى','Hâkimin yıllık onay, ret ve diğer karar karşılaştırması']
    ,['横向年度裁决对比图','Horizontal annual decision comparison chart','Gráfico horizontal de comparación anual de decisiones','Graphique horizontal de comparaison annuelle des décisions','Gráfico horizontal de comparação anual de decisões','वार्षिक निर्णयों का क्षैतिज तुलना चार्ट','橫向年度裁決比較圖','Горизонтальная диаграмма сравнения решений по годам','مخطط أفقي لمقارنة القرارات السنوية','Yatay yıllık karar karşılaştırma grafiği']
    ,['包括撤案、A10、十年绿卡、暂缓递解、自愿递解等其他裁决','Includes withdrawal, A10, ten-year green card, withholding of removal, voluntary departure, and other outcomes','Incluye retiro, A10, residencia de diez años, suspensión de expulsión, salida voluntaria y otros resultados','Comprend le retrait, A10, la carte verte de dix ans, la suspension de l’expulsion, le départ volontaire et d’autres résultats','Inclui retirada, A10, green card de dez anos, suspensão de remoção, saída voluntária e outros resultados','वापसी, A10, दस-वर्षीय ग्रीन कार्ड, निष्कासन स्थगन, स्वैच्छिक प्रस्थान और अन्य परिणाम शामिल हैं','包括撤案、A10、十年綠卡、暫緩遞解、自願離境等其他裁決','Включает отзыв, A10, десятилетнюю грин-карту, приостановление выдворения, добровольный выезд и другие исходы','يشمل السحب وA10 والبطاقة الخضراء لعشر سنوات ووقف الترحيل والمغادرة الطوعية ونتائج أخرى','Geri çekme, A10, on yıllık yeşil kart, sınır dışı etmeyi durdurma, gönüllü ayrılış ve diğer sonuçları içerir']
    ,['暂时无法读取该法院资料','This court’s information is temporarily unavailable','La información de este tribunal no está disponible temporalmente','Les informations de ce tribunal sont temporairement indisponibles','As informações deste tribunal estão temporariamente indisponíveis','इस अदालत की जानकारी अभी उपलब्ध नहीं है','暫時無法讀取該法院資料','Данные этого суда временно недоступны','معلومات هذه المحكمة غير متاحة مؤقتًا','Bu mahkemenin bilgileri geçici olarak kullanılamıyor']
    ,['请返回法院查询页稍后重试。','Return to the court search and try again later.','Vuelva a la búsqueda de tribunales e inténtelo más tarde.','Revenez à la recherche des tribunaux et réessayez plus tard.','Volte à busca de tribunais e tente novamente mais tarde.','अदालत खोज पर लौटें और बाद में फिर प्रयास करें।','請返回法院查詢頁稍後重試。','Вернитесь к поиску судов и повторите попытку позже.','عُد إلى البحث عن المحاكم وحاول مرة أخرى لاحقًا.','Mahkeme aramasına dönüp daha sonra tekrar deneyin.']
    ,['庇护通过率','Asylum approval rate','Tasa de aprobación de asilo','Taux d’approbation de l’asile','Taxa de aprovação de asilo','शरण अनुमोदन दर','庇護批准率','Доля одобрения убежища','نسبة الموافقة على اللجوء','Sığınma onay oranı']
    ,['美国各州移民法院庇护通过率｜唐人日报','U.S. immigration court asylum approval rates by state | AsylumJudge.com','Tasas de aprobación de asilo por estado | AsylumJudge.com','Taux d’approbation de l’asile par État | AsylumJudge.com','Taxas de aprovação de asilo por estado | AsylumJudge.com','राज्य के अनुसार अमेरिकी इमिग्रेशन कोर्ट शरण अनुमोदन दर | AsylumJudge.com','美國各州移民法院庇護批准率｜AsylumJudge.com','Одобрение убежища в иммиграционных судах по штатам | AsylumJudge.com','نسب الموافقة على اللجوء في محاكم الهجرة حسب الولاية | AsylumJudge.com','Eyalete göre göçmenlik mahkemesi sığınma onay oranları | AsylumJudge.com']
    ,['美国移民法院庇护通过率查询｜唐人日报','Search U.S. immigration court asylum approval rates | AsylumJudge.com','Buscar tasas de aprobación de asilo en tribunales de inmigración | AsylumJudge.com','Rechercher les taux d’approbation de l’asile par tribunal | AsylumJudge.com','Consultar taxas de aprovação de asilo por tribunal | AsylumJudge.com','अमेरिकी इमिग्रेशन कोर्ट शरण अनुमोदन दर खोजें | AsylumJudge.com','查詢美國移民法院庇護批准率｜AsylumJudge.com','Поиск одобрений убежища в иммиграционных судах США | AsylumJudge.com','البحث في نسب الموافقة على اللجوء بمحاكم الهجرة الأمريكية | AsylumJudge.com','ABD göçmenlik mahkemesi sığınma onay oranlarını ara | AsylumJudge.com']
    ,['移民法官通过率数据口径｜唐人日报','Immigration judge approval-rate methodology | AsylumJudge.com','Metodología de las tasas de aprobación de jueces | AsylumJudge.com','Méthodologie des taux d’approbation des juges | AsylumJudge.com','Metodologia das taxas de aprovação de juízes | AsylumJudge.com','इमिग्रेशन जज अनुमोदन दर की कार्यप्रणाली | AsylumJudge.com','移民法官批准率資料口徑｜AsylumJudge.com','Методика расчёта одобрений иммиграционных судей | AsylumJudge.com','منهجية نسب موافقة قضاة الهجرة | AsylumJudge.com','Göçmenlik hâkimi onay oranı yöntemi | AsylumJudge.com']
    ,['移民法院庇护裁决详情｜唐人日报','Immigration court asylum decision details | AsylumJudge.com','Detalles de decisiones de asilo del tribunal | AsylumJudge.com','Détails des décisions d’asile du tribunal | AsylumJudge.com','Detalhes das decisões de asilo do tribunal | AsylumJudge.com','इमिग्रेशन कोर्ट शरण निर्णय विवरण | AsylumJudge.com','移民法院庇護裁決詳情｜AsylumJudge.com','Данные решений об убежище в суде | AsylumJudge.com','تفاصيل قرارات اللجوء في محكمة الهجرة | AsylumJudge.com','Göçmenlik mahkemesi sığınma kararı ayrıntıları | AsylumJudge.com']
    ,['移民法官庇护裁决详情｜唐人日报','Immigration judge asylum decision details | AsylumJudge.com','Detalles de decisiones de asilo del juez | AsylumJudge.com','Détails des décisions d’asile du juge | AsylumJudge.com','Detalhes das decisões de asilo do juiz | AsylumJudge.com','इमिग्रेशन जज शरण निर्णय विवरण | AsylumJudge.com','移民法官庇護裁決詳情｜AsylumJudge.com','Данные решений судьи об убежище | AsylumJudge.com','تفاصيل قرارات اللجوء لقاضي الهجرة | AsylumJudge.com','Göçmenlik hâkimi sığınma kararı ayrıntıları | AsylumJudge.com']
    ,['移民法官通过率｜美国移民法官与法院庇护数据查询','Immigration Judge Approval Rates | U.S. judge and court asylum data','Tasas de aprobación de jueces | Datos de asilo de jueces y tribunales de EE. UU.','Taux d’approbation des juges | Données d’asile des juges et tribunaux américains','Taxas de aprovação de juízes | Dados de asilo de juízes e tribunais dos EUA','इमिग्रेशन जज अनुमोदन दर | अमेरिकी जज और अदालत शरण डेटा','移民法官批准率｜美國移民法官與法院庇護資料查詢','Одобрения иммиграционных судей | Данные судей и судов США','نسب موافقة قضاة الهجرة | بيانات اللجوء للقضاة والمحاكم الأمريكية','Göçmenlik hâkimi onay oranları | ABD hâkim ve mahkeme sığınma verileri']
    ,['裁决结果图例','Decision outcome legend','Leyenda de resultados de decisiones','Légende des résultats des décisions','Legenda dos resultados das decisões','निर्णय परिणाम संकेत','裁決結果圖例','Легенда исходов решений','مفتاح نتائج القرارات','Karar sonucu açıklaması']
    ,['暂时无法读取该法官资料','This judge’s information is temporarily unavailable','La información de este juez no está disponible temporalmente','Les informations de ce juge sont temporairement indisponibles','As informações deste juiz estão temporariamente indisponíveis','इस न्यायाधीश की जानकारी अभी उपलब्ध नहीं है','暫時無法讀取該法官資料','Данные этого судьи временно недоступны','معلومات هذا القاضي غير متاحة مؤقتًا','Bu hâkimin bilgileri geçici olarak kullanılamıyor']
    ,['请返回查询页稍后重试。','Return to search and try again later.','Vuelva a la búsqueda e inténtelo más tarde.','Revenez à la recherche et réessayez plus tard.','Volte à busca e tente novamente mais tarde.','खोज पर लौटें और बाद में फिर प्रयास करें।','請返回查詢頁稍後重試。','Вернитесь к поиску и повторите попытку позже.','عُد إلى البحث وحاول مرة أخرى لاحقًا.','Aramaya dönüp daha sonra tekrar deneyin.']
    ,['城市列表暂时无法读取','City list temporarily unavailable','La lista de ciudades no está disponible temporalmente','La liste des villes est temporairement indisponible','Lista de cidades temporariamente indisponível','शहरों की सूची अभी उपलब्ध नहीं है','城市列表暫時無法讀取','Список городов временно недоступен','قائمة المدن غير متاحة مؤقتًا','Şehir listesi geçici olarak kullanılamıyor']
    ,['州级数据暂时无法读取','State-level data temporarily unavailable','Los datos estatales no están disponibles temporalmente','Les données par État sont temporairement indisponibles','Dados estaduais temporariamente indisponíveis','राज्य-स्तरीय डेटा अभी उपलब्ध नहीं है','州級資料暫時無法讀取','Данные штата временно недоступны','بيانات الولاية غير متاحة مؤقتًا','Eyalet verileri geçici olarak kullanılamıyor']
    ,['州级数据库暂时无法读取','State database temporarily unavailable','La base estatal no está disponible temporalmente','La base de l’État est temporairement indisponible','Banco de dados estadual temporariamente indisponível','राज्य डेटाबेस अभी उपलब्ध नहीं है','州級資料庫暫時無法讀取','База штата временно недоступна','قاعدة بيانات الولاية غير متاحة مؤقتًا','Eyalet veri tabanı geçici olarak kullanılamıyor']
    ,['法院数据库暂时无法读取','Court database temporarily unavailable','La base de tribunales no está disponible temporalmente','La base des tribunaux est temporairement indisponible','Banco de dados dos tribunais temporariamente indisponível','अदालत डेटाबेस अभी उपलब्ध नहीं है','法院資料庫暫時無法讀取','База судов временно недоступна','قاعدة بيانات المحاكم غير متاحة مؤقتًا','Mahkeme veri tabanı geçici olarak kullanılamıyor']
    ,['数据库接口暂时无法读取','Database service temporarily unavailable','El servicio de la base no está disponible temporalmente','Le service de base de données est temporairement indisponible','Serviço do banco de dados temporariamente indisponível','डेटाबेस सेवा अभी उपलब्ध नहीं है','資料庫介面暫時無法讀取','Сервис базы временно недоступен','خدمة قاعدة البيانات غير متاحة مؤقتًا','Veri tabanı hizmeti geçici olarak kullanılamıyor']
    ,['请稍后重试。','Please try again later.','Inténtelo de nuevo más tarde.','Veuillez réessayer plus tard.','Tente novamente mais tarde.','कृपया बाद में फिर प्रयास करें।','請稍後重試。','Повторите попытку позже.','يرجى المحاولة مرة أخرى لاحقًا.','Lütfen daha sonra tekrar deneyin.']
    ,['最新庇护知识暂时无法读取，请稍后刷新。','The latest asylum knowledge is temporarily unavailable. Refresh later.','La información más reciente sobre asilo no está disponible. Actualice más tarde.','Les dernières informations sur l’asile sont temporairement indisponibles. Actualisez plus tard.','As informações mais recentes sobre asilo estão indisponíveis. Atualize mais tarde.','नवीनतम शरण जानकारी अभी उपलब्ध नहीं है। बाद में रीफ़्रेश करें।','最新庇護知識暫時無法讀取，請稍後重新整理。','Свежие материалы об убежище временно недоступны. Обновите страницу позже.','أحدث معلومات اللجوء غير متاحة مؤقتًا. حدّث الصفحة لاحقًا.','En güncel sığınma bilgileri geçici olarak kullanılamıyor. Daha sonra yenileyin.']
    ,['全部法官资料暂时无法读取，请稍后刷新。','All judge profiles are temporarily unavailable. Refresh later.','Los perfiles de jueces no están disponibles. Actualice más tarde.','Les profils des juges sont temporairement indisponibles. Actualisez plus tard.','Os perfis dos juízes estão indisponíveis. Atualize mais tarde.','सभी न्यायाधीश प्रोफ़ाइल अभी उपलब्ध नहीं हैं। बाद में रीफ़्रेश करें।','全部法官資料暫時無法讀取，請稍後重新整理。','Профили судей временно недоступны. Обновите страницу позже.','ملفات القضاة غير متاحة مؤقتًا. حدّث الصفحة لاحقًا.','Hâkim profilleri geçici olarak kullanılamıyor. Daha sonra yenileyin.']
  ];

  const indexes = { en: 1, es: 2, fr: 3, 'pt-BR': 4, hi: 5, 'zh-Hant': 6, ru: 7, ar: 8, tr: 9 };
  const maps = Object.fromEntries(Object.entries(indexes).map(([code, index]) => [code, new Map(rows.map((row) => [row[0], row[index]]))]));
  const stateEnglish = { AZ:'Arizona',CA:'California',CO:'Colorado',CT:'Connecticut',FL:'Florida',GA:'Georgia',GU:'Guam',HI:'Hawaii',IL:'Illinois',IN:'Indiana',LA:'Louisiana',MA:'Massachusetts',MD:'Maryland',MI:'Michigan',MN:'Minnesota',MO:'Missouri',MP:'Northern Mariana Islands',NC:'North Carolina',NE:'Nebraska',NJ:'New Jersey',NM:'New Mexico',NV:'Nevada',NY:'New York',OH:'Ohio',OR:'Oregon',PA:'Pennsylvania',PR:'Puerto Rico',TN:'Tennessee',TX:'Texas',UT:'Utah',VA:'Virginia',WA:'Washington' };
  const stateSimplified = { AZ:'亚利桑那州',CA:'加州',CO:'科罗拉多州',CT:'康涅狄格州',FL:'佛州',GA:'乔治亚州',GU:'关岛',HI:'夏威夷州',IL:'伊利诺伊州',IN:'印第安纳州',LA:'路易斯安那州',MA:'马萨诸塞州',MD:'马里兰州',MI:'密歇根州',MN:'明尼苏达州',MO:'密苏里州',MP:'北马里亚纳群岛',NC:'北卡罗来纳州',NE:'内布拉斯加州',NJ:'新泽西州',NM:'新墨西哥州',NV:'内华达州',NY:'纽约州',OH:'俄亥俄州',OR:'俄勒冈州',PA:'宾州',PR:'波多黎各',TN:'田纳西州',TX:'德州',UT:'犹他州',VA:'弗吉尼亚州',WA:'华盛顿州' };
  const stateTraditional = { AZ:'亞利桑那州',CA:'加州',CO:'科羅拉多州',CT:'康乃狄克州',FL:'佛州',GA:'喬治亞州',GU:'關島',HI:'夏威夷州',IL:'伊利諾州',IN:'印第安納州',LA:'路易斯安那州',MA:'麻薩諸塞州',MD:'馬里蘭州',MI:'密西根州',MN:'明尼蘇達州',MO:'密蘇里州',MP:'北馬里亞納群島',NC:'北卡羅來納州',NE:'內布拉斯加州',NJ:'新澤西州',NM:'新墨西哥州',NV:'內華達州',NY:'紐約州',OH:'俄亥俄州',OR:'俄勒岡州',PA:'賓州',PR:'波多黎各',TN:'田納西州',TX:'德州',UT:'猶他州',VA:'維吉尼亞州',WA:'華盛頓州' };
  const stateCodeByChinese = Object.fromEntries(Object.entries(stateSimplified).map(([code, name]) => [name, code]));
  const templates = {
    en: { trend:'{name} decision approval-rate trend', period:'FY {year} (through {date})', complete:'FY {year} (complete fiscal year)', updated:'Updated {date}', valid:'{count} valid decisions', sample:'{count} valid-decision sample', all:'{count} judges', match:'{shown} of {total} judges', range:'Data period {start} to {end}', hidden:'Fewer than 50; rate hidden', sorted:'FY {year} · sorted by asylum decision volume', stateSearch:'Search courts or cities in {state}', found:'“{query}” found {count} judges', courtLink:'{state} · view courts →' },
    es: { trend:'Tendencia de aprobación — {name}', period:'FY {year} (hasta {date})', complete:'FY {year} (año completo)', updated:'Actualizado {date}', valid:'{count} decisiones válidas', sample:'Muestra de {count} decisiones válidas', all:'{count} jueces', match:'{shown} de {total} jueces', range:'Período {start} a {end}', hidden:'Menos de 50; tasa oculta', sorted:'FY {year} · ordenado por decisiones', stateSearch:'Buscar tribunales o ciudades en {state}', found:'“{query}”: {count} jueces', courtLink:'{state} · ver tribunales →' },
    fr: { trend:'Tendance d’approbation — {name}', period:'FY {year} (au {date})', complete:'FY {year} (exercice complet)', updated:'Mis à jour {date}', valid:'{count} décisions valides', sample:'Échantillon de {count} décisions valides', all:'{count} juges', match:'{shown} sur {total} juges', range:'Période du {start} au {end}', hidden:'Moins de 50 ; taux masqué', sorted:'FY {year} · trié par décisions', stateSearch:'Rechercher tribunaux ou villes en {state}', found:'« {query} » : {count} juges', courtLink:'{state} · voir les tribunaux →' },
    'pt-BR': { trend:'Tendência de aprovação — {name}', period:'FY {year} (até {date})', complete:'FY {year} (ano completo)', updated:'Atualizado em {date}', valid:'{count} decisões válidas', sample:'Amostra de {count} decisões válidas', all:'{count} juízes', match:'{shown} de {total} juízes', range:'Período de {start} a {end}', hidden:'Menos de 50; taxa oculta', sorted:'FY {year} · por volume de decisões', stateSearch:'Buscar tribunais ou cidades em {state}', found:'“{query}”: {count} juízes', courtLink:'{state} · ver tribunais →' },
    hi: { trend:'{name} अनुमोदन दर रुझान', period:'FY {year} ({date} तक)', complete:'FY {year} (पूर्ण वित्त वर्ष)', updated:'अपडेट {date}', valid:'{count} वैध निर्णय', sample:'{count} वैध निर्णयों का नमूना', all:'{count} न्यायाधीश', match:'{total} में से {shown} न्यायाधीश', range:'डेटा अवधि {start} से {end}', hidden:'50 से कम; दर छिपी', sorted:'FY {year} · निर्णय संख्या के अनुसार', stateSearch:'{state} में अदालत या शहर खोजें', found:'“{query}” से {count} न्यायाधीश मिले', courtLink:'{state} · अदालतें देखें →' },
    'zh-Hant': { trend:'{name}裁決批准率走勢', period:'FY {year}（截至 {date}）', complete:'FY {year}（完整財年）', updated:'更新至 {date}', valid:'{count} 件有效裁決', sample:'{count} 件有效裁決樣本', all:'共 {count} 位法官', match:'匹配 {shown} 位／全部 {total} 位', range:'資料期 {start} 至 {end}', hidden:'少於 50 件，不顯示', sorted:'FY {year} · 按庇護裁決量排序', stateSearch:'在 {state} 州內搜尋法院或城市', found:'「{query}」找到 {count} 位法官', courtLink:'{state} · 查看該州法院 →' },
    ru: { trend:'Тренд одобрений — {name}', period:'FY {year} (по {date})', complete:'FY {year} (полный год)', updated:'Обновлено {date}', valid:'{count} действительных решений', sample:'Выборка: {count} решений', all:'{count} судей', match:'{shown} из {total} судей', range:'Период {start}–{end}', hidden:'Менее 50; доля скрыта', sorted:'FY {year} · по объёму решений', stateSearch:'Искать суды или города в {state}', found:'«{query}»: найдено {count} судей', courtLink:'{state} · суды →' },
    ar: { trend:'اتجاه الموافقة — {name}', period:'FY {year} (حتى {date})', complete:'FY {year} (سنة كاملة)', updated:'محدّث {date}', valid:'{count} قرار صالح', sample:'عينة من {count} قرار صالح', all:'{count} قاضيًا', match:'{shown} من {total} قاضيًا', range:'الفترة من {start} إلى {end}', hidden:'أقل من 50؛ النسبة مخفية', sorted:'FY {year} · حسب حجم القرارات', stateSearch:'ابحث عن محكمة أو مدينة في {state}', found:'“{query}”: تم العثور على {count} قاضيًا', courtLink:'{state} · عرض المحاكم ←' },
    tr: { trend:'{name} onay oranı eğilimi', period:'FY {year} ({date} itibarıyla)', complete:'FY {year} (tam mali yıl)', updated:'Güncelleme {date}', valid:'{count} geçerli karar', sample:'{count} geçerli karar örneklemi', all:'{count} hâkim', match:'{total} hâkimden {shown}', range:'Veri dönemi {start}–{end}', hidden:'50’den az; oran gizli', sorted:'FY {year} · karar hacmine göre', stateSearch:'{state} içinde mahkeme veya şehir ara', found:'“{query}”: {count} hâkim bulundu', courtLink:'{state} · mahkemeleri görüntüle →' }
  };
  const methodologyCopy = {
    en: { title:'Immigration judge asylum approval-rate methodology', note:'Important: This database is informational, not legal advice. Always read a rate together with its sample size and data period.', sections:[['1. Official source','The baseline is public U.S. Department of Justice EOIR data. Original outcome categories are preserved; not every non-approval is treated as a denial.'],['2. Two approval measures','Decision approval rate = grants ÷ (grants + denials). Approved share of all outcomes = grants ÷ all recorded outcomes. The interface identifies which measure is shown.'],['3. Judge-level data','Judge totals, fiscal-year results, and nationality results retain their source and coverage dates.'],['4. Nationality data','Judge-by-nationality results appear only when the source supports that cross-tabulation; national or court totals are never inferred for a judge.'],['5. Small samples','Small samples can mislead. The interface prioritizes counts and hides or flags rates below the display threshold.'],['6. Updates','Imports are repeatable and update the same judge, fiscal year, and nationality rather than double-counting records.'],['7. Status','Only records that pass field and source validation enter the public search. No invented placeholder data is used.']] },
    es: { title:'Metodología de las tasas de aprobación de asilo', note:'Importante: esta base es informativa y no constituye asesoría legal. Lea siempre la tasa junto con la muestra y el período.', sections:[['1. Fuente oficial','La base son datos públicos de EOIR del Departamento de Justicia. Se conservan las categorías originales; no todo resultado sin aprobación se considera denegación.'],['2. Dos medidas','Tasa de decisión = aprobadas ÷ (aprobadas + denegadas). Porcentaje de todos los resultados = aprobadas ÷ todos los resultados registrados. La interfaz indica la medida.'],['3. Datos por juez','Los totales, resultados fiscales y por nacionalidad conservan su fuente y fechas de cobertura.'],['4. Nacionalidad','Los datos juez × nacionalidad solo aparecen cuando la fuente permite ese cruce; nunca se infieren datos nacionales o del tribunal para un juez.'],['5. Muestras pequeñas','Las muestras pequeñas pueden inducir a error. Se priorizan los conteos y se ocultan o advierten tasas bajo el umbral.'],['6. Actualizaciones','Las importaciones actualizan el mismo juez, año fiscal y nacionalidad sin duplicar registros.'],['7. Estado','Solo se publican registros que superan la validación de campos y fuentes. No se usan datos ficticios.']] },
    fr: { title:'Méthodologie des taux d’approbation de l’asile', note:'Important : cette base est informative et ne constitue pas un avis juridique. Lisez toujours le taux avec l’échantillon et la période.', sections:[['1. Source officielle','La référence est constituée des données publiques EOIR du ministère de la Justice. Les catégories d’origine sont conservées ; tout résultat non approuvé n’est pas un refus.'],['2. Deux mesures','Taux de décision = approbations ÷ (approbations + refus). Part de tous les résultats = approbations ÷ tous les résultats enregistrés. L’interface précise la mesure.'],['3. Données par juge','Les totaux, résultats par exercice et par nationalité conservent leur source et leurs dates de couverture.'],['4. Nationalité','Le croisement juge × nationalité n’apparaît que si la source le permet ; les totaux nationaux ou du tribunal ne sont jamais imputés à un juge.'],['5. Petits échantillons','Ils peuvent induire en erreur. Les nombres sont prioritaires et les taux sous le seuil sont masqués ou signalés.'],['6. Mises à jour','Les imports mettent à jour le même juge, exercice et nationalité sans doubler les enregistrements.'],['7. État','Seuls les enregistrements validés sont publiés. Aucune donnée fictive n’est utilisée.']] },
    'pt-BR': { title:'Metodologia das taxas de aprovação de asilo', note:'Importante: esta base é informativa e não constitui aconselhamento jurídico. Leia a taxa junto com a amostra e o período.', sections:[['1. Fonte oficial','A referência são dados públicos do EOIR do Departamento de Justiça. As categorias originais são preservadas; nem todo resultado sem aprovação é negativa.'],['2. Duas medidas','Taxa de decisão = aprovados ÷ (aprovados + negados). Participação em todos os resultados = aprovados ÷ todos os resultados registrados. A interface identifica a medida.'],['3. Dados por juiz','Totais, resultados por ano fiscal e por nacionalidade mantêm fonte e datas de cobertura.'],['4. Nacionalidade','O cruzamento juiz × nacionalidade só aparece quando a fonte o permite; totais nacionais ou do tribunal nunca são atribuídos a um juiz.'],['5. Amostras pequenas','Podem enganar. Os números têm prioridade e taxas abaixo do limite são ocultadas ou sinalizadas.'],['6. Atualizações','As importações atualizam o mesmo juiz, ano fiscal e nacionalidade sem duplicar registros.'],['7. Estado','Somente registros validados são publicados. Não há dados fictícios.']] },
    hi: { title:'इमिग्रेशन जज शरण अनुमोदन दर की कार्यप्रणाली', note:'महत्वपूर्ण: यह डेटाबेस केवल जानकारी के लिए है, कानूनी सलाह नहीं। दर को नमूना आकार और डेटा अवधि के साथ पढ़ें।', sections:[['1. आधिकारिक स्रोत','आधार अमेरिकी न्याय विभाग के सार्वजनिक EOIR डेटा हैं। मूल परिणाम श्रेणियाँ सुरक्षित रहती हैं; हर गैर-अनुमोदन को अस्वीकृति नहीं माना जाता।'],['2. दो माप','निर्णय दर = अनुमोदित ÷ (अनुमोदित + अस्वीकृत)। सभी परिणामों में हिस्सा = अनुमोदित ÷ सभी दर्ज परिणाम। इंटरफ़ेस बताता है कि कौन सा माप दिख रहा है।'],['3. न्यायाधीश डेटा','कुल, वित्त-वर्ष और राष्ट्रीयता परिणाम अपने स्रोत और कवरेज तिथियाँ रखते हैं।'],['4. राष्ट्रीयता','जज × राष्ट्रीयता डेटा तभी दिखता है जब स्रोत इसका समर्थन करे; राष्ट्रीय या अदालत कुल किसी जज पर अनुमानित नहीं किए जाते।'],['5. छोटे नमूने','छोटे नमूने भ्रामक हो सकते हैं। संख्या को प्राथमिकता मिलती है और सीमा से नीचे दर छिपाई या चिह्नित की जाती है।'],['6. अपडेट','आयात उसी जज, वित्त वर्ष और राष्ट्रीयता को अपडेट करता है; रिकॉर्ड दोहरे नहीं गिने जाते।'],['7. स्थिति','केवल सत्यापित रिकॉर्ड सार्वजनिक खोज में आते हैं। काल्पनिक डेटा नहीं है।']] },
    'zh-Hant': { title:'移民法官庇護批准率資料口徑', note:'重要：本資料庫僅供資訊查詢，不構成法律意見。閱讀批准率時必須同時查看樣本量與資料期間。', sections:[['1. 官方來源','基礎口徑以美國司法部 EOIR 公開資料為準。保留原始結果分類，不把所有「非批准」一律視為拒絕。'],['2. 兩種批准率','裁決批准率＝批准 ÷（批准＋拒絕）；全部結案批准占比＝批准 ÷ 全部記錄結果。介面會清楚標示所用口徑。'],['3. 法官級資料','法官總數、財年結果與國籍結果均保留來源及資料涵蓋日期。'],['4. 國籍資料','只有來源支援「法官 × 國籍」交叉維度時才展示；不會把全國或法院總數推算到單一法官。'],['5. 小樣本保護','小樣本容易造成誤解。介面優先展示案件數，並隱藏或提示低於門檻的比例。'],['6. 資料更新','匯入會更新同一法官、財年與國籍的記錄，不重複累加。'],['7. 資料狀態','只有通過欄位與來源驗證的記錄才進入公開查詢，不使用虛構占位資料。']] },
    ru: { title:'Методика расчёта одобрений убежища', note:'Важно: база носит справочный характер и не является юридической консультацией. Долю следует читать вместе с выборкой и периодом.', sections:[['1. Официальный источник','Основа — открытые данные EOIR Министерства юстиции США. Исходные категории сохраняются; не каждый неодобренный исход считается отказом.'],['2. Два показателя','Доля решений = одобрено ÷ (одобрено + отказано). Доля всех исходов = одобрено ÷ все записанные исходы. Интерфейс указывает показатель.'],['3. Данные по судьям','Итоги, финансовые годы и гражданства сохраняют источник и даты охвата.'],['4. Гражданство','Связка судья × гражданство показывается лишь при наличии в источнике; национальные и судебные итоги не приписываются судье.'],['5. Малые выборки','Они могут вводить в заблуждение. Приоритет имеют числа, а доли ниже порога скрываются или помечаются.'],['6. Обновления','Импорт обновляет того же судью, год и гражданство без двойного счёта.'],['7. Статус','Публикуются только проверенные записи. Выдуманные данные не используются.']] },
    ar: { title:'منهجية نسب الموافقة على اللجوء', note:'مهم: قاعدة البيانات للمعلومات وليست نصيحة قانونية. اقرأ النسبة مع حجم العينة وفترة البيانات.', sections:[['1. المصدر الرسمي','الأساس هو بيانات EOIR العامة التابعة لوزارة العدل الأمريكية. تُحفظ فئات النتائج الأصلية؛ وليست كل نتيجة غير موافق عليها رفضًا.'],['2. مقياسان','نسبة القرار = الموافق عليها ÷ (الموافق عليها + المرفوضة). حصة جميع النتائج = الموافق عليها ÷ كل النتائج المسجلة. توضح الواجهة المقياس.'],['3. بيانات القضاة','تحتفظ الإجماليات ونتائج السنوات المالية والجنسيات بالمصدر وتواريخ التغطية.'],['4. الجنسية','يظهر تقاطع القاضي × الجنسية فقط إذا دعمه المصدر؛ ولا تُنسب إجماليات وطنية أو قضائية إلى قاضٍ.'],['5. العينات الصغيرة','قد تكون مضللة. تُعطى الأولوية للأعداد وتُخفى النسب تحت الحد أو يُنبه إليها.'],['6. التحديثات','يحدّث الاستيراد القاضي والسنة والجنسية نفسها من دون عد مزدوج.'],['7. الحالة','لا تدخل البحث العام إلا السجلات التي اجتازت التحقق. لا تُستخدم بيانات مختلقة.']] },
    tr: { title:'Sığınma onay oranı yöntemi', note:'Önemli: Bu veri tabanı yalnızca bilgi amaçlıdır, hukuki tavsiye değildir. Oranı örneklem ve veri dönemiyle birlikte okuyun.', sections:[['1. Resmî kaynak','Temel, ABD Adalet Bakanlığı EOIR açık verileridir. Özgün sonuç kategorileri korunur; her onaylanmayan sonuç ret sayılmaz.'],['2. İki ölçüm','Karar oranı = onay ÷ (onay + ret). Tüm sonuçlardaki pay = onay ÷ kayıtlı tüm sonuçlar. Arayüz kullanılan ölçümü belirtir.'],['3. Hâkim verileri','Toplamlar, mali yıl ve uyruk sonuçları kaynak ve kapsama tarihlerini korur.'],['4. Uyruk','Hâkim × uyruk yalnızca kaynak destekliyorsa gösterilir; ulusal veya mahkeme toplamları bir hâkime atfedilmez.'],['5. Küçük örnekler','Yanıltıcı olabilir. Sayılara öncelik verilir; eşik altındaki oranlar gizlenir veya işaretlenir.'],['6. Güncellemeler','İçe aktarma aynı hâkim, mali yıl ve uyruğu günceller; kayıtları iki kez saymaz.'],['7. Durum','Yalnızca doğrulanmış kayıtlar kamu aramasına girer. Uydurma veri kullanılmaz.']] }
  };
  const detailTemplates = {
    en: { insufficient:'Only {count} valid decisions; fewer than 50, so the rate is hidden.', small:'{count} valid decisions meet the display threshold, but the rate may move sharply with a few cases.', normal:'{count} valid decisions; historical statistics do not represent an individual case.', compactSmall:'{count} valid decisions meet the threshold, but may be volatile.', dates:'Record dates {start} to {end}', source:'Source: {source} · Data range {start} to {end}', nationalityPeriod:'FY {year}: {start} to {end} · Each row shows fiscal year, nationality, case count, and actual outcomes.' },
    es: { insufficient:'Solo {count} decisiones válidas; menos de 50, por lo que se oculta la tasa.', small:'{count} decisiones válidas superan el umbral, pero la tasa puede variar con pocos casos.', normal:'{count} decisiones válidas; las estadísticas históricas no representan un caso individual.', compactSmall:'{count} decisiones válidas superan el umbral, pero pueden ser volátiles.', dates:'Fechas de los registros: {start} a {end}', source:'Fuente: {source} · Período {start} a {end}', nationalityPeriod:'FY {year}: {start} a {end} · Cada fila muestra año fiscal, nacionalidad, casos y resultados reales.' },
    fr: { insufficient:'Seulement {count} décisions valides ; moins de 50, le taux est donc masqué.', small:'{count} décisions valides atteignent le seuil, mais quelques dossiers peuvent fortement modifier le taux.', normal:'{count} décisions valides ; les statistiques historiques ne représentent pas un dossier individuel.', compactSmall:'{count} décisions valides atteignent le seuil, mais peuvent être volatiles.', dates:'Dates des dossiers : {start} à {end}', source:'Source : {source} · Période du {start} au {end}', nationalityPeriod:'FY {year} : du {start} au {end} · Chaque ligne indique l’exercice, la nationalité, les dossiers et les résultats réels.' },
    'pt-BR': { insufficient:'Apenas {count} decisões válidas; menos de 50, portanto a taxa fica oculta.', small:'{count} decisões válidas atingem o limite, mas poucos casos podem alterar bastante a taxa.', normal:'{count} decisões válidas; estatísticas históricas não representam um caso individual.', compactSmall:'{count} decisões válidas atingem o limite, mas podem oscilar.', dates:'Datas dos registros: {start} a {end}', source:'Fonte: {source} · Período de {start} a {end}', nationalityPeriod:'FY {year}: {start} a {end} · Cada linha mostra ano fiscal, nacionalidade, casos e resultados reais.' },
    hi: { insufficient:'केवल {count} वैध निर्णय; 50 से कम होने के कारण दर छिपी है।', small:'{count} वैध निर्णय सीमा पूरी करते हैं, लेकिन कुछ मामले दर को काफी बदल सकते हैं।', normal:'{count} वैध निर्णय; ऐतिहासिक आँकड़े किसी एक मामले का प्रतिनिधित्व नहीं करते।', compactSmall:'{count} वैध निर्णय सीमा पूरी करते हैं, पर दर अस्थिर हो सकती है।', dates:'रिकॉर्ड तिथियाँ {start} से {end}', source:'स्रोत: {source} · डेटा अवधि {start} से {end}', nationalityPeriod:'FY {year}: {start} से {end} · हर पंक्ति में वित्त वर्ष, राष्ट्रीयता, मामले और वास्तविक परिणाम हैं।' },
    'zh-Hant': { insufficient:'僅 {count} 件有效裁決，少於 50 件，因此不展示批准率。', small:'{count} 件有效裁決已達展示標準，但少量案件仍可能造成較大波動。', normal:'{count} 件有效裁決；歷史統計不代表個案結果。', compactSmall:'{count} 件有效裁決已達展示標準，但波動可能較大。', dates:'記錄日期 {start} 至 {end}', source:'資料來源：{source} · 資料範圍 {start} 至 {end}', nationalityPeriod:'FY {year}：{start} 至 {end} · 每行顯示財年、國籍、案件數和真實裁決結果。' },
    ru: { insufficient:'Только {count} действительных решений; менее 50, поэтому доля скрыта.', small:'{count} решений достигают порога, но несколько дел могут заметно изменить долю.', normal:'{count} действительных решений; историческая статистика не описывает отдельное дело.', compactSmall:'{count} решений достигают порога, но показатель может быть нестабилен.', dates:'Даты записей: {start}–{end}', source:'Источник: {source} · Период {start}–{end}', nationalityPeriod:'FY {year}: {start}–{end} · В каждой строке указаны год, гражданство, число дел и реальные исходы.' },
    ar: { insufficient:'فقط {count} قرار صالح؛ أقل من 50، لذا تُخفى النسبة.', small:'بلغت {count} قرارات صالحة حد العرض، لكن قد تتغير النسبة كثيرًا مع قضايا قليلة.', normal:'{count} قرار صالح؛ الإحصاءات التاريخية لا تمثل قضية فردية.', compactSmall:'بلغت {count} قرارات صالحة الحد، لكنها قد تكون متقلبة.', dates:'تواريخ السجلات من {start} إلى {end}', source:'المصدر: {source} · الفترة من {start} إلى {end}', nationalityPeriod:'FY {year}: من {start} إلى {end} · يعرض كل صف السنة المالية والجنسية وعدد القضايا والنتائج الفعلية.' },
    tr: { insufficient:'Yalnızca {count} geçerli karar; 50’den az olduğu için oran gizlidir.', small:'{count} geçerli karar eşiği karşılıyor, ancak birkaç dava oranı önemli ölçüde değiştirebilir.', normal:'{count} geçerli karar; tarihsel istatistikler tek bir davayı temsil etmez.', compactSmall:'{count} geçerli karar eşiği karşılıyor, ancak oynak olabilir.', dates:'Kayıt tarihleri {start}–{end}', source:'Kaynak: {source} · Veri dönemi {start}–{end}', nationalityPeriod:'FY {year}: {start}–{end} · Her satır mali yıl, uyruk, dava sayısı ve gerçek sonuçları gösterir.' }
  };
  const interpolate = (value, vars) => String(value).replace(/\{(\w+)\}/g, (_, key) => vars[key] ?? '');
  const profileTitles = {
    en:'{name} asylum approval rate | AsylumJudge.com', es:'Tasa de aprobación de asilo de {name} | AsylumJudge.com', fr:'Taux d’approbation de l’asile — {name} | AsylumJudge.com', 'pt-BR':'Taxa de aprovação de asilo de {name} | AsylumJudge.com', hi:'{name} शरण अनुमोदन दर | AsylumJudge.com', 'zh-Hant':'{name} 庇護批准率｜AsylumJudge.com', ru:'Одобрение убежища — {name} | AsylumJudge.com', ar:'نسبة الموافقة على اللجوء — {name} | AsylumJudge.com', tr:'{name} sığınma onay oranı | AsylumJudge.com'
  };
  const translateDynamic = (source) => {
    if (locale === 'zh-Hans') return source;
    const tpl = templates[locale] || templates.en;
    const detail = detailTemplates[locale] || detailTemplates.en;
    let match;
    if ((match = source.match(/^(.+?) 庇护通过率｜(?:唐人日报|移民法官通过率)$/))) return interpolate(profileTitles[locale] || profileTitles.en, { name: match[1] });
    if ((match = source.match(/^(.+)裁决批准率走势$/))) {
      const code = stateCodeByChinese[match[1]];
      const name = code ? (locale === 'zh-Hant' ? stateTraditional[code] : stateEnglish[code]) : match[1];
      return interpolate(tpl.trend, { name });
    }
    if ((match = source.match(/^FY (\d+)（截至 (.+)）$/))) return interpolate(tpl.period, { year: match[1], date: match[2] });
    if ((match = source.match(/^FY (\d+) 财年至今（截至 (.+)）$/))) return interpolate(tpl.period, { year: match[1], date: match[2] });
    if ((match = source.match(/^FY (\d+)（完整财年）$/))) return interpolate(tpl.complete, { year: match[1] });
    if ((match = source.match(/^FY (\d+) 完整财政年度（.+）$/))) return interpolate(tpl.complete, { year: match[1] });
    if ((match = source.match(/^更新至 (.+)$/))) return interpolate(tpl.updated, { date: match[1] });
    if ((match = source.match(/^(.+?) 件有效裁决样本$/))) return interpolate(tpl.sample, { count: match[1] });
    if ((match = source.match(/^(.+?) 件有效裁决$/))) return interpolate(tpl.valid, { count: match[1] });
    if ((match = source.match(/^共 (.+?) 位法官$/))) return interpolate(tpl.all, { count: match[1] });
    if ((match = source.match(/^匹配 (.+?) 位／全部 (.+?) 位$/))) return interpolate(tpl.match, { shown: match[1], total: match[2] });
    if ((match = source.match(/^数据期 (.+) 至 (.+)$/))) return interpolate(tpl.range, { start: match[1], end: match[2] });
    if (/^少于 50 件，不显示$/.test(source)) return tpl.hidden;
    if (/^少于\s*50\s*件，不显示$/.test(source)) return tpl.hidden;
    if ((match = source.match(/^FY (\d+) · 按庇护裁决量排序$/))) return interpolate(tpl.sorted, { year: match[1] });
    if ((match = source.match(/^在 ([A-Z]{2}) 州内搜索法院或城市$/))) return interpolate(tpl.stateSearch, { state: stateEnglish[match[1]] || match[1] });
    if ((match = source.match(/^“(.+)” 找到 (.+?) 位法官$/))) return interpolate(tpl.found, { query: match[1], count: match[2] });
    if ((match = source.match(/^([A-Z]{2}) · 查看该州法院 →$/))) return interpolate(tpl.courtLink, { state: stateEnglish[match[1]] || match[1] });
    if ((match = source.match(/^(.+)（([A-Z]{2})）$/)) && stateEnglish[match[2]]) return `${stateEnglish[match[2]]} (${match[2]})`;
    if ((match = source.match(/^仅 (.+?) 件有效裁决，少于 50 件，因此不展示通过率。$/))) return interpolate(detail.insufficient, { count: match[1] });
    if ((match = source.match(/^(.+?) 件有效裁决，已达到展示标准；数量仍不大，百分比可能随少量案件变化。$/))) return interpolate(detail.small, { count: match[1] });
    if ((match = source.match(/^(.+?) 件有效裁决；历史统计不代表个案结果。$/))) return interpolate(detail.normal, { count: match[1] });
    if ((match = source.match(/^仅 (.+?) 件有效裁决，少于 50 件，不显示通过率$/))) return interpolate(detail.insufficient, { count: match[1] });
    if ((match = source.match(/^(.+?) 件有效裁决，已达到展示标准，但波动可能较大$/))) return interpolate(detail.compactSmall, { count: match[1] });
    if ((match = source.match(/^记录日期 (.+?) 至 (.+)$/))) return interpolate(detail.dates, { start: match[1], end: match[2] });
    if ((match = source.match(/^数据来源：(.+?) · 数据范围 (.+?) 至 (.+)$/))) return interpolate(detail.source, { source: match[1], start: match[2], end: match[3] });
    if ((match = source.match(/^FY (\d+)：(.+?)-10-01 至 (.+?) · 每行显示财年、国籍、案件数和真实裁决结果。$/))) return interpolate(detail.nationalityPeriod, { year: match[1], start: `${match[2]}-10-01`, end: match[3] });
    let translated = source;
    const tokenMap = maps[locale] || maps.en;
    [...tokenMap.entries()].sort((a, b) => b[0].length - a[0].length).forEach(([from, to]) => {
      if (from.length > 18 || !translated.includes(from)) return;
      if (from === '任命') translated = translated.split(from).join(locale === 'zh-Hant' ? to : ` ${to}`);
      else if (from === '件') translated = translated.split(from).join(locale === 'zh-Hant' ? to : ` ${to}`);
      else if (from === '结案') translated = translated.split(from).join(locale === 'zh-Hant' ? to : `${to} `);
      else translated = translated.split(from).join(to);
    });
    return translated;
  };
  const translate = (source) => {
    const clean = String(source || '').trim();
    if (!clean || locale === 'zh-Hans') return clean;
    const direct = maps[locale]?.get(clean) || maps.en.get(clean);
    if (direct) return direct;
    const arrow = clean.match(/^(.*?)(\s*[→←↗])$/);
    if (arrow) {
      const translatedBase = maps[locale]?.get(arrow[1]) || maps.en.get(arrow[1]) || translateDynamic(arrow[1]);
      if (translatedBase !== arrow[1]) return `${translatedBase}${arrow[2]}`;
    }
    return translateDynamic(clean);
  };
  const translateTextNode = (node) => {
    const raw = node.nodeValue || '';
    const clean = raw.trim();
    if (!clean) return;
    const next = translate(clean);
    if (next !== clean) node.nodeValue = `${raw.match(/^\s*/)?.[0] || ''}${next}${raw.match(/\s*$/)?.[0] || ''}`;
  };
  const translateElement = (element) => {
    if (!element || element.nodeType !== 1 || element.closest?.('script,style')) return;
    const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
    const textNodes = [];
    while (walker.nextNode()) textNodes.push(walker.currentNode);
    textNodes.forEach(translateTextNode);
    const attributeNodes = [element, ...(element.querySelectorAll?.('[placeholder],[aria-label],[title]') || [])];
    attributeNodes.forEach((node) => {
      for (const attr of ['placeholder', 'aria-label', 'title']) {
        const value = node.getAttribute(attr);
        if (!value) continue;
        const next = translate(value);
        if (next !== value.trim()) node.setAttribute(attr, next);
      }
    });
  };
  const renderMethodology = () => {
    const main = document.querySelector('main.method');
    const copy = methodologyCopy[locale];
    if (!main || !copy || main.dataset.locale === locale) return;
    main.dataset.locale = locale;
    main.innerHTML = `<div class="eyebrow">EOIR · DATA METHODOLOGY</div><h1>${copy.title}</h1><p class="note">${copy.note}</p>${copy.sections.map(([heading, body]) => `<h2>${heading}</h2><p>${body}</p>`).join('')}`;
    document.title = `${copy.title} | AsylumJudge.com`;
  };
  const apply = () => {
    document.documentElement.lang = locale;
    document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr';
    const translatedTitle = translate(document.title);
    if (translatedTitle !== document.title) document.title = translatedTitle;
    renderMethodology();
    translateElement(document.body);
    document.querySelectorAll('#language-select,#site-language-select').forEach((select) => { select.value = locale; });
  };
  const setLocale = (next, options = {}) => {
    const normalized = normalize(next);
    try { localStorage.setItem('asylumjudge-language', normalized); } catch {}
    const url = new URL(location.href);
    if (options.updateUrl === false) {
      locale = normalized;
      apply();
      return;
    }
    const standalone = /^(?:www\.)?asylumjudge\.com$|^(?:.+--)?asylumjudge\.netlify\.app$/i.test(location.hostname);
    if (standalone) {
      url.searchParams.delete('lang');
      location.href = `${pathForLocale(url.pathname, normalized)}${url.search}${url.hash}`;
      return;
    }
    url.searchParams.set('lang', normalized);
    location.href = `${url.pathname}${url.search}${url.hash}`;
  };
  const formatNumber = (value) => Number(value || 0).toLocaleString(locale);
  const stateName = (code, fallback = '') => {
    const normalized = String(code || '').toUpperCase();
    if (locale === 'zh-Hans') return stateSimplified[normalized] || fallback || code;
    if (locale === 'zh-Hant') return stateTraditional[normalized] || fallback || code;
    return stateEnglish[normalized] || fallback || code;
  };
  window.AsylumI18n = { get locale() { return locale; }, supported: locales, t: (key, vars) => interpolate(translate(key), vars), translate, setLocale, formatNumber, stateName, dictionarySize: rows.length };
  const observer = new MutationObserver((records) => records.forEach((record) => record.addedNodes.forEach((node) => {
    if (node.nodeType === 3) translateTextNode(node);
    else if (node.nodeType === 1) translateElement(node);
  })));
  apply();
  observer.observe(document.body, { childList: true, subtree: true });
  const title = document.querySelector('title');
  if (title) new MutationObserver(() => {
    const next = translate(document.title);
    if (next !== document.title) document.title = next;
  }).observe(title, { childList: true });
})();
