const URL="https://fwiznbpsqkfgkvyznebz.supabase.co",KEY="sb_publishable_hSmKJghvQoJKg0m5loDQ2g_f1gu8qak";
const db=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=s=>document.querySelector(s);const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function isAdmin(user){const {data}=await db.from("admin_users").select("role,is_active").eq("user_id",user.id).eq("is_active",true).maybeSingle();return data&&["owner","admin"].includes(String(data.role).toLowerCase())}
async function enter(user){if(!(await isAdmin(user))){await db.auth.signOut();$("#ex-login-msg").textContent="账号没有管理员权限";return}$("#ex-login").classList.add("hidden");$("#ex-admin").classList.remove("hidden");$("#ex-user").textContent=user.email;loadPosts();}
$("#ex-login-form").addEventListener("submit",async e=>{e.preventDefault();$("#ex-login-msg").textContent="登录中...";const {data,error}=await db.auth.signInWithPassword({email:$("#ex-email").value,password:$("#ex-password").value});if(error){$("#ex-login-msg").textContent=error.message;return}enter(data.user)});
$("#ex-logout").onclick=async()=>{await db.auth.signOut();location.reload()};
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));$("#posts-tab").classList.toggle("hidden",b.dataset.tab!=="posts");$("#comments-tab").classList.toggle("hidden",b.dataset.tab!=="comments");if(b.dataset.tab==="comments")loadComments()});
const fmt=v=>v?new Date(v).toLocaleString("zh-CN"):"";
async function loadPosts(){let q=db.from("exposure_posts").select("*").order("created_at",{ascending:false}).limit(200);const f=$("#post-status-filter").value;if(f)q=q.eq("status",f);const {data,error}=await q;if(error){$("#ex-posts-body").innerHTML=`<tr><td colspan=5>${esc(error.message)}</td></tr>`;return}$("#ex-posts-body").innerHTML=(data||[]).map(p=>`<tr><td><b>${esc(p.title)}</b><br><small>${esc(p.target_name||"")} · ${esc(p.location||"")}</small></td><td>${esc(p.author_name||"匿名")}<br><small>${esc(p.author_contact||"未留联系方式")}</small></td><td><span class="status status-${esc(p.status)}">${esc(p.status)}</span></td><td>${fmt(p.created_at)}</td><td><div class="ex-actions"><button onclick="setPost('${p.id}','published')">发布</button><button onclick="setPost('${p.id}','disputed')">争议</button><button onclick="setPost('${p.id}','resolved')">解决</button><button onclick="setPost('${p.id}','hidden')">隐藏</button><button class="danger" onclick="setPost('${p.id}','removed')">撤稿</button><a href="/exposure-post.html?id=${p.id}" target="_blank">查看</a></div></td></tr>`).join("")||`<tr><td colspan=5>暂无数据</td></tr>`}
window.setPost=async(id,status)=>{const {error}=await db.from("exposure_posts").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)alert(error.message);else loadPosts()};
async function loadComments(){const {data,error}=await db.from("exposure_comments").select("*").order("created_at",{ascending:false}).limit(300);if(error){$("#ex-comments-body").innerHTML=`<tr><td colspan=5>${esc(error.message)}</td></tr>`;return}$("#ex-comments-body").innerHTML=(data||[]).map(c=>`<tr><td>${esc(c.body)}</td><td>${esc(c.nickname)}<br><small>${esc(c.email||"")}</small></td><td><span class="status status-${esc(c.status)}">${esc(c.status)}</span></td><td>${fmt(c.created_at)}</td><td><div class="ex-actions"><button onclick="setComment('${c.id}','published')">显示</button><button onclick="setComment('${c.id}','hidden')">隐藏</button><button class="danger" onclick="setComment('${c.id}','removed')">删除</button></div></td></tr>`).join("")||`<tr><td colspan=5>暂无评论</td></tr>`}
window.setComment=async(id,status)=>{const {error}=await db.from("exposure_comments").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)alert(error.message);else loadComments()};
$("#refresh-posts").onclick=loadPosts;$("#refresh-comments").onclick=loadComments;$("#post-status-filter").onchange=loadPosts;
db.auth.getSession().then(({data})=>{if(data.session?.user)enter(data.session.user)});
