(()=>{"use strict";
const $=id=>document.getElementById(id);let state=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(method="GET",body){const token=await window.getAdminAccessToken?.();if(!token)throw new Error("后台登录已失效");const endpoint=typeof method==="string"&&method.startsWith("GET?")?"/.netlify/functions/property-admin?"+method.slice(4):"/.netlify/functions/property-admin";if(method.startsWith("GET?"))method="GET";const r=await fetch(endpoint,{method,headers:{Authorization:"Bearer "+token,...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"请求失败（"+r.status+"）");return d}
const badge=s=>'<span class="property-badge property-'+esc(s)+'">'+esc(s)+"</span>";
function rows(items,type){return items.map(x=>'<tr><td><b>'+esc(x.title||x.display_name||x.claimant_name||x.contact_name||"—")+'</b><small>'+esc(x.address||x.email||x.claimant_email||x.contact_email||"")+'</small></td><td>'+esc(x.listing_type||x.license_number||x.relationship||x.message||"—")+'</td><td>'+badge(x.status)+'</td><td>'+esc(x.id)+'</td><td><select data-property-type="'+type+'" data-property-id="'+x.id+'"><option value="">审核操作</option>'+options(type)+'</select><button type="button" onclick="viewPropertyFiles(\''+type+'\',\''+x.id+'\')">查看材料</button></td></tr>').join("")||'<tr><td colspan="5">暂无记录</td></tr>'}
function options(t){const m={listing:[["needs_evidence","补充证明"],["approved","审核通过"],["published","发布"],["rejected","拒绝"],["withdrawn","撤回"]],agent:[["verified","认证"],["rejected","拒绝"],["suspended","暂停"]],claim:[["approved","批准"],["needs_evidence","补充证明"],["rejected","拒绝"]],lead:[["contacted","已联系"],["closed","关闭"],["spam","垃圾"]]};return(m[t]||[]).map(x=>'<option value="'+x[0]+'">'+x[1]+"</option>").join("")}
function render(){const c=state.counts;$("property-counts").innerHTML=[["房源总数",c.listings],["待审房源",c.pendingListings],["待审经纪",c.pendingAgents],["待审认领",c.pendingClaims],["新线索",c.newLeads]].map(x=>"<article><strong>"+x[1]+"</strong><span>"+x[0]+"</span></article>").join("");$("property-listings-body").innerHTML=rows(state.listings,"listing");$("property-agents-body").innerHTML=rows(state.agents,"agent");$("property-claims-body").innerHTML=rows(state.claims,"claim");$("property-leads-body").innerHTML=rows(state.leads,"lead");document.querySelectorAll("[data-property-type]").forEach(s=>{s.onchange=()=>changeStatus(s);if(s.dataset.propertyType==="lead"){const b=document.createElement("button");b.type="button";b.textContent="分配经纪";b.onclick=()=>assignLead(s.dataset.propertyId);s.parentElement.appendChild(b)}})}
async function load(){const m=$("property-message");m.textContent="正在读取房产后台…";try{state=await api();render();m.textContent="已刷新。房产证明文件保持私有，不生成公开地址。"}catch(e){m.textContent=e.message}}
async function changeStatus(s){if(!s.value)return;const note=prompt("审核备注（可以留空）","")||"";const publish=s.dataset.propertyType==="listing"&&s.value==="published";if(publish&&!confirm("确认资料、授权和证明均已核验，并立即发布该房源？")){s.value="";return}try{await api("POST",{action:"set_status",entity_type:s.dataset.propertyType,entity_id:s.dataset.propertyId,status:s.value,review_note:note,confirm_publish:publish});await load()}catch(e){alert(e.message)}}
const file64=file=>new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(String(r.result).split(",")[1]);r.onerror=no;r.readAsDataURL(file)});
async function upload(type,id,file,category){if(file.size>4194304)throw new Error(file.name+" 超过4MB，请压缩后上传");return api("POST",{action:"upload_file",entity_type:type,entity_id:id,category,name:file.name,mime_type:file.type,base64:await file64(file)})}
async function submit(e){e.preventDefault();const form=e.currentTarget,f=new FormData(form),m=$("property-create-message");m.textContent="正在保存房源与材料…";try{if([...$("property-photos").files,...$("property-proofs").files].some(x=>x.size>4194304))throw new Error("单个文件最多4MB，请压缩后上传");const p=Object.fromEntries(f.entries());p.action="create_listing";p.authorization_confirmed=f.get("authorization_confirmed")==="yes";const result=await api("POST",p),id=result.record.id,photos=[...$("property-photos").files],proofs=[...$("property-proofs").files];for(const file of photos)await upload("listing",id,file,"photo");for(const file of proofs)await upload("listing",id,file,f.get("proof_category")||"authorization");form.reset();m.textContent="已进入待审核队列，共上传 "+(photos.length+proofs.length)+" 个文件。";await load()}catch(err){m.textContent=err.message}}

async function assignLead(id){const verified=(state.agents||[]).filter(x=>x.status==="verified");if(!verified.length)return alert("没有已认证经纪，不能分配线索");const hint=verified.map(x=>x.display_name+"："+x.id).join("\n");const agent=prompt("输入经纪ID：\n"+hint)||"";if(!agent)return;try{await api("POST",{action:"assign_lead",entity_id:id,agent_id:agent});await load()}catch(e){alert(e.message)}}
async function createRecord(kind){try{let body={};if(kind==="broker")body={action:"create_broker",legal_name:prompt("Broker法定名称")||"",license_number:prompt("Broker执照号")||"",email:prompt("联系邮箱")||"",phone:prompt("联系电话")||""};if(kind==="agent")body={action:"create_agent",display_name:prompt("经纪姓名")||"",license_number:prompt("执照号")||"",license_state:"NY",broker_id:prompt("所属Broker ID（可稍后补）")||"",email:prompt("邮箱")||"",phone:prompt("电话")||""};if(kind==="claim")body={action:"create_claim",claimant_name:prompt("认领人姓名")||"",relationship:prompt("与房源/主页关系")||"",listing_id:prompt("房源ID（认领主页可留空）")||"",agent_id:prompt("经纪主页ID（认领房源可留空）")||"",email:prompt("邮箱")||"",phone:prompt("电话")||""};await api("POST",body);await load()}catch(e){alert(e.message)}}
async function viewFiles(type,id){const files=(state.files||[]).filter(f=>f.entity_type===type&&f.entity_id===id);if(!files.length)return alert("暂无材料");let dialog=document.getElementById("property-file-dialog");if(!dialog){dialog=document.createElement("dialog");dialog.id="property-file-dialog";dialog.style.cssText="max-width:680px;width:90%;padding:24px;border:1px solid #dbe4eb;border-radius:12px";document.body.appendChild(dialog)}dialog.innerHTML='<h3>私有证明与房源图片</h3><p>链接仅用于本次核验，有效期5分钟；过期后请重新打开材料列表。</p><div data-files>正在准备文件…</div><form method="dialog"><button>关闭</button></form>';dialog.showModal();const list=dialog.querySelector('[data-files]');list.textContent='';for(const file of files){const row=document.createElement('p');row.textContent=file.original_name+'：准备中…';list.appendChild(row);try{const d=await api("GET?action=file_url&id="+encodeURIComponent(file.id));const url=new URL(d.url);if(url.protocol!=='https:')throw Error('文件地址无效');const a=document.createElement('a');a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';a.textContent=file.original_name+' · 打开 / 下载';row.replaceChildren(a)}catch(e){row.textContent=file.original_name+'：'+e.message}}}
window.createPropertyRecord=createRecord;window.viewPropertyFiles=viewFiles;
window.loadPropertyAdmin=load;
document.addEventListener("DOMContentLoaded",()=>{$("property-refresh")?.addEventListener("click",load);$("property-listing-form")?.addEventListener("submit",submit)});
document.addEventListener("trrb:admin-page-shown",e=>{if(e.detail?.page==="property-admin")load()});
})();
// Extend the existing property module; no second admin application.
(()=>{const panel=document.getElementById('property-admin-page');if(!panel)return;
const link=document.createElement('div');link.className='panel';link.id='property-brokers-panel';link.innerHTML='<h3>Broker 与材料管理</h3><button id="property-brokers-refresh" type="button">查看 Broker</button><div id="property-brokers-list"></div><h4>补录 / 更正执照号码</h4><select id="property-identity-type"><option value="broker">Broker</option><option value="agent">经纪</option></select><input id="property-identity-id" placeholder="记录 ID"><input id="property-identity-license" placeholder="执照号"><button id="property-identity-save" type="button">保存并重新审核</button><h4>关联经纪与 Broker</h4><select id="property-link-type"><option value="listing">房源 → 经纪</option><option value="agent">经纪 → Broker</option></select><input id="property-link-id" placeholder="房源或经纪 ID"><input id="property-link-target" placeholder="目标经纪或 Broker ID"><button id="property-link-save" type="button">保存关联</button><h4>上传执照或补充证明（单个最多4MB）</h4><select id="property-material-type"><option value="broker">Broker</option><option value="agent">经纪</option><option value="claim">认领</option><option value="listing">房源</option></select><input id="property-material-id" placeholder="对应记录 ID"><select id="property-material-category"><option value="license">执照证明</option><option value="broker_proof">Broker证明</option><option value="identity">认领身份证明</option><option value="authorization">挂牌授权</option><option value="ownership">产权证明</option><option value="photo">房源照片</option></select><input id="property-material-file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"><button id="property-material-save" type="button">上传材料</button><p id="property-material-result" role="status"></p>';
panel.appendChild(link);
const el=id=>document.getElementById(id);const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(body){const token=await window.getAdminAccessToken?.();if(!token)throw Error('请先登录后台');const r=await fetch('/.netlify/functions/property-admin',{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'操作失败');return d}
async function run(fn){const m=el('property-material-result');m.textContent='处理中…';try{await fn();m.textContent='已保存';await window.loadPropertyAdmin?.()}catch(e){m.textContent=e.message}}
el('property-brokers-refresh').onclick=()=>run(async()=>{const d=await call();el('property-brokers-list').innerHTML=d.brokers.map(b=>'<p><strong>'+escape(b.legal_name)+'</strong> · '+escape(b.license_number)+' · '+escape(b.status)+'<br><code>'+escape(b.id)+'</code> <button data-broker="'+b.id+'" data-status="verified">认证</button> <button data-broker="'+b.id+'" data-status="suspended">暂停</button> <button data-broker-files="'+b.id+'">查看材料</button></p>').join('')||'暂无 Broker';el('property-brokers-list').querySelectorAll('[data-broker]').forEach(button=>button.onclick=()=>run(()=>call({action:'set_status',entity_type:'broker',entity_id:button.dataset.broker,status:button.dataset.status})));el('property-brokers-list').querySelectorAll('[data-broker-files]').forEach(button=>button.onclick=()=>window.viewPropertyFiles('broker',button.dataset.brokerFiles))});
el('property-identity-save').onclick=()=>run(()=>call({action:'edit_identity',entity_type:el('property-identity-type').value,entity_id:el('property-identity-id').value.trim(),license_number:el('property-identity-license').value.trim()}));
el('property-link-save').onclick=()=>run(()=>call({action:'link_record',entity_type:el('property-link-type').value,entity_id:el('property-link-id').value.trim(),agent_id:el('property-link-target').value.trim(),broker_id:el('property-link-target').value.trim()}));
el('property-material-save').onclick=()=>run(async()=>{const f=el('property-material-file').files[0];if(!f||f.size>4194304)throw Error('请选择不超过4MB的文件');const base64=await new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(f)});await call({action:'upload_file',entity_type:el('property-material-type').value,entity_id:el('property-material-id').value.trim(),category:el('property-material-category').value,name:f.name,mime_type:f.type,base64})});
const help=document.querySelector('#property-photos + small');if(help)help.textContent='可多选，单个不超过4MB。';
})();
