(()=>{"use strict";
const $=id=>document.getElementById(id);let state=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(method="GET",body){const token=await window.getAdminAccessToken?.();if(!token)throw new Error("后台登录已失效");const endpoint=typeof method==="string"&&method.startsWith("GET?")?"/.netlify/functions/property-admin?"+method.slice(4):"/.netlify/functions/property-admin";if(method.startsWith("GET?"))method="GET";const r=await fetch(endpoint,{method,headers:{Authorization:"Bearer "+token,...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"请求失败（"+r.status+"）");return d}
const badge=s=>'<span class="property-badge property-'+esc(s)+'">'+esc(s)+"</span>";
function rows(items,type){return items.map(x=>'<tr><td><b>'+esc(x.title||x.display_name||x.claimant_name||x.contact_name||"—")+'</b><small>'+esc(x.address||x.email||x.claimant_email||x.contact_email||"")+'</small></td><td>'+esc(x.listing_type||x.license_number||x.relationship||x.message||"—")+'</td><td>'+badge(x.status)+'</td><td>'+esc(x.id)+'</td><td><select data-property-type="'+type+'" data-property-id="'+x.id+'"><option value="">审核操作</option>'+options(type)+'</select></td></tr>').join("")||'<tr><td colspan="5">暂无记录</td></tr>'}
function options(t){const m={listing:[["needs_evidence","补充证明"],["approved","审核通过"],["published","发布"],["rejected","拒绝"],["withdrawn","撤回"]],agent:[["verified","认证"],["rejected","拒绝"],["suspended","暂停"]],claim:[["approved","批准"],["needs_evidence","补充证明"],["rejected","拒绝"]],lead:[["contacted","已联系"],["closed","关闭"],["spam","垃圾"]]};return(m[t]||[]).map(x=>'<option value="'+x[0]+'">'+x[1]+"</option>").join("")}
function render(){const c=state.counts;$("property-counts").innerHTML=[["房源总数",c.listings],["待审房源",c.pendingListings],["待审经纪",c.pendingAgents],["待审认领",c.pendingClaims],["新线索",c.newLeads]].map(x=>"<article><strong>"+x[1]+"</strong><span>"+x[0]+"</span></article>").join("");$("property-listings-body").innerHTML=rows(state.listings,"listing");$("property-agents-body").innerHTML=rows(state.agents,"agent");$("property-claims-body").innerHTML=rows(state.claims,"claim");$("property-leads-body").innerHTML=rows(state.leads,"lead");document.querySelectorAll("[data-property-type]").forEach(s=>s.onchange=()=>changeStatus(s))}
async function load(){const m=$("property-message");m.textContent="正在读取房产后台…";try{state=await api();render();m.textContent="已刷新。房产证明文件保持私有，不生成公开地址。"}catch(e){m.textContent=e.message}}
async function changeStatus(s){if(!s.value)return;const note=prompt("审核备注（可以留空）","")||"";const publish=s.dataset.propertyType==="listing"&&s.value==="published";if(publish&&!confirm("确认资料、授权和证明均已核验，并立即发布该房源？")){s.value="";return}try{await api("POST",{action:"set_status",entity_type:s.dataset.propertyType,entity_id:s.dataset.propertyId,status:s.value,review_note:note,confirm_publish:publish});await load()}catch(e){alert(e.message)}}
const file64=file=>new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(String(r.result).split(",")[1]);r.onerror=no;r.readAsDataURL(file)});
async function upload(type,id,file,category){if(file.size>4194304)throw new Error(file.name+" 超过4MB，请压缩后上传");return api("POST",{action:"upload_file",entity_type:type,entity_id:id,category,name:file.name,mime_type:file.type,base64:await file64(file)})}
async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget),m=$("property-create-message");m.textContent="正在保存房源与材料…";try{const p=Object.fromEntries(f.entries());p.action="create_listing";p.authorization_confirmed=f.get("authorization_confirmed")==="yes";const result=await api("POST",p),id=result.record.id,photos=[...$("property-photos").files],proofs=[...$("property-proofs").files];for(const file of photos)await upload("listing",id,file,"photo");for(const file of proofs)await upload("listing",id,file,f.get("proof_category")||"authorization");e.currentTarget.reset();m.textContent="已进入待审核队列，共上传 "+(photos.length+proofs.length)+" 个文件。";await load()}catch(err){m.textContent=err.message}}

async function createRecord(kind){try{let body={};if(kind==="broker")body={action:"create_broker",legal_name:prompt("Broker法定名称")||"",license_number:prompt("Broker执照号")||"",email:prompt("联系邮箱")||"",phone:prompt("联系电话")||""};if(kind==="agent")body={action:"create_agent",display_name:prompt("经纪姓名")||"",license_number:prompt("执照号")||"",license_state:"NY",broker_id:prompt("所属Broker ID（可稍后补）")||"",email:prompt("邮箱")||"",phone:prompt("电话")||""};if(kind==="claim")body={action:"create_claim",claimant_name:prompt("认领人姓名")||"",relationship:prompt("与房源/主页关系")||"",listing_id:prompt("房源ID（认领主页可留空）")||"",agent_id:prompt("经纪主页ID（认领房源可留空）")||"",email:prompt("邮箱")||"",phone:prompt("电话")||""};await api("POST",body);await load()}catch(e){alert(e.message)}}
async function viewFiles(type,id){const files=(state.files||[]).filter(f=>f.entity_type===type&&f.entity_id===id);if(!files.length)return alert("暂无材料");for(const file of files){const d=await api("GET?action=file_url&id="+encodeURIComponent(file.id));window.open(d.url,"_blank","noopener")}}
window.createPropertyRecord=createRecord;window.viewPropertyFiles=viewFiles;
window.loadPropertyAdmin=load;
document.addEventListener("DOMContentLoaded",()=>{$("property-refresh")?.addEventListener("click",load);$("property-listing-form")?.addEventListener("submit",submit)});
document.addEventListener("trrb:admin-page-shown",e=>{if(e.detail?.page==="property-admin")load()});
})();