const SITE = "https://trrb.net";
export const config = { path: "/news-sitemap.xml" };
const FALLBACK: Record<string,string> = {"重要新闻":"important-news","热门头条":"hot","美国时政":"us-politics","美国警情":"us-crime","中国官场":"china-officialdom","移民美国":"immigration","庇护百科":"asylum","驱逐快报":"deport","ICE执法动态":"ice","ICE执法":"ice","曝光墙":"expose"};
const clean=(v:unknown)=>String(v??"").replace(/\s+/g," ").trim();
const esc=(v:unknown)=>clean(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;");
function cfg(){const base=(Deno.env.get("SUPABASE_URL")||"").replace(/\/+$/,'');const key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_ANON_KEY")||"";return{base,key};}
async function rows(path:string,params:Record<string,string>){const{base,key}=cfg();if(!base||!key)throw new Error("Supabase config missing");const u=new URL(`${base}/rest/v1/${path}`);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{cache:"no-store",headers:{apikey:key,Authorization:`Bearer ${key}`,Accept:"application/json"}});if(!r.ok)throw new Error(`${path} ${r.status}`);const j=await r.json();return Array.isArray(j)?j:[];}
function section(a:any,byId:Map<string,any>,byName:Map<string,any>){const t=clean(a.topic_key).toLowerCase();if(t==="trump")return"trump";if(t==="ice")return"ice";return clean(byId.get(String(a.category_id||""))?.slug)||clean(byName.get(clean(a.category_name))?.slug)||FALLBACK[clean(a.category_name)]||"news";}
export default async(request:Request,context:any)=>{if(!["GET","HEAD"].includes(request.method))return context.next();try{const [cats,articles]=await Promise.all([rows("categories",{select:"id,name,slug,is_active,include_in_google_news",is_active:"eq.true",limit:"500"}),rows("articles",{select:"id,title,slug,category_id,category_name,topic_key,status,published_at,created_at",status:"eq.published",order:"published_at.desc.nullslast,created_at.desc",limit:"1000"})]);const ids=new Set(cats.filter((x:any)=>x.include_in_google_news!==false).map((x:any)=>String(x.id)));const names=new Set(cats.filter((x:any)=>x.include_in_google_news!==false).map((x:any)=>clean(x.name)));const byId=new Map(cats.map((x:any)=>[String(x.id||""),x]));const byName=new Map(cats.map((x:any)=>[clean(x.name),x]));const now=Date.now(),cutoff=now-48*60*60*1000;const blocks=[];for(const a of articles){const ts=Date.parse(a.published_at||a.created_at||"");if(!Number.isFinite(ts)||ts<cutoff||ts>now+300000||!clean(a.title))continue;if(cats.length&&a.category_id&&!ids.has(String(a.category_id)))continue;if(cats.length&&!a.category_id&&a.category_name&&!names.has(clean(a.category_name)))continue;const slug=clean(a.slug)||clean(a.id);if(!slug)continue;const loc=`${SITE}/${encodeURIComponent(section(a,byId,byName))}/${encodeURIComponent(slug)}`;blocks.push(`  <url>\n    <loc>${esc(loc)}</loc>\n    <news:news>\n      <news:publication><news:name>唐人日报</news:name><news:language>zh-cn</news:language></news:publication>\n      <news:publication_date>${new Date(ts).toISOString()}</news:publication_date>\n      <news:title>${esc(a.title)}</news:title>\n    </news:news>\n  </url>`);if(blocks.length>=1000)break;}const xml=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">\n${blocks.join("\n")}\n</urlset>\n`;return new Response(request.method==="HEAD"?null:xml,{status:200,headers:{"content-type":"application/xml; charset=UTF-8","cache-control":"public, max-age=30, stale-while-revalidate=60","x-trrb-news-sitemap":"live-supabase-v1","x-trrb-news-count":String(blocks.length)}});}catch(e){console.error("live news sitemap failed",e);return context.next();}};
