begin;

-- Public registration attempts are performed by a Netlify Function using the
-- service role. This table is intentionally inaccessible to browser clients.
create table if not exists public.account_registration_attempts (
  id bigint generated by default as identity primary key,
  identifier_hash text not null check (char_length(identifier_hash) = 64),
  ip_hash text not null check (char_length(ip_hash) = 64),
  was_created boolean not null default false,
  attempted_at timestamptz not null default now()
);

create index if not exists account_registration_attempts_identifier_time_idx
  on public.account_registration_attempts(identifier_hash, attempted_at desc);
create index if not exists account_registration_attempts_ip_time_idx
  on public.account_registration_attempts(ip_hash, attempted_at desc);

alter table public.account_registration_attempts enable row level security;
revoke all on public.account_registration_attempts from anon, authenticated;
grant all on public.account_registration_attempts to service_role;
grant usage, select on sequence public.account_registration_attempts_id_seq to service_role;

create or replace function public.trrb_avatar_initial(value text)
returns text
language sql
immutable
set search_path = public
as $$
  select upper(left(btrim(coalesce(value, '')), 1))
$$;

create or replace function public.trrb_initial_avatar_key(value text)
returns text
language sql
immutable
set search_path = public
as $$
  select 'initial:' || coalesce(nullif(public.trrb_avatar_initial(value), ''), '用')
$$;

create or replace function public.trrb_unique_account_name(
  requested_name text,
  account_email text,
  account_phone text
)
returns text
language plpgsql
set search_path = public
as $$
declare
  base_name text;
  candidate text;
  phone_digits text;
  i integer;
begin
  phone_digits := regexp_replace(coalesce(account_phone, ''), '[^0-9]', '', 'g');
  base_name := btrim(coalesce(
    nullif(requested_name, ''),
    nullif(split_part(coalesce(account_email, ''), '@', 1), ''),
    case when phone_digits <> '' then '用户' || right(phone_digits, 4) end,
    '新用户'
  ));
  base_name := left(base_name, 24);
  if char_length(base_name) < 2 or public.trrb_name_is_reserved(base_name) then
    base_name := '用户' || right(md5(coalesce(account_email, '') || coalesce(account_phone, '') || random()::text), 6);
  end if;

  for i in 0..99 loop
    candidate := case when i = 0 then base_name else left(base_name, 27) || i::text end;
    if not exists(select 1 from public.profiles p where lower(p.display_name) = lower(candidate)) then
      return candidate;
    end if;
  end loop;
  return '用户' || right(md5(gen_random_uuid()::text), 10);
end;
$$;

create or replace function public.handle_new_trrb_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  account_name text;
begin
  account_name := public.trrb_unique_account_name(
    new.raw_user_meta_data ->> 'display_name',
    new.email,
    new.phone
  );
  insert into public.profiles(id, display_name, avatar_key, is_custom_name, is_custom_avatar)
  values(new.id, account_name, public.trrb_initial_avatar_key(account_name), false, false)
  on conflict(id) do nothing;
  insert into public.notification_preferences(user_id) values(new.id) on conflict(user_id) do nothing;
  return new;
end;
$$;

revoke all on function public.handle_new_trrb_user() from public, anon, authenticated;

create or replace function public.validate_trrb_profile_settings()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  auto_initial_change boolean := false;
begin
  new.display_name := btrim(new.display_name);
  new.bio := btrim(coalesce(new.bio, ''));

  if char_length(new.display_name) < 2 or char_length(new.display_name) > 32 then
    raise exception 'display_name_length_invalid';
  end if;
  if public.trrb_name_is_reserved(new.display_name) then
    raise exception 'display_name_reserved';
  end if;
  if char_length(new.bio) > 240 then
    raise exception 'bio_length_invalid';
  end if;

  if tg_op = 'UPDATE'
     and new.display_name is distinct from old.display_name
     and not old.is_custom_avatar
     and new.avatar_key = old.avatar_key then
    new.avatar_key := public.trrb_initial_avatar_key(new.display_name);
    new.is_custom_avatar := false;
    auto_initial_change := true;
  end if;

  if not (
    new.avatar_key ~ '^avatar_(00[1-9]|0[1-9][0-9]|1[01][0-9]|120)$'
    or (left(new.avatar_key, 8) = 'initial:' and char_length(substr(new.avatar_key, 9)) = 1)
  ) then
    raise exception 'avatar_key_invalid';
  end if;

  if tg_op = 'UPDATE' then
    if new.display_name is distinct from old.display_name then new.is_custom_name := true; end if;
    if new.avatar_key is distinct from old.avatar_key and not auto_initial_change then new.is_custom_avatar := true; end if;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

update public.profiles
set avatar_key = public.trrb_initial_avatar_key(display_name), updated_at = now()
where not is_custom_avatar;

comment on table public.account_registration_attempts is
  'Server-only rate-limit audit for login-or-register account creation. Contains keyed hashes only, never raw email addresses, phone numbers, passwords, or tokens.';

commit;
