create table if not exists public.uscis_asylum_data_releases (
  id uuid primary key default gen_random_uuid(),
  source_url text not null unique,
  source_title text not null,
  fiscal_year integer not null check (fiscal_year between 2000 and 2100),
  period_end date,
  source_published_at date,
  source_fingerprint text not null,
  official boolean not null default true,
  status text not null default 'published' check (status in ('published', 'superseded', 'rejected')),
  metadata jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.uscis_asylum_office_monthly (
  id bigint generated by default as identity primary key,
  release_id uuid not null references public.uscis_asylum_data_releases(id) on delete cascade,
  source_url text not null,
  fiscal_year integer not null check (fiscal_year between 2000 and 2100),
  period date not null,
  office text not null,
  applications_received integer check (applications_received is null or applications_received >= 0),
  cases_completed integer check (cases_completed is null or cases_completed >= 0),
  cases_pending integer check (cases_pending is null or cases_pending >= 0),
  interviews_completed integer check (interviews_completed is null or interviews_completed >= 0),
  grants integer check (grants is null or grants >= 0),
  deny_referrals integer check (deny_referrals is null or deny_referrals >= 0),
  admin_close_dismissals integer check (admin_close_dismissals is null or admin_close_dismissals >= 0),
  has_suppressed_values boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_url, office, period)
);

create table if not exists public.uscis_asylum_nationality_monthly (
  id bigint generated by default as identity primary key,
  release_id uuid not null references public.uscis_asylum_data_releases(id) on delete cascade,
  source_url text not null,
  fiscal_year integer not null check (fiscal_year between 2000 and 2100),
  period date not null,
  nationality text not null,
  applications_received integer check (applications_received is null or applications_received >= 0),
  has_suppressed_values boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_url, nationality, period)
);

create index if not exists uscis_asylum_office_monthly_release_idx
  on public.uscis_asylum_office_monthly (release_id, office, period);
create index if not exists uscis_asylum_office_monthly_period_idx
  on public.uscis_asylum_office_monthly (period desc);
create index if not exists uscis_asylum_nationality_monthly_release_idx
  on public.uscis_asylum_nationality_monthly (release_id, nationality, period);

alter table public.uscis_asylum_data_releases enable row level security;
alter table public.uscis_asylum_office_monthly enable row level security;
alter table public.uscis_asylum_nationality_monthly enable row level security;

drop policy if exists "Public reads published USCIS asylum releases" on public.uscis_asylum_data_releases;
create policy "Public reads published USCIS asylum releases"
  on public.uscis_asylum_data_releases for select
  to anon, authenticated
  using (official = true and status = 'published');

drop policy if exists "Public reads USCIS asylum office statistics" on public.uscis_asylum_office_monthly;
create policy "Public reads USCIS asylum office statistics"
  on public.uscis_asylum_office_monthly for select
  to anon, authenticated
  using (exists (
    select 1 from public.uscis_asylum_data_releases releases
    where releases.id = release_id and releases.official = true and releases.status = 'published'
  ));

drop policy if exists "Public reads USCIS asylum nationality statistics" on public.uscis_asylum_nationality_monthly;
create policy "Public reads USCIS asylum nationality statistics"
  on public.uscis_asylum_nationality_monthly for select
  to anon, authenticated
  using (exists (
    select 1 from public.uscis_asylum_data_releases releases
    where releases.id = release_id and releases.official = true and releases.status = 'published'
  ));

revoke all on table public.uscis_asylum_data_releases from anon, authenticated;
revoke all on table public.uscis_asylum_office_monthly from anon, authenticated;
revoke all on table public.uscis_asylum_nationality_monthly from anon, authenticated;
grant select on table public.uscis_asylum_data_releases to anon, authenticated;
grant select on table public.uscis_asylum_office_monthly to anon, authenticated;
grant select on table public.uscis_asylum_nationality_monthly to anon, authenticated;
grant select, insert, update, delete on table public.uscis_asylum_data_releases to service_role;
grant select, insert, update, delete on table public.uscis_asylum_office_monthly to service_role;
grant select, insert, update, delete on table public.uscis_asylum_nationality_monthly to service_role;
grant usage, select on sequence public.uscis_asylum_office_monthly_id_seq to service_role;
grant usage, select on sequence public.uscis_asylum_nationality_monthly_id_seq to service_role;
