begin;

create table if not exists public.automation_notifications (
  id bigint generated by default as identity primary key,
  control_key text references public.automation_controls(control_key) on delete set null,
  severity text not null default 'error' check (severity in ('info', 'warning', 'error', 'success')),
  title text not null,
  message text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create index if not exists automation_notifications_created_at_idx
  on public.automation_notifications(created_at desc);

alter table public.automation_notifications enable row level security;

drop policy if exists "automation notifications admin read" on public.automation_notifications;
create policy "automation notifications admin read"
  on public.automation_notifications
  for select
  to authenticated
  using (public.is_jobs_admin());

revoke all on public.automation_notifications from anon;
revoke insert, update, delete on public.automation_notifications from authenticated;
grant select on public.automation_notifications to authenticated;
grant select, insert, update, delete on public.automation_notifications to service_role;
grant usage, select on sequence public.automation_notifications_id_seq to service_role;

comment on table public.automation_notifications is
  'In-admin alerts for robot dispatch, cancellation, gate, and workflow failures.';

commit;
