const {rest,SUPABASE_URL,SERVICE_KEY,safeText}=require('./supabase-admin');
const uuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(String(v||''));
const fail=(message,statusCode=400)=>{throw Object.assign(new Error(message),{statusCode})};
const one=async(table,id)=>uuid(id)?(await rest(table,{query:{id:'eq.'+id,limit:'1'}}))[0]:null;
async function verifiedAgent(id){const a=await one('property_agents',id);if(!a||a.status!=='verified')return null;const b=await one('property_brokers',a.broker_id);return b?.status==='verified'?{...a,broker:b}:null}
async function evidence(type,id){return rest('property_files',{query:{entity_type:'eq.'+type,entity_id:'eq.'+id,select:'id,category,storage_path,mime_type,original_name,size_bytes'}})}
function evidenceReady(files){return files.some(x=>x.category==='photo'&&x.mime_type.startsWith('image/'))&&files.some(x=>['ownership','authorization'].includes(x.category))}
async function publishable(row){if(!row?.authorization_confirmed||!row.agent_id)return false;const a=await verifiedAgent(row.agent_id);if(!a||row.broker_id!==a.broker_id)return false;return evidenceReady(await evidence('listing',row.id))}
async function audit(user,action,type,id,detail={}){await rest('property_admin_audit',{method:'POST',prefer:'return=minimal',body:{actor_user_id:user.id,actor_email:user.email||null,action,entity_type:type,entity_id:id,detail}})}
function decodeFile(b){const mime=safeText(b.mime_type,80),data=String(b.base64||'');if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(mime))fail('只支持 JPG、PNG、WebP、PDF');if(data.length>5592410||!/^[A-Za-z0-9+/]*={0,2}$/.test(data))fail('文件无效或超过4MB');const bytes=Buffer.from(data,'base64');if(!bytes.length||bytes.length>4194304)fail('单个文件不得超过4MB');const valid=mime==='application/pdf'?bytes.subarray(0,5).toString()==='%PDF-':mime==='image/png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):mime==='image/jpeg'?bytes[0]===255&&bytes[1]===216&&bytes[2]===255:bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP';if(!valid)fail('文件内容与格式不符');if(b.category==='photo'&&!mime.startsWith('image/'))fail('房源照片必须是图片');return{bytes,mime}}
async function upload(user,b){if(!['listing','agent','broker','claim'].includes(b.entity_type)||!uuid(b.entity_id))fail('文件关联对象无效');if(!['photo','ownership','authorization','license','broker_proof','identity','other'].includes(b.category))fail('材料类型无效');const {bytes,mime}=decodeFile(b);const bucket=b.category==='photo'?'property-photos':'property-private',ext=mime==='application/pdf'?'pdf':mime.split('/')[1],path=b.entity_type+'/'+b.entity_id+'/'+crypto.randomUUID()+'.'+ext;const response=await fetch(SUPABASE_URL+'/storage/v1/object/'+bucket+'/'+path,{method:'POST',headers:{apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'content-type':mime},body:bytes});if(!response.ok)fail('文件上传失败，请重试',502);const rows=await rest('property_files',{method:'POST',prefer:'return=representation',body:{entity_type:b.entity_type,entity_id:b.entity_id,category:b.category,storage_path:bucket+':'+path,original_name:safeText(b.name,180)||'文件.'+ext,mime_type:mime,size_bytes:bytes.length,uploaded_by:user.id}});await audit(user,'file.uploaded',b.entity_type,b.entity_id,{file_id:rows[0].id,category:b.category});return rows[0]}
async function fileUrl(file){const split=file.storage_path.indexOf(':'),bucket=split<0?'property-private':file.storage_path.slice(0,split),path=split<0?file.storage_path:file.storage_path.slice(split+1);if(bucket==='property-photos')return SUPABASE_URL+'/storage/v1/object/public/property-photos/'+path;const r=await fetch(SUPABASE_URL+'/storage/v1/object/sign/property-private/'+path,{method:'POST',headers:{apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'content-type':'application/json'},body:JSON.stringify({expiresIn:300})});if(!r.ok)fail('无法打开证明材料',502);const d=await r.json();return SUPABASE_URL+'/storage/v1'+d.signedURL}
module.exports={uuid,fail,one,verifiedAgent,evidence,evidenceReady,publishable,audit,upload,fileUrl,decodeFile};
